### ISSUE TITLE
Set listening time

### ISSUE THREAD

**Issue by csal3** [Uberi/speech_recognition#101]
Sometimes the speech recogniser stops listening and tries to guess the utterance even if nothing was uttered. Now I am trying to let the speech recogniser to record for 3 seconds (for example) instead of waiting for the energy threshold to change. Which duration parameter should I change? When I am changing the duration of listen(), when timed out the program stops due to timeout error.
Thanks for your help!

**Comment by Uberi** [comment]
Hi @csal3,

It sounds like you're looking for [recognizer_instance.record](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instancerecordsource-duration--none-offset--none). Also, if you're getting cut off before you're done speaking, also consider adjusting [recognizer_instance.pause_threshold](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instancepause_threshold--08) to a slightly higher value. The pause threshold is the number of seconds of silence before it considers you done speaking.

**Comment by csal3** [comment]
Thanks for your reply. I have adjusted both the pause threshold and also the energy threshold and have better results. However sometimes at start up the system tries to guess the word even when nothing is uttered and then it works correctly. But I guess maybe it is something to do with the microphone or how the system is being used.

**Comment by Uberi** [comment]
Seems like this issue is now resolved, especially with the tuning on the VAD in recent versions! Please reopen if there are any remaining issues.
