### ISSUE TITLE
Error for Pyaudio 0.2.9 version 

### ISSUE THREAD

**Issue by javiisanchez** [Uberi/speech_recognition#104]
Hello!

I installed all modules for use the SpeechRecognition, and I checked that the modules was in the python modules.
When I check the examples for use this SpeechRecognition in Terminal do the next:

Traceback (most recent call last):
  File "background_listening.py", line 19, in <module>
    m = sr.Microphone()
  File "/home/javier/.local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 55, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/home/javier/.local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 88, in get_pyaudio
    raise AttributeError("PyAudio 0.2.9 or later is required (found version {0})".format(pyaudio.__version__))
AttributeError: PyAudio 0.2.9 or later is required (found version 0.2.8)

Why this function does this? because my version of pyaudio is 0.2.9.

I will like that somebody help me please
Thanks.

**Comment by Uberi** [comment]
Hi @javiisanchez,

Your version of PyAudio is 0.2.8, not 0.2.9. You'll need to install version 0.2.9.

If you need any assistance with upgrading your PyAudio installation, please provide the rest of the information outlined in the issue template (such as OS version, Python version, library version, how you installed PyAudio, etc.).

**Comment by javiisanchez** [comment]
Thanks  Uberi,

That problem was solved yet. I'm trying the examples now, and could recognize a phrase stored in a wav file. However when I try to get audio directly from the microphone (microphone_recognition.py) the script execution gets stucked at .listen(source)

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
Say something!
....

OS version: Ubuntu 14.04LTS, Python version: 2.7 , library version: Speech Reggnition 3.4

**Comment by jhoelzl** [comment]
@javiisanchez, have you tried this: https://github.com/Uberi/speech_recognition#on-ubuntudebian-i-get-annoying-output-in-the-terminal-saying-things-like-bt_audio_service_open--connection-refused-and-various-others to get rid of the "Unknown PCM cards.pcm" messages?

**Comment by Uberi** [comment]
@javiisanchez,

Does the `arecord` command manage to record anything? What's your hardware like? In particular, the microphone.

**Comment by sravanth1** [comment]
how did the error in the question go? @javiisanchez

**Comment by Uberi** [comment]
Sounds like @javiisanchez managed to get things working - feel free to re-open if the issue persists!

**Comment by lvivtotoro** [comment]
The issue persists. I use a USB microphone (Plantronics Gamecom 780). `pip list` tells me that I have PyAudio 0.2.9 and yet `speech_recognition` finds 0.2.7.

**Comment by Uberi** [comment]
Hi @lvivtotoro,

Here are a few things that might be causing this:

* You might be using `pip3 list` and running `python2 X.py`, or `pip2 list` and running `python3 X.py`. In other words, mismatched Python versions, where one being run has PyAudio 0.2.7, and the one being listed has PyAudio 0.2.9.
* You might have the old version installed locally. On POSIX, check your `~/.local/lib/*` folders for the old package version.

If that doesn't work and you're on a POSIX system, run the following command, and post the output: `python -c 'import pyaudio as a;print(a.__version__, a.__file__)'`.

If that doesn't work and you're on Windows, make sure that you've uninstalled old versions.

**Comment by Shai1436** [comment]
Hi, I was facing the same problem. I downloaded the file PyAudio-0.2.9.tar.gz from the link https://people.csail.mit.edu/hubert/pyaudio/packages. Then extract and cd to the folder then install PyAudio. 
Hope this helps.

**Comment by allanis79** [comment]
@Uberi I am having the same problem. This is the output of "python -c 'import pyaudio as a;print(a.__version__, a.__file__)'"

('0.2.7', '/usr/lib/python2.7/dist-packages/pyaudio.pyc')

Can you tell me how I can solve this?

**Comment by Uberi** [comment]
Hi @allanis79,

You have PyAudio 0.2.7, but you need 0.2.9. Please upgrade your PyAudio version, as the error says.

**Comment by allanis79** [comment]
@Uberi 
Thank for your reply. I was able ot solve the issue myself. But I am getting the following error: 
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Say something!
Traceback (most recent call last):
  File "./jarvis.py", line 52, in <module>
    data = recordAudio()
  File "./jarvis.py", line 19, in recordAudio
    audio = r.listen(source)
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 531, in listen
    assert source.stream is not None, "Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

I found a link where you addressed this issue, but still I was not able to solve it. Can I know how I can solve this?

**Comment by Uberi** [comment]
Hi @allanis79,

Please refer to the documentation and examples for how to use this library. It seems like you want the [microphone recognition example](https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py).

The error actually describes exactly what the issue is:

> Audio source must be entered before listening, see documentation for `AudioSource`; are you using source outside of a `with` statement?

Namely, you need to use the audio source within a `with` statement.

**Comment by allanis79** [comment]
@Uberi 

Hey I am trying to run the code from this link [https://pythonspot.com/en/personal-assistant-jarvis-in-python/](url). As you mentioned, i changed the code on line 19 and now it's in the with statement. 
But still I am getting the following error: 
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

I am not using any bluetooth speaker. I am using my iphone earphone plugged into my CPU.

**Comment by Uberi** [comment]
Hi @allanis79,

It looks like it is actually listening properly. Have you set the device index correctly? You can do this by replacing `Microphone()` with `Microphone(device_index=INDEX_OF_YOUR_MICROPHONE)`

Try running the following code and posting the output here:

```python
import speech_recognition as sr
for index, name in enumerate(sr.Microphone.list_microphone_names()):
    print("Microphone with name \"{1}\" found for `Microphone(device_index={0})`".format(index, name))
```

This output will help you determine what the value of INDEX_OF_YOUR_MICROPHONE should be.

**Comment by allanis79** [comment]
hi @Uberi ,

This is the output of the above code snippet:

> /usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/allani/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Microphone with name "HDA Intel PCH: ALC262 Analog (hw:0,0)" found for `Microphone(device_index=0)`
Microphone with name "HDA Intel PCH: ALC262 Alt Analog (hw:0,2)" found for `Microphone(device_index=1)`
Microphone with name "HDA NVidia: HDMI 0 (hw:1,3)" found for `Microphone(device_index=2)`
Microphone with name "HDA NVidia: HDMI 1 (hw:1,7)" found for `Microphone(device_index=3)`
Microphone with name "HDA NVidia: HDMI 2 (hw:1,8)" found for `Microphone(device_index=4)`
Microphone with name "HDA NVidia: HDMI 3 (hw:1,9)" found for `Microphone(device_index=5)`
Microphone with name "sysdefault" found for `Microphone(device_index=6)`
Microphone with name "pulse" found for `Microphone(device_index=7)`
Microphone with name "default" found for `Microphone(device_index=8)`

**Comment by Uberi** [comment]
Sounds like you either want device index 0, 1, or 8. Try those values with the instructions above and see if it listens after that.

Also check out the calibrate_energy_threshold example and see if calibrating makes the recognition work: https://github.com/Uberi/speech_recognition/blob/master/examples/calibrate_energy_threshold.py
