### ISSUE TITLE
 Is there any way to use older version of port audio with speech_recognition?

### ISSUE THREAD

**Issue by obayhan** [Uberi/speech_recognition#105]
when i am trying to use :

`audio = r.listen(sr.Microphone(device_index=i))`

gives me 

> 
> ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> bt_audio_service_open: connect() failed: Connection refused (111)
> bt_audio_service_open: connect() failed: Connection refused (111)
> bt_audio_service_open: connect() failed: Connection refused (111)
> bt_audio_service_open: connect() failed: Connection refused (111)
> ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started

and then

> Audio source must be opened before recording - see documentation for `AudioSource`

I found that is about the  pyaudio and portaudio.

My system is Ubuntu 14.04. Is there any way to use older version of port audio with speech_recognition?

**Comment by Uberi** [comment]
Your PortAudio version is working fine, but your code is incorrect. According to the error message:

    Audio source must be opened before recording - see documentation for `AudioSource`

Refer to the [documentation](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#microphonedevice_index--none-sample_rate--16000-chunk_size--1024):

> Instances of this class are context managers, and are designed to be used with with statements

The very next line also gives an example:

```python
with Microphone() as source:    # open the microphone and start recording
    pass                        # do things here - ``source`` is the Microphone instance created above
                                # the microphone is automatically released at this point
```

There are also 6 working examples in the [examples](https://github.com/Uberi/speech_recognition#examples) section of the README. I highly recommend reading the README, or at least skimming through it.

**Comment by obayhan** [comment]
I tried 

`with Microphone(device_index=i) as source:`

first. Then i tried 

`audio = r.listen(sr.Microphone(device_index=i))`

So sorry but my code is correct but Port Audio has problems. Because i got the same result with your example >> [https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py](https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py)

**Comment by Uberi** [comment]
I highly doubt the unmodified microphone recognition example can give a `Audio source must be opened before recording - see documentation for AudioSource` error. Have you modified the example?

Please post full code listings. For example, `with Microphone(device_index=i) as source:` is not a valid Python program.

Does the unmodified [audio transcribe](https://github.com/Uberi/speech_recognition/blob/master/examples/audio_transcribe.py) example work?
