### ISSUE TITLE
flac is not found on i686 system

### ISSUE THREAD

**Issue by rolfschr** [Uberi/speech_recognition#108]
Steps to reproduce
------------------

Install SpeechRecognition on i686 system using pip.

```
In [1]: import platform

In [2]: platform.system()
Out[2]: 'Linux'

In [3]: platform.machine()
Out[3]: 'i686'

```

Expected behaviour
------------------

I can run any of the example files

Actual behaviour
----------------

Flac "cannot be found". 
```
$ py audio_transcribe.py
Traceback (most recent call last):
  File "audio_transcribe.py", line 14, in <module>
    with sr.AudioFile(AUDIO_FILE) as source:
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 186, in __enter__
    flac_converter = get_flac_converter()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 891, in get_flac_converter
    raise OSError("FLAC conversion utility not available - consider installing the FLAC command line application using `brew install flac` or your operating system's equivalent")
OSError: FLAC conversion utility not available - consider installing the FLAC command line application using `brew install flac` or your operating system's equivalent
```

Flac actually runs fine.
```
$ /usr/local/lib/python2.7/dist-packages/speech_recognition/flac-linux-x86 
===============================================================================
flac - Command-line FLAC encoder/decoder version 1.3.1
...
```

I'm no hardware expert, but I believe test `machine()` test should be more flexible and allow ``i686``:

`elif system == "Linux" and platform.machine() in ["i386", "x86", "x86_64", "AMD64"]:`

System information
------------------

My **Python version** is Python 2.7.6 (default, Mar 22 2014, 22:59:38)

$ python -c "import speech_recognition as sr;print(sr.__version__)"
3.4.3

I **installed PocketSphinx from** ``pip install pocketsphinx``

**Comment by Uberi** [comment]
Thanks @rolfschr, I've added all of the missing machine types I could think of in 36fef2b9df6cb08b868396b128796d5c33bc5d47. Expect to see this in the next release!

**Comment by Uberi** [comment]
This is now part of version 3.4.4. Thanks for reporting!
