### ISSUE TITLE
audioop.error: Size should be 1, 2 or 4

### ISSUE THREAD

**Issue by danse** [Uberi/speech_recognition#110]
Steps to reproduce:

Try to convert the short audio sample here attached, with a few lines of code similar to the first lines in the [Transcribe an audio file](https://github.com/Uberi/speech_recognition/blob/master/examples/audio_transcribe.py) example

[archive.zip](https://github.com/Uberi/speech_recognition/files/223504/archive.zip)

Expected behaviour
------------------

The audio is converted to a source

Actual behaviour
----------------

While running `audio = r.record(source)`, an exception is thrown:

        buffer = audioop.tomono(buffer, sample_width, 1, 1) # convert stereo audio data to mono
        audioop.error: Size should be 1, 2 or 4

System information
------------------

My **Python version** is 2.7.10

My **SpeechRecognition library version** is 3.4.3

My **PyAudio library version** is 0.2.9

**Comment by danse** [comment]
Using `print` i found out that `sample_width` is 3 in my case

**Comment by Uberi** [comment]
This is indeed an issue for Pythons before 3.4. The next version will address this.

**Comment by danse** [comment]
Coul you paste the link to the upstream issue?

**Comment by Uberi** [comment]
https://bugs.python.org/issue12866

We're going to shim this behaviour in Python <3.4, so it'll still work, but be slower on those versions. This will be in the next version.

**Comment by danse** [comment]
Perfect, thanks for the great support on this lib! :+1:

**Comment by Uberi** [comment]
This has been fixed in 3.4.4. Thanks for reporting!

**Comment by danse** [comment]
Thanks to you :+1:
