### ISSUE TITLE
How to fix the chunk  eoferror?

### ISSUE THREAD

**Issue by hillerliao** [Uberi/speech_recognition#112]
environment:
python2.7
I'm sure the local wav file exists.

'''
import speech_recognition as sr
from os import path
file_path = path.join(path.dirname(path.realpath(__file__)), "english.wav")
r = sr.Recognizer() 
with sr.WavFile(file_path) as source:  
    audio = r.record(source)
IBM_USERNAME = 'myemail'  
IBM_PASSWORD= 'mypw'  
text = r.recognize_ibm(audio, username = IBM_USERNAME, password = IBM_PASSWORD, language = 'en-US')    
print text
'''

when running:

'''
Traceback (most recent call last):
  File "speech2text.py", line 14, in <module>
    with sr.WavFile(file_path) as source:  
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 195, in __enter__
    self.audio_reader = aifc.open(aiff_file, "rb")
  File "/usr/lib/python2.7/aifc.py", line 949, in open
    return Aifc_read(f)
  File "/usr/lib/python2.7/aifc.py", line 347, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/aifc.py", line 298, in initfp
    chunk = Chunk(file)
  File "/usr/lib/python2.7/chunk.py", line 63, in __init__
    raise EOFError
EOFError
'''

**Comment by Uberi** [comment]
Please fill out the issue template. In particular, the code you are using, and the audio file that causes the error.

**Comment by hillerliao** [comment]
updated

**Comment by Uberi** [comment]
@hillerliao,

Thanks for posting the code, but please also upload the audio file that causes the issue (the WAV file that you mentioned). GitHub allows you to attach files directly to your messages.

**Comment by hillerliao** [comment]
this file,thx

https://github.com/Uberi/speech_recognition/blob/master/examples/english.wav

[english.wav.zip](https://github.com/Uberi/speech_recognition/files/229041/english.wav.zip)

**Comment by hillerliao** [comment]
In fact I made a mistake: the file i downloaded was an html page, not the raw wav file of 'english.wave'

**Comment by Uberi** [comment]
Glad to hear you found the solution.
