### ISSUE TITLE
After Update to Version 3.4.4: ('Unexpected error:', <class 'audioop.error'>

### ISSUE THREAD

**Issue by jhoelzl** [Uberi/speech_recognition#116]
Hello,

after update from 3.4.3 to 3.4.4 i always get this error when doing an ASR request from an audio file (independent on the recognition service):

`
('Unexpected error:', <class 'audioop.error'>`

I tried several audio formats and sampling frequencies, everytime the same.
When doing the ASR request with microphone as audio source, everything works.

I am using Python 2.7.6 on Ubuntu 14.04.

Thanks.

**Comment by Uberi** [comment]
Hi @jhoelzl,

Version 3.4.5 should fix this issue. Give it a try and re-open if it happens again!
