### ISSUE TITLE
Online demos

### ISSUE THREAD

**Issue by johnfelipe** [Uberi/speech_recognition#119]
Can i view online demos?

**Comment by Uberi** [comment]
You can try online demos for the individual, third-party services this library supports:

* [Google](https://www.google.com/intl/en/chrome/demos/speech.html)
* [Wit.ai](https://labs.wit.ai/demo/index.html)
* [Microsoft Oxford](https://www.microsoft.com/cognitive-services/en-us/speech-api)
* [IBM Speech to Text](https://speech-to-text-demo.mybluemix.net/)

CMU Sphinx and api.ai don't have any online demos that I'm aware of.

**Comment by johnfelipe** [comment]
can i build IBM Speech to Text no using bluemix and create account?

**Comment by Uberi** [comment]
I don't understand what you're trying to say. What's a "no using", and what account would be created here?

**Comment by johnfelipe** [comment]
I have account for 28 days in

https://idaas.iam.ibm.com/idaas/mtfim/sps/authsvc?PolicyId=urn:ibm:security:authentication:asf:basicldapuser

using voice to text IBM

Can i create something with this library no using that account?

**Comment by Uberi** [comment]
I assume you mean your trial expired, and you'd like to use the library with BlueMix without an account.

This is not possible. I recommend you try a service that has a free tier instead.

**Comment by johnfelipe** [comment]
what service has a free tier?

**Comment by Uberi** [comment]
Please read the documentation for this library first. All of the ones I linked to above have indefinite free accounts.

**Comment by johnfelipe** [comment]
IBM Speech to Text is not for free i install locally but need user and password like account say u before

**Comment by jhoelzl** [comment]
@johnfelipe have a look at https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/speech-to-text.html#pricing-block. Although, after 30 days your IBM trial expires, you can add a credit card to your account and continue using the service for free when you only use less than 1000 minutes per month.

**Comment by Uberi** [comment]
@johnfelipe, I'm not sure how you're using this Python library from Node.js. Can you give some more details?

It sounds like you've got a BlueMix Local setup. This library doesn't support that, since we wouldn't have any way of testing it without actually having one. I recommend you use the usual IBM SDKs for that.
