### ISSUE TITLE
Where is the third-party directory on windows

### ISSUE THREAD

**Issue by leglars** [Uberi/speech_recognition#121]
Hi Uberi,
First, thanks for your fabulous work.
I am working on a project which needs to recognize some simple commands to interact with users. I can't use an online server because of the limitation of deployment place. So I plan to use the Sphinx. In your instruction, you mentioned that you have put a wheel package of PocketSphinx-python in a "third-party" directory. Sorry, I can't find a wheel file and also this third-party directory. But I do find under site-packages\speech-recognition\ has a pocket-sphinx-data folder.

Could you tell me how to do for this, or I needs build from source by myself

**Comment by Uberi** [comment]
Hi @leglars,

The third-party directory is [here](https://github.com/Uberi/speech_recognition/tree/master/third-party). It's not distributed with the actual Python package.

I've added a note to the README about this in 78b6231bd8e1cd642fc4439253179e182e8a5c20.
