### ISSUE TITLE
Support for pulseaudio

### ISSUE THREAD

**Issue by jhoelzl** [Uberi/speech_recognition#127]
Hello,

unfortunately i am not able to select a pulseaudio sound input device as microphone input for pyAudio. Do you know a workaround or are there any plans to support pulseaudio in future releases?

Regards,
Josef

**Comment by Uberi** [comment]
Hi @jhoelzl,

Since PyAudio uses Portaudio, there's no simple way to get it to use Pulseaudio stuff. One way to use those devices is to use a Python Pulseaudio binding to obtain raw samples, then pass that to this library.
