### ISSUE TITLE
recognizer.listen() will not stop unless I manually disable my microphone

### ISSUE THREAD

**Issue by geecko86** [Uberi/speech_recognition#13]
Hi again,

Thank you for fixing the division by zero error. Now I have another issue.
It occurs when using this sample code:

```
                                               # NOTE: this requires PyAudio because it uses the Microphone class
import speech_recognition as sr
r = sr.Recognizer()
with sr.Microphone() as source:                # use the default microphone as the audio source
    audio = r.listen(source)                   # listen for the first phrase and extract it into audio data

try:
    print("You said " + r.recognize(audio))    # recognize speech using Google Speech Recognition
except LookupError:                            # speech is unintelligible
    print("Could not understand audio")
```

As you know when listen() is called, it starts waiting for me to speak. After I'm done talking, even though the room is almost completely silent, it simply doesn't move on. At that point the only thing I can do to force it to continue is to manually disable my microphone in my control panel. Then it goes to the try/except part of the code.

I've tried tweaking silent_treshold and energy_treshold but I can't get it to work.

Again, I'm not sure what information I should provide. Feel free to ask whatever's necessary. I'm running Archlinux with Gnome, PyAudio is installed.

**Comment by anandnwarrier** [comment]
Hi, 
  I am making an app (in dash) wherein I want to create a button to make the mic stop listening. Is there some function in speech_recognition which can disable the mic so that it stops listening?

**Comment by Marvin19594** [comment]
I have the same problem. I dont know how you solved it and have a few questions:
1.) What is __init__.py?
2.) Why does it only work with print(…)?
3.) How did you solve it at the end?

Thank you in advace :)
