### ISSUE TITLE
Bad gateway errors using Google Speech Recognition service

### ISSUE THREAD

**Issue by mtraton** [Uberi/speech_recognition#132]
Steps to reproduce
------------------

1. Trying to transcribe polish voice files basing on code from examples. I have tried with default and my generated API key.
2. `#!/usr/bin/env python3

import speech_recognition as sr

from os import path

AUDIO_FILE = path.join(path.dirname(path.realpath(__file__)), "test.flac")

r = sr.Recognizer()
with sr.AudioFile(AUDIO_FILE) as source:
    audio = r.record(source) # read the entire audio file

GOOGLE_KEY = "mykey"
lang = "pl"

try:
    print("Google Speech Recognition thinks you said " + r.recognize_google(audio, key = GOOGLE_KEY, language=lang))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))
`
I use this file as test file - [test.zip](https://github.com/Uberi/speech_recognition/files/335129/test.zip)

Expected behaviour
------------------

Recognized polish text.

Actual behaviour
----------------

Every time i get the same error message: "Could not request results from Google Speech Recognition service; recognition request failed: Bad Gateway"

System information
------------------

My **Python version** is Python 2.7.11

My **SpeechRecognition library version** is 3.4.6

I don't have PyAudio installed. 

I don't havePocketSphinx  installed.

**Comment by Uberi** [comment]
Oops, must've missed this issue. I can't seem to reproduce this; I am able to get results just fine using the following code:

```python
#!/usr/bin/env python3
import speech_recognition as sr
from os import path
AUDIO_FILE = path.join(path.dirname(path.realpath(__file__)), "test.flac")
r = sr.Recognizer()
with sr.AudioFile(AUDIO_FILE) as source:
    audio = r.record(source) # read the entire audio file
print(r.recognize_google(audio, language="pl"))
```

I'm going to close this issue now, but feel free to re-open if the problem persists!

**Comment by sravanth** [comment]
Hi Uberi,
Sorry for reopening this..I am facing the same issues as the original OP posted here..
_Could not request results from Google Speech Recognition service; recognition request failed: Bad Gateway_

Any thoughts on why this is happening?

**Comment by Uberi** [comment]
Hi @sravanth,

What is your internet connection setup like? Can you access `google.com` using the Python `urlopen` function?

**Comment by sravanth** [comment]
Hi @Uberi ,

Thanks for the reply. Yes, I am able to access the urls. Just as a note I was able to use the Watson API as you laid out in your original code, its just the google speech API that I am not able to, when I try adding an API key with the key parameter it gives me
_Could not request results from Google Speech Recognition service; recognition request failed: Forbidden_

**Comment by asachanfbd** [comment]
Any update on this? I am having same problem.

**Comment by KaylCoulston** [comment]
I am having the same problem as well. Will keep everyone updated on if I find the solution or not.

**Comment by vipinagrahari** [comment]
Even I am facing this same issue. What is the possible reason?

**Comment by AbenaSerwaaSebe** [comment]
i having the same results. Any solution?

**Comment by Uberi** [comment]
Hi @sravanth, @asachanfbd, @KaylCoulston, @vipinagrahari, @AbenaSerwaaSebe,

This particular issue is not reproducible with the latest version, using the code in my previous comment above. If you have a different case that causes the same error, please feel free to open a new issue and post your code!

**Comment by lordlabakdas** [comment]
I get the same error and given below is the code I am working with

```
[# NOTE: this example requires PyAudio because it uses the Microphone class

import speech_recognition as sr
import ConfigParser

cf = ConfigParser.ConfigParser()
cf.read('config.py')
api_key=cf.get('speech', 'API_KEY')
print api_key
# obtain audio from the microphone
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

# recognize speech using Google Speech Recognition
try:
    # for testing purposes, we're just using the default API key
    # to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
    # instead of `r.recognize_google(audio)`
    print("Google Speech Recognition thinks you said " + r.recognize_google(audio, key=api_key))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))](url)
```

And the error I get is `Could not request results from Google Speech Recognition service; recognition connection failed: [Errno 32] Broken pipe`

**Comment by lordlabakdas** [comment]
Figured it out: was using API Key instead of Service account key in Google Cloud SPeech API.
Sorry for the false alarm

**Comment by Charan-Karthikeyan** [comment]
getting the same error can you share what you did to get rid of it??

**Comment by adrianmrit** [comment]
I jus got the Service account key, but how to use it? is a pretty long text

**Comment by Uberi** [comment]
Hi @adrianmrit, @Charan-Karthikeyan,

This is an issue for a different error - I'd recommend opening a new one with the relevant details, so we can help you debug.

@adrianmrit, where did you get the service account key from?

**Comment by hblanken** [comment]
I have the same issues. When I run the code without a key all works fine. -Then I added billing to my Google Console, set up Google Speech Cloud API, created an API key, an App Engine account key and a Service account key. I tried all the ID and private keys. Such as: (audio, key="xxxxXHGKRHF49kghf985xxxxxx") I always get "Could not request results from Google Speech Recognition service; recognition request failed: Forbidden" 
Any suggestions on how to fix this?

**Comment by Uberi** [comment]
Hi @hblanken,

I think you're looking for `recognize_google_cloud` rather than `recognize_google`. Google actually has two different offerings for this: Google Speech API and Google Cloud Speech API.

Here's the documentation: https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instancerecognize_google_cloudaudio_data-credentials_json--none-language--en-us-preferred_phrases--none-show_all--false

**Comment by shreshthagarg21** [comment]
Hi,
while using google speech recognition api and passing it a voice sample file it creates an error like:
Could not request results from Google Speech Recognition service; recognition connection failed: [Errno 32] Broken pipe
Please suggest what could be done to resolve the issue. 
Thanks

**Comment by lew-tolstoi** [comment]
Also same issue,  
Installed on cetos7, SpeechRecognition (3.6.5),  
tried with key (test account for  Google Cloud Speech API) and without,   both does not work. Also with  language="de_DE" variable  ( r.recognize_google(audio, language="de_DE") )  also without success.


Please resolv this issue.

**Comment by vr00n** [comment]
Hey @Uberi - I think it has to do with the length of the audio input. I found that audio files above a minute tend to produce this error whereas audio files <30 seconds work pretty good. 

@mtraton @sravanth @asachanfbd @vipinagrahari have you tried trimming your input audio?

**Comment by zsiegel92** [comment]
I have the same problem, getting "`[Errno 32] Broken Pipe`" when the audio input is longer than 25 seconds.

**Comment by NenadPantelic** [comment]
Probably, you're getting that no because library is making problem, but web service itself, check this:
https://cloud.google.com/speech/quotas.

**Comment by guptadikshant** [comment]
getting unknown value error after compiling the code

**Comment by TuanTool** [comment]
I only get text from video mp4 with 20 seconds in video.
