### ISSUE TITLE
[Feature] Make sphinx model configurable

### ISSUE THREAD

**Issue by tlindener** [Uberi/speech_recognition#138]
Hi,

I'm using the latest version of this fantastic module. Thanks a lot for your work!

It would be great if one could configure the model and e.g. the keyword spotting mode of the sphinx recognizer.

**Comment by Uberi** [comment]
Hi @tlindener,

Glad you found it useful! Keyword support is planned for a future release, but we probably won't be adding arbitrary Sphinx configuration in order to keep things simple.

**Comment by Uberi** [comment]
Keyword support has been officially added as of 3.6.0!
