### ISSUE TITLE
[Errno -9998] Invalid number of channels

### ISSUE THREAD

**Issue by TheCamoc** [Uberi/speech_recognition#139]
I did a little test programm to test if the speech recognition works but when i run it i get this error:
`ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1438
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2742
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    with sr.Microphone(device_index = 1, sample_rate = 44100, chunk_size = 1024) as source:
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 116, in __enter__
    input = True, # stream is an input stream
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9998] Invalid number of channels
`

My programm im using is:
`#!/usr/bin/env python2

import speech_recognition as sr

r = sr.Recognizer()
with sr.Microphone(device_index = 1, sample_rate = 44100, chunk_size = 1024) as source:
    print("Say something!")
    audio = r.listen(source)

try:
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
except sr.UnknownValueError:
    print("Sphinx could not understand audio")
except sr.RequestError as e:
    print("Sphinx error; {0}".format(e))`
## System information

Im using a Raspberry Pi 2 and a cheap USB Soundcard.
Im also using Python 2.7.3, Speech Recognition 3.4.6, PyAudio 0.2.9, PocketSphinx 0.1.0

**Comment by TheCamoc** [comment]
Fixed it by changing the Number of channels in /usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py.
Now it prints Say Something but when i say something it doesnt do anything and theres no Error.

**Comment by Uberi** [comment]
That's very strange. For debugging purposes, do you mind posting the result of running the following code?

```python
python -c "import pyaudio;audio=pyaudio.PyAudio();print([audio.get_device_info_by_index(i) for i in range(audio.get_device_count())])"
```

**Comment by TheCamoc** [comment]
This is the Output:

Expression 'GetExactSampleRate( hwParams, &defaultSr )' failed in 'src/hostapi/a                                                                                                   lsa/pa_linux_alsa.c', line: 877
ALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usable
ALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usable
ALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usable
[{'defaultSampleRate': 44100.0, 'defaultLowOutputLatency': 0.011609977324263039,                                                                                                    'defaultLowInputLatency': -1.0, 'maxInputChannels': 0L, 'structVersion': 2L, 'h                                                                                                   ostApi': 0L, 'index': 0, 'defaultHighOutputLatency': 0.046439909297052155, 'maxO                                                                                                   utputChannels': 2L, 'name': u'bcm2835 ALSA: bcm2835 ALSA (hw:0,0)', 'defaultHigh                                                                                                   InputLatency': -1.0}, {'defaultSampleRate': 44100.0, 'defaultLowOutputLatency':                                                                                                    0.011609977324263039, 'defaultLowInputLatency': -1.0, 'maxInputChannels': 0L, 's                                                                                                   tructVersion': 2L, 'hostApi': 0L, 'index': 1, 'defaultHighOutputLatency': 0.0464                                                                                                   39909297052155, 'maxOutputChannels': 2L, 'name': u'bcm2835 ALSA: bcm2835 IEC958/                                                                                                   HDMI (hw:0,1)', 'defaultHighInputLatency': -1.0}, {'defaultSampleRate': 44100.0,                                                                                                    'defaultLowOutputLatency': 0.011609977324263039, 'defaultLowInputLatency': 0.01                                                                                                   1609977324263039, 'maxInputChannels': 1L, 'structVersion': 2L, 'hostApi': 0L, 'i                                                                                                   ndex': 2, 'defaultHighOutputLatency': 0.046439909297052155, 'maxOutputChannels':                                                                                                    2L, 'name': u'C-Media USB Headphone Set: USB Audio (hw:1,0)', 'defaultHighInput                                                                                                   Latency': 0.046439909297052155}]


Now im not getting errors anymore but when using Sphinx it doesnt Recognize anything it just freezes my Raspberry Pi. When i use Google it works.

**Comment by TheCamoc** [comment]
Ok now im Using this code


#!/usr/bin/env python3

import speech_recognition as sr

def callback(recognizer, audio):
    try:     
        print("Recognizing...")
        print("Sphinx thinks you said " + recognizer.recognize_sphinx(audio))
    except sr.UnknownValueError:
        print("Could not understand audio")
    except sr.RequestError as e:
        print("Could not request results; {0}".format(e))

r = sr.Recognizer()
m = sr.Microphone(sample_rate = 48000, device_index = 2, chunk_size = 7052)
with m as source:
    r.adjust_for_ambient_noise(source) 

stop_listening = r.listen_in_background(m, callback)

import time
for _ in range(50): time.sleep(0.1)
stop_listening() 
while True: time.sleep(0.1)


But when i run it it and i say something it takes half a minute and then outputs, but this only works once when i try to say something again ist doesnt work anymore and also if i restart the script it doesnt either. It only works again after i restart my raspberry. 

Also is there any way i could make the dictionary smaller as i wont use too much different words, and it would run faster then.
And is there someting wrong with my chunk_size or sample_rate cause the recognizes are a bit off but are at least words that sound about the same.

**Comment by Uberi** [comment]
Hi @TheCamoc,

This example code you've posted above only listens for 5 seconds. To make it listen forever, remove the second-last and third-last lines. Please re-open this if that doesn't work!

You can make Sphinx recognition potentially faster by using the new `keywords` argument of `recognize_sphinx`, though you'll want to install the latest development version of this library from the GitHub repository in order to use that.

**Comment by JayjeetAtGithub** [comment]
Hi @TheCamoc Can you please tell to what value did you change `channels` to ?
