### ISSUE TITLE
Additional Parameters for r.recognize_ibm()

### ISSUE THREAD

**Issue by michellemorales** [Uberi/speech_recognition#141]
IBM Watson's Speech to Text Service allows you to opt out of data collection when making requests. I do not want them to collect my data so I am trying to opt-out, which involves setting the parameter X-Watson-Learning-Opt-Out to True. See more details at: http://www.ibm.com/watson/developercloud/speech-to-text/api/v1/#authentication

When I use your  r.recognize_ibm() function, X-Watson_Learning-Opt-Out=True, is not valid. Is there a way for me to pass this argument in?

Thanks!

**Comment by Uberi** [comment]
This will be a part of the next release (ref: ba8becc3f3ffea793eb0bf02d77acb06bbe5c173)

**Comment by Uberi** [comment]
Fixed in 3.5.0!

**Comment by michellemorales** [comment]
Awesome, thanks!
