### ISSUE TITLE
Perform ASR after VAD

### ISSUE THREAD

**Issue by jhoelzl** [Uberi/speech_recognition#147]
Hello,

currently the ASR API service functions are called even when no speech signal is detected from microphone signal. When i use the [microphone example script](https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py) and define 

```
recognizer_instance.energy_threshold = 3500
```
the ASR API is called even when i do not speak any word. The value 3500 is very high compared to the ambient noise label (like 100) so the ASR API should not be called.

It would be nice to first pass the microphone signal to an VAD (Voice Activity Detector) to prevent unnecessary API calls.

Maybe someone knows a good Python VAD that could be used as an extension for this library?

Regards,
Josef

**Comment by jhoelzl** [comment]
I found an issue related to the `recognizer_instance.energy_threshold`.

Please have a look at this small example script:

```
#!/usr/bin/env python3

import speech_recognition as sr

# obtain audio from the microphone
r = sr.Recognizer()
r.energy_threshold = 300
print("Initial Energy Threshold: {}".format(r.energy_threshold))

with sr.Microphone() as source:
    print("Say something!")
    print("Energy Threshold before Listen: {}".format(r.energy_threshold))
    audio = r.listen(source)
    print("Energy Threshold after Listen: {}".format(r.energy_threshold))

# recognize speech using Google Speech Recognition
try:
    # for testing purposes, we're just using the default API key
    # to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
    # instead of `r.recognize_google(audio)`
    print("Google Speech Recognition thinks you said " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))
```

This is the output:

> Say something!
> Initial Energy Threshold: 300
> Energy Threshold before Listen: 300
> Energy Threshold after Listen: 21.948869972
> Google Speech Recognition thinks you said hello

Why is the energy threshold modified when i use `r.listen(source)`?
From my opinion the energy threshold should be fixed at the value 300!

**Comment by Uberi** [comment]
Hi @jhoelzl,

We do use a energy-based VAD. By default, it's configured to automatically adjust to account for background noise. If the dynamic adjustment isn't working well for your application, you can [turn it off and set the threshold yourself](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instancedynamic_energy_threshold--true).

Also, check out the [adjust_for_ambient_noise](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instanceadjust_for_ambient_noisesource-duration--1) function. It will auto-adjust the energy threshold to a reasonable level.

**Comment by jhoelzl** [comment]
Thanks, `recognizer_instance.dynamic_energy_threshold = False` is what i need.
