### ISSUE TITLE
OSError: [Errno 2] No such file or directory with r.recognize_google() and r.recognize_ibm() 

### ISSUE THREAD

**Issue by MarkusMcNugen** [Uberi/speech_recognition#149]
Steps to reproduce
------------------

1) Record audio from file then call r.recognize_google() or r.recognize_ibm() to transcribe the audio file. (All the other recognize functions work and transcribe properly, i.e. Api.ai, Bing, Wit.ai)

2) Relevant code is below:
```
r = sr.Recognizer()
with sr.AudioFile(recording) as source:
     record = r.record(source)
try:
     audio = r.recognize_google(record, key=self.transcribekeys[0])
     transcriber = 'Google Speech to Text'
     return audio, transcriber

except sr.UnknownValueError:
     log.error('\t\t[{0}] Audio could not be understood by Google'.format(upid))
     return None, None

except sr.RequestError:
     log.error('\t\t[{0}] Could not request results from Google'.format(upid))
     return None, None

except Exception as e:
      trace = traceback.format_exc()
      log.error('\t\t[{0}] Unknown exception occured: {1}\n{2}.'.format(upid, str(e.args), trace))
      return None, None
```

3) The audio files being transcribed are Asterisk recorded wav files. They are 128Kbps, 8,000Khz, 16-bit, Mono.

Expected behaviour
------------------

Speech returned as transcribed text

Actual behaviour
----------------

```
Unknown exception occured: (2, 'No such file or directory')
Traceback (most recent call last):
  File "/var/spool/asterisk/PyMon/PyMon.py", line 667, in transaudiogoog
    audio = r.recognize_google(record, key=self.transcribekeys[0])
  File "/usr/local/lib/python2.7.12/lib/python2.7/site-packages/speech_recognition/__init__.py", line 642, in recognize_google
    convert_width = 2 # audio samples must be 16-bit
  File "/usr/local/lib/python2.7.12/lib/python2.7/site-packages/speech_recognition/__init__.py", line 385, in get_flac_data
    ], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/local/lib/python2.7.12/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

System information
------------------

My **Python version** is 2.7.12.

My **SpeechRecognition library version** is 3.4.6.

**Comment by MarkusMcNugen** [comment]
This started happening after I updated my application to use 3.4.6. Previously I was using 3.1.2 and transcribing using r.recognize_google() worked properly. For shiggles I tried swapping the flac encoder names for linux (flac-linux-x86 > flac-linux-i386) and vice versa. While it did stop the error from happening, it still wasn't transcribing the audio file.

**Comment by Uberi** [comment]
It's interesting that you mention renaming `flac-linux-x86` to `flac-linux-i386` caused the error to go away, since that implies you might have some outdated install files. Do versions 3.3.3 or 3.4.1 work?

How was the library installed (e.g., via pip, via the setup.py, or something else)? Was it upgraded or reinstalled? If not, does unintsalling/reinstalling the library work?

Does it work if you install the system FLAC package?

**Comment by MarkusMcNugen** [comment]
The library was installed using pip to a freshly compiled Python 2.7.12 installation. Although the python version doesnt matter because it was happening on the distro installed version, 2.7.3. I haven't tried with the older library versions, but I did install the system flag package and it worked. Google transcriptions instantly started working.

I don't know if it makes a difference but this program is running on Ubuntu 12.04 LTS.

**Comment by Uberi** [comment]
Since I haven't seen any other cases of this, and it's working in this case, I'll close this now. Feel free to open if it pops up again!

**Comment by Avagenzo** [comment]
I got the same error message as mentioned above. Solved it by installing flac:
sudo apt-get install flac

**Comment by jacksun101** [comment]
I am having an issue very similar, so let me try ask question here.

I got libflac installed on my OpenWRT Respeaker board.

> root@ReSpeaker:~# opkg install libflac
Package libflac (1.3.1-1) installed in root is up to date.

I got the error.

> root@ReSpeaker:~# python -m speech_recognition
A moment of silence, please...
Set minimum energy threshold to 70.2429621167
Say something!
Got it! Now to recognize it...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/speech_recognition/__main__.py", line 16, in <module>
    value = r.recognize_google(audio)
  File "/usr/lib/python2.7/site-packages/speech_recognition/__init__.py", line 660, in recognize_google
    convert_width = 2 # audio samples must be 16-bit
  File "/usr/lib/python2.7/site-packages/speech_recognition/__init__.py", line 386, in get_flac_data
    ], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Uberi** [comment]
Hi @jacksun101,

You seem to be using an outdated version of the package. Please update to the latest version, 3.6.3.

Also, I believe libflac doesn't contain the `flac` binary. Make sure you have this by running `flac --help`. You might need to install the relevant package.

Finally, this is a closed issue. If you have an issue that is not the same as the original submitter's issue, please open a new one.
