### ISSUE TITLE
Recognizer is not working

### ISSUE THREAD

**Issue by aquibjaved** [Uberi/speech_recognition#150]
My Python version is 2.7.10 and speech_recognition module 3.4.6 
here's the simple code, It's not giving me any audio in text as output, it waits for long time until I manually closed  the program. 

`import speech_recognition as sr
import subprocess,sys

r = sr.Recognizer()
with sr.Microphone() as source:
	r.adjust_for_ambient_noise(source) 
	audio = r.listen(source)
try:
	speech = (r.recognize_google(audio))
	print speech
except sr.UnknownValueError:
	print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
	print("Could not request results from Google Speech Recognition service; {0}".format(e))
	 `

**Comment by Uberi** [comment]
This is lacking a lot of information - would you mind filling out the issue template? Feel free to re-open afterward.

Also try the audio file transcription examples, and the other recognizers.
