### ISSUE TITLE
set a limit to the amount of time Recognizer.listen() will listen for.

### ISSUE THREAD

**Issue by thundergolfer** [Uberi/speech_recognition#151]
I see that there is a `timeout=` option in `Recognizer.listen()` but this timeout functions when there is a **lack of audio**. Does this library have a way for .listen() to cut-off when the sound level never falls below the needed level? 

In the event that a microphone is playing up `Recognizer,listen()` can lock the script. 
## System information

Windows 10 on Lenovo Thinkpad E550

My **Python version** is 2.7. (You can check this by running `python -V`.)

My **SpeechRecognition library version** is <<current>>. (You can check this by running `python -c "import speech_recognition as sr;print(sr.__version__)"`.)

My **PyAudio library version** is <<current>> / I don't have PyAudio installed. (You can check this by running `python -c "import pyaudio as p;print(p.__version__)"`.))

**Comment by Uberi** [comment]
Fixed in 3.5.0!

**Comment by BigPapaZ** [comment]
@Uberi 
I need some help. 
I want my recognizer.listen() to only work for 3ish seconds and then stop. How do I that? Could you provide me with an example or a link to some documentation?

**Comment by baongocst96** [comment]
> @Uberi
> I need some help.
> I want my recognizer.listen() to only work for 3ish seconds and then stop. How do I that? Could you provide me with an example or a link to some documentation?

recognizer.listen(source, timeout=3)

**Comment by Parth-Shah-Tool-Kit** [comment]
you can try type :
recognizer.listen(source, timeout=3)

Hey, I tried this but it is not stopping after 3 sec...Pl help

**Comment by shiv19july** [comment]
> lp

not working in 3.8.5

**Comment by shiv19july** [comment]
You can type :
audio = r.listen(source, phrase_time_limit=5)

this will surely work in python 3.8.5
I have tested this

**Comment by firstmoon1** [comment]
voice = listener.listen(source,timeout=3, phrase_time_limit=3)

**Comment by firefly19** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
