### ISSUE TITLE
Sometimes urlopen function stucks

### ISSUE THREAD

**Issue by jhoelzl** [Uberi/speech_recognition#152]
Sometimes when i do an ASR request in Python 2.7.6 with Google ASR, the `urlopen` function get stucked [see this line](https://github.com/Uberi/speech_recognition/blob/master/speech_recognition/__init__.py#L672).

So when i wait more than several minutes i get the error:

> recognition request failed: Bad Gateway

I added the argument timeout=10 to the `urlopen` function which fixed the issue for me.
Maybe you can add such an timeout parameter to the library.

**Comment by Uberi** [comment]
Hi @jhoelzl,

That is a good suggestion - we'll put it in for the next release.

**Comment by Uberi** [comment]
Fixed in 3.5.0!
