### ISSUE TITLE
Partial request from Microsoft Bing and Houndify

### ISSUE THREAD

**Issue by bugagashen6ka** [Uberi/speech_recognition#156]
I tried to run IBM Watzon speech recognizer and it works fine - as a request I am getting full converted from audio file to text information. But when I am running unchanged code example for the Microsoft Bing and Houndify, on the same wav file(5 mins long) I receive recognized text probably only for first 60 seconds. I didnt specify any custom options, just changed appropriate tokens/keys for each of the service.

**Comment by Uberi** [comment]
Hi @bugagashen6ka,

The Bing Speech API has [a built-in length limit](https://www.microsoft.com/cognitive-services/en-us/speech-api/documentation/API-Reference-REST/BingVoiceRecognition#user-content-access-the-speech-service-endpoint).

The Houndify API [consumes credits as you use it](https://www.houndify.com/docs#credits). It is possible that you do not have enough credits for this transcription on your Houndify plan.

I recommend using the IBM or Sphinx recognizers instead.
