### ISSUE TITLE
[Errno -2] Name or service not known. Disconnects from Network

### ISSUE THREAD

**Issue by theinem** [Uberi/speech_recognition#161]
The library presents an error when I execute this function:
```
def listen():
	with speech_recognition.Microphone() as source:
		recognizer.adjust_for_ambient_noise(source)
		audio = recognizer.listen(source)

	try:
          captura = recognizer.recognize_google(audio, language = "es-la")
          #captura = recognizer.recognize_sphinx(audio)
          print "Dijiste", captura
          return captura
		# or: return recognizer.recognize_google(audio)
	except speech_recognition.UnknownValueError:          
		print("Could not understand audio")
	except speech_recognition.RequestError as e:
		print("Recog Error; {0}".format(e))

	return ""
```
The output is slow and shows this errors:

- Recog Error; recognition connection failed: [Errno -2] Name or service not known
- "Could not understand audio"

When this occurs, the WiFi connection is reset.
----------------
I suspect this can be an Internet problem, but the connection is, actually, not so slow. I'm using Python 2.7 with Ubuntu 32 bits. My SpeechRecognition library version is 3.4.6. 
My PyAudio library version is 0.2.29

**Comment by Uberi** [comment]
Hi @theinem,

Are you able to access `http://www.google.com/speech-api/v2/recognize` in your browser?

It looks like this is part of a larger program; can you paste the larger program?

**Comment by theinem** [comment]
I have forgotten return to this question.

The problem was because of the bluetooth module. If I turn on the bluetooth, the pc has problem with the WiFi conection in the library, I don't know why, but if I want to avoid the error, I just must to turn off the bluettoth module.

**Comment by Uberi** [comment]
This seems like an issue with the network configuration rather than the library. I'll close this for now, but feel free to re-open if you determine that this is specific to the library!

**Comment by Ganofins** [comment]
I am facing the same issue

**Comment by Ganofins** [comment]
I am using Manjaro KDE Plasma

**Comment by leematthewshome** [comment]
I am facing the same issue when using the google speech API with python speech recognition module.  http://www.google.com/speech-api/v2/recognize is not a valid URL.
