### ISSUE TITLE
Google Speech API is not recognizing audio file

### ISSUE THREAD

**Issue by pankug** [Uberi/speech_recognition#163]
Hello,

Just started to use  speech_recognition in my project.
The wit.ai API is working good but the Google API is failing for same API.

from os import path
AUDIO_FILE = path.join(path.dirname(path.realpath(__file__)), "whats.wav")

r = sr.Recognizer()
with sr.AudioFile(AUDIO_FILE) as source:
    audio = r.record(source) # read the entire audio file

# recognize speech using Wit.ai
WIT_AI_KEY = ""
try:
    print("Wit.ai thinks you said " + r.recognize_wit(audio, key=WIT_AI_KEY))
except sr.UnknownValueError:
    print("Wit.ai could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Wit.ai service; {0}".format(e))

## Google Speech Reciginition API
try:
   print("Google Speech Recognition thinks you said " + r.recognize_google(audio,  key=""))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))

The same code i am using, The wit.ai is correctly recognizing the audio and showing text but google API is showing No such file or directory.
File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 660, in recognize_google
    convert_width = 2 # audio samples must be 16-bit
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 386, in get_flac_data
    ], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Uberi** [comment]
Hi @pankug,

Please upload the WAV file that is causing the issue, as well as any custom code that is necessary to reproduce it.

Also, it looks like your code didn't install correctly. Try running `pip install --reinstall SpeechRecognition` and see if that fixes the problem.

To check your installation, it would also be helpful to know the output of the following command:

```bash
ls -la /usr/local/lib/python2.7/dist-packages/speech_recognition
```

**Comment by pankug** [comment]
Hi
Thanks for the response. I reinstall the package. It is working now.

**Comment by Uberi** [comment]
Great to hear!

**Comment by anabothula** [comment]
`import speech_recognition as sr

r=sr.Recognizer()
with sr.Microphone() as source:
	print("Say Something!")
	audio=r.listen(source,phrase_time_limit=5)
try:
	print(audio)
	print(r.recognize_google(audio,language='en-US',show_all=True))
except LookupError:
	print("Could not understand audio")	
except sr.UnknownValueError:
	print("Try and Try Until You Die")
except sr.RequestError as e:
	print("Could not request results from Google Speech Recognition service; {0}".format(e))
`
Why this code is not recognizing my speech

**Comment by Uberi** [comment]
Works fine here, @anabothula. If you want help with your setup, please open a new issue and fill in the issue template.
