### ISSUE TITLE
Can't get pocketsphinx to detect mic audio (raspberry pi/wolfson audio card)

### ISSUE THREAD

**Issue by williewh** [Uberi/speech_recognition#164]
Hi, I'd like to get an offline test working using Pocketsphinx.  Running "python -m speech_recognition" works fine but I can't tell if it's using Pocketsphinx.

Other examples:
audio_transcribe.py <-- works
background_listening.py <-- no detection
microphone_recognition.py <-- no detection
write_audio.py <-- no detection

I'm running the following code from a script in my home folder.

```
#!/usr/bin/env python3

import speech_recognition as sr

r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

try:
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
except sr.UnknownValueError:
    print("Sphinx could not understand audio")
except sr.RequestError as e:
    print("Sphinx error; {0}".format(e))
```
## System information

My **Python version** is 2.7.9. Tried 3 also.
My **SpeechRecognition library version** is 3.4.6.
My **PyAudio library version** is 0.2.9
I **installed PocketSphinx from** Debian Repos. I also use Blather and it works fine.

**Comment by Uberi** [comment]
Hi @williewh,

If the script you posted is working, then yes, you are using PocketSphinx.

I highly recommend not using the version from the Debian repositories, as they're too old to support the language data we bundle. Instead, you can install one of our [verified Pocketsphinx versions](https://github.com/Uberi/speech_recognition/blob/master/third-party/pocketsphinx-0.0.9-cp27-none-win_amd64.whl) (instructions available in README), or [build and install it from source](https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst).

**Comment by Uberi** [comment]
Seems like this issue is resolved - please re-open if this is not the case!
