### ISSUE TITLE
Recognition from existing raw audio data

### ISSUE THREAD

**Issue by giffy1** [Uberi/speech_recognition#165]
I have existing audio data (8kHz, 16bit mono PCM) sent to my Python script from an Android application. In Android they are shorts; when I receive them in Python I get integers. The only sample code I've seen for this either loads data from a file or acquires it directly from the microphone. Digging into the code, I was able to create an AudioData object from my data as follows:

audio=sr.AudioData(np.asarray(window), 8000, 2)

But when I run the recognition APIs, all of them are completely wrong. I think I must be doing something incorrectly. If I don't convert window to a numpy array, it fails with this error:

TypeError: ratecv() argument 1 must be string or read-only buffer, not list

And looking at the documentation for ratecv(), it is clear that it expects a byte array, which I am not passing in. I am passing in an integer array. Will this work if I convert the audio data into a byte array and pass that in? How would I go about doing this?

**Comment by giffy1** [comment]
I got it working, I had to convert it using bumpy's np.int16() function.

**Comment by Uberi** [comment]
Nice catch, @giffy1 - this is [now documented](https://github.com/Uberi/speech_recognition/commit/d4e4bcc412b5580d14ea84e6a00c623d22fb9535), and hopefully should be more clear to people in the future!
