### ISSUE TITLE
Release new version with the latest code

### ISSUE THREAD

**Issue by brett--anderson** [Uberi/speech_recognition#166]
Firstly, thanks so much for working on this library, it's simple to use and incredibly useful!

I was trying to set the keyword elements for the CMU Sphinx recognition. I eventually noticed that the code installed with 3.4.6 doesn't take the keyword elements argument, while the most recent code in the master branch here does. I just copied the **init**.py file from this repo over the top of the one in site_packages/speech_recognition and everything worked perfectly.

It would be great if a newer version of the library was released to simplify the installation of this functionality.

**Comment by Uberi** [comment]
Fixed in 3.5.0!
