### ISSUE TITLE
'Hide' Alsalib errors when initializing speech_recognition

### ISSUE THREAD

**Issue by postables** [Uberi/speech_recognition#174]
Hello, currently I initialize speech recognition using the following command:
with sr.Microphone() as source:
    app(source)

Which causes a slew of Alsalib errors to show up. Although these don't effect the execution is there a way to "quiet" or completely ignore these error messages to clean up the output of the code?

**Comment by Uberi** [comment]
Hi @postables,

This [thread on StackOverflow](https://stackoverflow.com/questions/7088672/pyaudio-working-but-spits-out-error-messages-each-time) has a bunch of information about making this work. One answer in particular implements a context manager that suppresses ALSA errors entirely.

However, I don't recommend using these - those messages mean there is something wrong with the ALSA configuration, even if they don't affect this particular functionality. I would recommend fixing those issues instead.
