### ISSUE TITLE
languages Mandarin Chinese Unable to download

### ISSUE THREAD

**Issue by 984958198** [Uberi/speech_recognition#175]
Installing other languages
languages Mandarin Chinese Unable to download (https://db.tt/2YQVXmEk)
I am in China

**Comment by Uberi** [comment]
Hi @984958198,

Dropbox is blocked in China. I'm not sure whether Google Drive is as well, but here is a mirror on Google Drive](https://drive.google.com/drive/folders/0Bw_EqP-hnaFNdDk0NDdPb1lJQlE).

If that doesn't work, use a VPN, or try [building a copy from source](https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst).
