### ISSUE TITLE
EOFError with 3gp

### ISSUE THREAD

**Issue by ndy1g14** [Uberi/speech_recognition#180]
Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)
2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)
3. (If there are any files, like audio recordings, don't forget to include them.)

Expected behaviour
------------------

(What did you expect to happen?)

Actual behaviour
----------------

(What happened instead? How is it different from what you expected?)

```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all the statements that don't apply.)

My **system** is <INSERT SYSTEM HERE>. (For example, "Ubuntu 16.04 LTS x64", "Windows 10 x64", or "macOS Sierra".)

My **Python version** is <INSERT VERSION HERE>. (You can check this by running `python -V`.)

My **SpeechRecognition library version** is <INSERT VERSION HERE>. (You can check this by running `python -c "import speech_recognition as sr;print(sr.__version__)"`.)

My **PyAudio library version** is <INSERT VERSION HERE> / I don't have PyAudio installed. (You can check this by running `python -c "import pyaudio as p;print(p.__version__)"`.)

I **installed PocketSphinx from** <INSERT SOURCE HERE>. (For example, from the Debian repositories, from Homebrew, or from the source code.)

**Comment by ndy1g14** [comment]
I don't know whether this is one of the supported formats but I get this when trying to transcribe a 3gp file produced by Android device. The problem could be also that I am not receiving the file correctly. I don't know.

`Traceback (most recent call last):
  File "server.py", line 57, in <module>
    data = getTextFromAudio()
  File "server.py", line 12, in getTextFromAudio
    with sr.AudioFile(AUDIO_FILE) as source:
  File "D:\third year\robert walters\server\speech_recognition\__init__.py", line 221, in __enter__
    self.audio_reader = aifc.open(aiff_file, "rb")
  File "C:\Program Files\Anaconda2\lib\aifc.py", line 952, in open
    return Aifc_read(f)
  File "C:\Program Files\Anaconda2\lib\aifc.py", line 347, in __init__
    self.initfp(f)
  File "C:\Program Files\Anaconda2\lib\aifc.py", line 298, in initfp
    chunk = Chunk(file)
  File "C:\Program Files\Anaconda2\lib\chunk.py", line 63, in __init__
    raise EOFError
EOFError`

**Comment by Uberi** [comment]
Hi @ndy1g14,

3gp audio is not supported. As the [AudioFile documentation](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#audiofilefilename_or_fileobject) says, only WAV/AIFF/FLAC audio is supported - this is what we can support without adding too many dependencies.

You can convert your 3gp audio to WAV by running `ffmpeg -i input.3gp output.wav`, if you have the [FFmpeg command line tools installed](https://ffmpeg.org/download.html).
