### ISSUE TITLE
Hide ALSA error output

### ISSUE THREAD

**Issue by chrisspen** [Uberi/speech_recognition#182]
Every creation of `Microphone()` or `listen()` seems to generate the output:

    ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
    ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
    ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
    ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
    ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
    ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave

which clutter my output and makes it difficult to read other output. Otherwise, the recognition code works flawlessly. I've tried swapping out `sys.stdout` and `sys.stderr`, but this is still output, implying it's happening from a system call. Is there an easy way to suppress these errors?

**Comment by Uberi** [comment]
Hi @chrisspen,

You can use the technique described in [this StackOverflow answer](http://stackoverflow.com/a/17673011) to do what you want:

```python
with noalsaerr() as n, Microphone() as source:
    ...
```

I wouldn't recommend using this (it would be better to make the ALSA configuration correct instead), but in a pinch, this should work fine.

**Comment by chrisspen** [comment]
I also found removing the `cards.pcm.*` from my `alsa.conf` fixed some of the errors, and then explicitly entering the device_index for my microphone fixed the others. However, it's good to know about that context manager. Thanks.

**Comment by Trickery710** [comment]
import sounddevice

if you have to install it
pip3 install sounddevice

**Comment by OpenAyEye** [comment]
> import sounddevice
> 
> if you have to install it pip3 install sounddevice

this is the answer. I don't know why, but it's the answer.
raspi 4 8gb bookworm raspbian

was getting alsa errors, jack errors, all sorts of errors, 
i added
import sounddevice

all errors gone. if you're struggling on the raspi this is the answer.

**Comment by blokpardi** [comment]
import sounddevice solved it for me as well. Thanks @Trickery710!

**Comment by Speeder9743** [comment]
Wow @Trickery710, how does importing a lib fix all these stupid errors on the raspi?!

**Comment by Speeder9743** [comment]
> > import sounddevice
> > if you have to install it pip3 install sounddevice
> 
> this is the answer. I don't know why, but it's the answer. raspi 4 8gb bookworm raspbian
> 
> was getting alsa errors, jack errors, all sorts of errors, i added import sounddevice
> 
> all errors gone. if you're struggling on the raspi this is the answer.

Using the exact same os and pi board, @OpenAyEye !

**Comment by lstuma** [comment]
> Wow @Trickery710, how does importing a lib fix all these stupid errors on the raspi?!

anybody found an answer, I'd be very interested

**Comment by renatocava** [comment]
I installed and imported the sounddevice library and the same output messages also stopped appearing. Just clarify that it is not an error, just messages that worry.

**Comment by SamuelSGSouza** [comment]
> import sounddevice
> 
> if you have to install it pip3 install sounddevice

That worked for me. It seems that the messages are shown because the PyAudio is trying to initialize the PortAudio, but it isn't working correctly. So, when you include the "import sounddevice", this lib initializes the PortAudio on it's own way, what makes PyAudio get that initialized PortAudio and work fine.

**Comment by Shaurya-Grover** [comment]
> import sounddevice
> 
> if you have to install it pip3 install sounddevice



Worked for me aswell thnkyou so much man, saved me hours of warning suppressions!
