### ISSUE TITLE
open wav file - errors.

### ISSUE THREAD

**Issue by catafest** [Uberi/speech_recognition#183]
Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)
every tme
2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)
Run this code:
`import speech_recognition as sr
r = sr.Recognizer()
with sr.AudioFile("english.wav") as source:
    audio = r.record(source)

try:
    s = r.recognize_google(audio)
    print("Text: "+s)
except Exception as e:
    print("Exception: "+str(e))
` got this error:
`C:\Python27>python.exe speek001.py
Traceback (most recent call last):
  File "speek001.py", line 3, in <module>
    with sr.AudioFile("english.wav") as source:
  File "C:\Python27\lib\site-packages\speech_recognition\__init__.py", line 200,
 in __enter__
    self.audio_reader = aifc.open(aiff_file, "rb")
  File "C:\Python27\lib\aifc.py", line 952, in open
    return Aifc_read(f)
  File "C:\Python27\lib\aifc.py", line 347, in __init__
    self.initfp(f)
  File "C:\Python27\lib\aifc.py", line 298, in initfp
    chunk = Chunk(file)
  File "C:\Python27\lib\chunk.py", line 63, in __init__
    raise EOFError
EOFError`
3. (If there are any files, like audio recordings, don't forget to include them.)

Expected behaviour
------------------
to show the text 
(What did you expect to happen?)

Actual behaviour
----------------

(What happened instead? How is it different from what you expected?)
`C:\Python27>python.exe speek001.py
Traceback (most recent call last):
  File "speek001.py", line 3, in <module>
    with sr.AudioFile("english.wav") as source:
  File "C:\Python27\lib\site-packages\speech_recognition\__init__.py", line 200,
 in __enter__
    self.audio_reader = aifc.open(aiff_file, "rb")
  File "C:\Python27\lib\aifc.py", line 952, in open
    return Aifc_read(f)
  File "C:\Python27\lib\aifc.py", line 347, in __init__
    self.initfp(f)
  File "C:\Python27\lib\aifc.py", line 298, in initfp
    chunk = Chunk(file)
  File "C:\Python27\lib\chunk.py", line 63, in __init__
    raise EOFError
EOFError`
```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all the statements that don't apply.)

My **system** is <Windows 8>. (For example, "Ubuntu 16.04 LTS x64", "Windows 10 x64", or "macOS Sierra".)

My **Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (
Intel)] on win32** is <INSERT VERSION HERE>. (You can check this by running `python -V`.)

My **SpeechRecognition library version** is <INSERT VERSION HERE>. (You can check this by running `python -c "import speech_recognition as sr;print(sr.__version__)"`.)

My **PyAudio library version** is <PyAudio-0.2.9> / I don't have PyAudio installed. (You can check this by running `python -c "import pyaudio as p;print(p.__version__)"`.)

I **installed PocketSphinx from** <None>. (For example, from the Debian repositories, from Homebrew, or from the source code.)

**Comment by Uberi** [comment]
Hi @catafest,

Please upload the `english.wav` file referenced in the issue. Remember that WAV files must be in PCM WAV format.

**Comment by srknkrn** [comment]
You can convert the wav file to flac using the ffmpeg command line tools
`ffmpeg -i ses.xxx-c: a flac sound.flac`
I recommend that install ffmpeg from GitHub source, some libraries may be missing at other sources (libebur128 etc.)

**Comment by Uberi** [comment]
This should no longer occur as of version 3.6.0.

**Comment by alikhan2596** [comment]
I got these errors... will you please help me?

line 75, in <module> 
    audio_to_text(str(audio))
line 54, in audio_to_text
    with sr.WavFile(open(audio)) as source:  # use "test.wav" as the audio source
line 203, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
line 499, in open
    return Wave_read(f)
line 163, in __init__
    self.initfp(f)
line 128, in initfp
    self._file = Chunk(file, bigendian = 0)
line 61, in __init__
    self.chunkname = file.read(4)
line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 326: character maps to <undefined>

**Comment by Uberi** [comment]
Hi @alikhan2596,

This is a closed issue - please open a new one and fill in the issue template! It seems like your code is converting the WAV file into a string first, which is incorrect.

**Comment by DHYANI112** [comment]
[speech_to_text(audio(file)).txt](https://github.com/Uberi/speech_recognition/files/2799867/speech_to_text.audio.file.txt)

**Comment by koshyviv** [comment]
Hey @DHYANI112. this i a closed issue, so you can open a new one. Your file seems to suggest that the file is not available in the directory - so please check that.
