### ISSUE TITLE
The code doesn't run- got: missing PocketSphinx modul

### ISSUE THREAD

**Issue by RafahF** [Uberi/speech_recognition#184]
I can't get the result of the code, I got this message: 
Sphinx error; missing PocketSphinx module: ensure that PocketSphinx is set up correctly.
------------------

This is the code I have:

import speech_recognition as sr
from os import path
AUDIO_FILE = path.join(path.dirname(path.realpath("__init__")), "test.wav")
r = sr.Recognizer()
with sr.AudioFile(AUDIO_FILE) as source:
    audio = r.record(source) 
try:
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
except sr.UnknownValueError:
    print("Sphinx could not understand audio")
except sr.RequestError as e:
    print("Sphinx error; {0}".format(e))

I expected to have to spoken words as a text.
------------------
Please note that:
My **system** is <Windows 7 x64>.
My **Python version** is <2.7.12>.
My **SpeechRecognition library version** is <3.5.0>. 
I didn't install PyAudio since I want to use the speech recognition offline and from existing file.
I **installed PocketSphinx from** (pip install pocketsphinx) .. I am not sure though.
------------------
I'm sorry if this is such a stupid question.

**Comment by Uberi** [comment]
Hi @RafahF,

It seems like you don't have PocketSphinx installed properly. To test that it is, run each of the following commands and post the output of all of them here:

```bash
python -V
pip -V
python -c "from pocketsphinx import pocketsphinx; print(pocketsphinx)"
```

For example, when I run it on my machine, I get the following:

```
$ python -V
Python 3.5.2
$ pip -V
pip 9.0.0 from /usr/local/lib/python3.5/dist-packages (python 3.5)
$ python -c "from pocketsphinx import pocketsphinx; print(pocketsphinx)"
<module 'pocketsphinx.pocketsphinx' from '/home/anthony/.local/lib/python3.5/site-packages/pocketsphinx/pocketsphinx.pyc'>
```

**Comment by RafahF** [comment]
@Uberi 
`$ python -V
Python 2.7.12
$ pip -V
pip 9.0.1 from c:\python27\lib\site-packages (python27)
$ python -c "from pocketsphinx import pocketsphinx; print(pocketsphinx)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pocketsphinx\__init__.py", line 35, in <mo
dule>
    from sphinxbase import *
  File "C:\Python27\lib\site-packages\sphinxbase\__init__.py", line 32, in <modu
le>
    from .ad import *
  File "C:\Python27\lib\site-packages\sphinxbase\ad.py", line 35, in <module>
    _ad = swig_import_helper()
  File "C:\Python27\lib\site-packages\sphinxbase\ad.py", line 34, in swig_import
_helper
    return importlib.import_module('_ad')
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _ad
`

Can you help me fixing it please?

**Comment by Uberi** [comment]
Hi @RafahF,

Try installing pocketsphinx 0.0.9 from the provided wheels in the `third-party` directory of this project, using something like `pip install third-party/pocketsphinx-0.0.9-cp35-none-win_amd64.whl`. The version you have installed appears to have some SWIG-related bugs.
