### ISSUE TITLE
Do not recommend to install JACK

### ISSUE THREAD

**Issue by nshmyrev** [Uberi/speech_recognition#187]
The README says:

> On Ubuntu/Debian, I get errors like "jack server is not running or cannot be started" or "Cannot lock down [...] byte memory area (Cannot allocate memory)".
> The Linux audio stack is pretty fickle. There are a few things that can cause these issues.
> First, make sure JACK is installed - to install it, run sudo apt-get install multimedia-jack

this is not a proper recommendation. JACK is not a default server on Ubuntu and the installation might cause a lot of compatibility problems with other software which does not support JACK.

Those messages are purely debug messages, they are not report about problems, pyaudio tries to select different sound subsystems and report their state. 

User should properly configure alsa drivers and pulseaudio to get the sound, not install JACK since it will not solve his problem most likely.

**Comment by Uberi** [comment]
Good call - removed in 081b0fc54f0a8dbed226e828c70c6d201fdb07e1!
