### ISSUE TITLE
Google speech recognition

### ISSUE THREAD

**Issue by jopedroliveira** [Uberi/speech_recognition#188]
Hi there.

I'm working on a speech recognition project, and I'm using this lib. Everything goes well! Congrats for your job.

My point is... I'd like to know which google's API is this lib currently using... At first I was thinking it's using Google Speech API. After some digging I figured out it's a web based API. Plus, It's deprecated.
I've read all reported issues and the lib update for google cloud speech API, but couldn't find documentation about this implementation.
Here goes the question: does the current release of this lib uses Google Cloud Platform API?

**Comment by jhoelzl** [comment]
Hi,

have a look at https://github.com/Uberi/speech_recognition/blob/master/speech_recognition/__init__.py#L745

So, when you use `r.recognize_google()` you are using the depricated web based API. Better use  `r.recognize_google_cloud()` from Google Cloud Platform API to obtain better recognition results.
Apparently this is not documented in the example scripts.

**Comment by jopedroliveira** [comment]
Thanks @jhoelzl 

Both API are still in use indeed.
However, according to my survey, google is trying to force users to migrate for Google Cloud Speech API. Do you, or anybody else, know if Google Speech API (chromium) still is and independent service, or if it's sharing the Google Cloud Speech mechanism? 

(I know It's a bit out of topic discussion, but I may be useful for someone who's about to choose between those APIs)

**Comment by jhoelzl** [comment]
The only thing i noticed that the two services have different performance. I did a test of speech samples from a database and it comes out that the ASR performance is improved (word error rate) in Google Cloud Speech API.

For a new project, i can recommend to use the Cloud Speech API version, because you will never know when Google turns off the free Google Speech API.

**Comment by jopedroliveira** [comment]
Thank you very much @jhoelzl for your time.

In fact, after some reading, I concluded that Google Cloud Platform API may be a better solution for speech recognition, even while Google Speech Recognition API is still running... 
Google Cloud Platform presents a lot of functionalities that can improve apps, such as audio streaming...

Thanks for your time!
