### ISSUE TITLE
Error no acoustic model definition 'mdef' on raspberry pi 3

### ISSUE THREAD

**Issue by jeremiahtenbrink** [Uberi/speech_recognition#189]
Steps to reproduce
------------------
I've been trying to start a connection with pocketsphinx on the raspberry pi three with the new Rasbian jessie installed. I have installed sphinx base and pocketsphinx using this install script located here.
https://github.com/jeremiahtenbrink/Samantha

I'm currently trying to run the python code found as an example

```python
#!/usr/bin/env python
from os import environ, path

from pocketsphinx.pocketsphinx import *
from sphinxbase.sphinxbase import *

MODELDIR = "~/Samantha/pocketsphinx/model"
DATADIR = "~/Samantha/pocketsphinx/test/data"

# Create a decoder with certain model
config = Decoder.default_config()
config.set_string('-hmm', path.join(MODELDIR, 'en-us/en-us'))
config.set_string('-lm', path.join(MODELDIR, 'en-us/en-us.lm.bin'))
config.set_string('-dict', path.join(MODELDIR, 'en-us/cmudict-en-us.dict'))
decoder = Decoder(config)

# Decode streaming data.
decoder = Decoder(config)
decoder.start_utt()
stream = open(path.join(DATADIR, 'goforward.raw'), 'rb')
while True:
  buf = stream.read(1024)
  if buf:
    decoder.process_raw(buf, False, False)
  else:
    break
decoder.end_utt()
print ('Best hypothesis segments: ', [seg.word for seg in decoder.seg()])
```

I keep getting an error stating 

```
INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='live', VARNORM='no', AGC='none'
ERROR: "acmod.c", line 83: Folder '~/Samantha/pocketsphinx/model/en-us/en-us' does not contain acoustic model definition 'mdef'
Traceback (most recent call last):
  File "STT.py", line 15, in <module>
    decoder = Decoder(config)
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 228, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1
```

I've checked the folder en-us and the mdef file is located right there. 

```
pi@raspberrypi:~/Samantha/pocketsphinx/model/en-us/en-us $ dir
feat.params  means      README   transition_matrices
mdef         noisedict  sendump  variances
```

So I'm not sure what it is I'm doing wrong. I can record just find using the arecord command.

**Comment by Uberi** [comment]
Hi @jeremiahtenbrink,

This repository is for the `speech_recognition` project - you might be looking for the [pocketsphinx-python repository](https://github.com/cmusphinx/pocketsphinx-python) instead.

However, I took a look at your code, and the issue is that your paths use `~` rather than being absolute paths. I recreated your directory structure and managed to get it working by changing the following lines:

```python
MODELDIR = "~/Samantha/pocketsphinx/model"
DATADIR = "~/Samantha/pocketsphinx/test/data"
```

To this:

```python
MODELDIR = "/home/anthony/Samantha/pocketsphinx/model"
DATADIR = "/home/anthony/Samantha/pocketsphinx/test/data"
```

Evidently, the library doesn't support home directory lookups.

Since you're already here, I also feel obliged to mention that SpeechRecognition will handle these little details for you automatically :)
