### ISSUE TITLE
PyPI release with recognize_google_cloud support?

### ISSUE THREAD

**Issue by tyarkoni** [Uberi/speech_recognition#190]
The current PyPI release doesn't appear to include the Google Cloud Speech API support that was added recently. Any chance you could push a new release for this in the near future? The old API is deprecated as far as I can tell, and the new one offers better performance anyway. I'm using the speech_recognition package (which is fantastic!) in another package, so I'd prefer to pin the version number in requirements.txt and not have to worry about installing a particular branch from GitHub. Thanks!

**Comment by Uberi** [comment]
Hi @tyarkoni,

Version 3.6.0 has just been released!
