### ISSUE TITLE
How to install a new language for CMUSphinx?

### ISSUE THREAD

**Issue by AllARTSoftworks** [Uberi/speech_recognition#192]
I'm trying to install italian support for CMUSphinx with no luck. 

I've found models here:

https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Italian/

And I think they must be placed here:

/usr/local/lib/python2.7/dist-packages/speech_recognition/pocketsphinx-data/it-IT

But actual en-US folder content is different from archives content linked above.

Can you help me? 

Thank you in advance. 

Yuri

System information
------------------

My **system** is Lubuntu 15.04 "Vivid" 

My **Python version** is 2.7.9 

My **Pip version** is pip 9.0.1 

My **SpeechRecognition library version** is 3.3.1 

My **PyAudio library version** is 0.2.9

I **installed PocketSphinx from** (cannot remember, done it a long time ago, probably repos)

**Comment by jhoelzl** [comment]
Hi,

you have to rename and restructure the files in the italian zip folder:

`etc/voxforge_it_sphinx.lm` > `speech_recognition/pocketsphinx-data/it-IT/language-model.lm.bin`
`etc/voxforge_it_sphinx.dic` > `speech_recognition/pocketsphinx-data/it-IT/pronounciation-dictionary.dict`
`model_parameters/voxforge_it_sphinx.cd_cont_2000/` > `speech_recognition/pocketsphinx-data/it-IT/acoustic-model/`

**Comment by Uberi** [comment]
To add on to what @jhoelzl said, you might want to check out the [language data documentation](https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst#notes-on-the-structure-of-the-language-data)!

Also, here are exact instructions for building the Italian model:

* Italian: ``/speech_recognition/pocketsphinx-data/it-IT/``:
    * ``/speech_recognition/pocketsphinx-data/it-IT/language-model.lm.bin`` is generated as follows:
        1. Download ``cmusphinx-it-5.2.tar.gz`` from the `Sphinx Italian language model <https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Italian/>`__.
        2. Extract ``/etc/voxforge_it_sphinx.lm`` from ``cmusphinx-it-5.2.tar.gz`` as ``italian.lm``.
        4. Convert from ARPA format to Sphinx binary format: ``sphinx_lm_convert -i italian.lm -o italian.lm.bin``.
        5. Replace ``/speech_recognition/pocketsphinx-data/it-IT/language-model.lm.bin`` with ``italian.lm.bin`` created in the previous step.
    * ``/speech_recognition/pocketsphinx-data/it-IT/pronounciation-dictionary.dict`` is ``/etc/voxforge_it_sphinx.dic`` from ``cmusphinx-it-5.2.tar.gz`` (from the `Sphinx Italian language model <https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Italian/>`__).
    * ``/speech_recognition/pocketsphinx-data/it-IT/acoustic-model/`` contains all of the files in ``/model_parameters`` extracted from ``cmusphinx-it-5.2.tar.gz`` (from the `Sphinx Italian language model <https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Italian/>`__).

I have attached the result of following those instructions here:

* [it-IT.zip](https://github.com/Uberi/speech_recognition/files/683258/it-IT.zip)

**Comment by AllARTSoftworks** [comment]
You guys are great. Thank you so much. I'll try and test your hints.

**Comment by AllARTSoftworks** [comment]
Sadly I have a problem: 

ERROR: "ngram_model_arpa.c", line 351: Trigrams not in bigram order
ERROR: "ngram_model_dmp.c", line 121: Wrong magic header size number a5c6461: italian.lm is not a dump file
FATAL_ERROR: "sphinx_lm_convert.c", line 170: Failed to read the model from the file 'italian.lm

Here's the complete log:

$ sphinx_lm_convert -i italian.lm -o italian.lm.bin
INFO: cmd_ln.c(691): Parsing command line:
sphinx_lm_convert \
	-i italian.lm \
	-o italian.lm.bin 

Current configuration:
[NAME]		[DEFLT]	[VALUE]
-case			
-debug			0
-help		no	no
-i			italian.lm
-ienc			
-ifmt			
-logbase	1.0001	1.000100e+00
-mmap		no	no
-o			italian.lm.bin
-oenc		utf8	utf8
-ofmt			

INFO: ngram_model_arpa.c(477): ngrams 1=3741, 2=11194, 3=13364
INFO: ngram_model_arpa.c(135): Reading unigrams
INFO: ngram_model_arpa.c(516):     3741 = #unigrams created
INFO: ngram_model_arpa.c(195): Reading bigrams
INFO: ngram_model_arpa.c(533):    11194 = #bigrams created
INFO: ngram_model_arpa.c(534):      429 = #prob2 entries
INFO: ngram_model_arpa.c(542):     2362 = #bo_wt2 entries
INFO: ngram_model_arpa.c(292): Reading trigrams
ERROR: "ngram_model_arpa.c", line 351: Trigrams not in bigram order
ERROR: "ngram_model_dmp.c", line 121: Wrong magic header size number a5c6461: italian.lm is not a dump file
FATAL_ERROR: "sphinx_lm_convert.c", line 170: Failed to read the model from the file 'italian.lm

**Comment by Uberi** [comment]
Oh, I just realized you mentioned installing Pocketsphinx from the repos - that won't work, you need a more recent version of Pocketsphinx, preferably 0.0.9, which is what I have installed.

I recommend using one of the Python wheels I [bundle with the project](https://github.com/Uberi/speech_recognition/tree/master/third-party) - all of these are properly tested.
