### ISSUE TITLE
Trying to transcribe audio file over the internets

### ISSUE THREAD

**Issue by bottomoftheheap9000** [Uberi/speech_recognition#195]
Im trying to transcribe an audio file from a url. If the url was https://wiki.teamfortress.com/w/images/3/34/Demoman_specialcompleted04.wav?t=20100625221817

How would I transcribe it?
url = "https://wiki.teamfortress.com/w/images/3/34/Demoman_specialcompleted04.wav?t=20100625221817"
BING_KEY = "API_KEY"

r = sr.Recognizer()
	with sr.AudioFile(url) as source:
	    audio = r.record(source) # read the entire audio file
user_input = r.recognize_bing(audio, key=BING_KEY)
print(user_input)

I get the error: Given audio file must be a filename string or a file-like object

**Comment by Uberi** [comment]
You'll want to download it first - see the documentation for `urllib.request` [here](https://docs.python.org/3/library/urllib.request.html#module-urllib.request). As the error message says, the input audio file must be a filename string or a file-like object.

**Comment by bottomoftheheap9000** [comment]
Wow thats fucking shit. Thanks anyway

**Comment by bottomoftheheap9000** [comment]
Would it be possible to stream it at all? With a different additional libraries? I've got it working by downloading, just it slows down my script massively. Either way, thank you!!

**Comment by Uberi** [comment]
Hi @bottomoftheheap9000,

Not at this time, unfortunately, but it is planned for the future. For now, I'd recommend using one of the engines that supports FLAC upload, since that should be a lot faster - `recognize_google_cloud` or `recognize_ibm`.

**Comment by bottomoftheheap9000** [comment]
No worries man, the library kicks ass as it is, very nice to use. I'll check out google_cloud now, thanks!!
