### ISSUE TITLE
Speech recognition could not understand audio

### ISSUE THREAD

**Issue by dshivani** [Uberi/speech_recognition#196]
Hi!  every time I say something speech recognition can't understand what I said. I even tried r.adjust_for_ambient_noise(source)
Here is the code I'm working with:

```
import speech_recognition as sr
from time import ctime
import time
import os
from gtts import gTTS
 
def recordAudio():
    # Record Audio
    r = sr.Recognizer()    
# obtain audio from the microphone
    
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source)
        print("Say something!")
        audio = r.listen(source)
        
 
    # Speech recognition using Google Speech Recognition
        data = ""
    try:
        # Uses the default API key
        # To use another API key: `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
        data = r.recognize_google(audio)
        print("You said: " + data)
    except sr.UnknownValueError:
        speak("Sorry sir, but, I could not understand what you said!")
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))
 
    return data


```

Please help!

**Comment by foud123** [comment]
Same problem here, i speak in french, the text is in english and it's not even translation).

**Comment by linuxipho** [comment]
Hi, you should add language="fr-FR" attribute in recognize_google() function.

**Comment by foud123** [comment]
Hi, i'm using MS speech and it didn't work.

This is the code 

BING_KEY = "MyKey" # Microsoft Bing Voice Recognition API keys 32-character lowercase hexadecimal strings
language="fr-FR"
try:
    print("Microsoft Bing Voice Recognition thinks you said " + r.recognize_bing(audio, key=BING_KEY))
except sr.UnknownValueError:
    print("Microsoft Bing Voice Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Microsoft Bing Voice Recognition service; {0}".format(e))

**Comment by aniu** [comment]
same error here. Can the host give some advice? thanks a lot!

**Comment by shafaypro** [comment]
I was facing the same error. I got it corrected to manually checking the threshold value, which I added += 280 .
there is a trade-off between the quality of your microphone and the threshold value, lower the microphone (higher the garbage value).
Try configuring the Threshold value as 👍 

`    def speech_to_text(self):
        r = sr.Recognizer()
        with sr.Microphone() as source:
            r.adjust_for_ambient_noise(source, duration=1)
            print(r.energy_threshold)
            print("Chucking rate: ", source.CHUNK)
            print("format rate :", source.format)
            print("Say something!...")
            print(r.energy_threshold)
            r.energy_threshold += 280
            audio = r.listen(source)

            # Speech recognition using Google Speech Recognition
        try:
            print("Parsing ...")  # Debugging To
            # for testing purposes, we're just using the default API key
            text = r.recognize_google(audio, language='en-GB')
            print("You said: " + text)
        except sr.UnknownValueError:
            print("Google Speech Recognition could not understand audio")
        except sr.RequestError as e:
            print("Could not request results from Google Speech Recognition service; {0}".format(e))
        except sr.HTTPError as e:
            print("Couldn't connect to the websites perhaps , Hyper text transfer protocol error",e)
`
First If you are a Pakistani or Indian (change the recognition language to 'en-GB" Accent counts for correct parsing
`
r.recognize_google(audio, language='en-GB')`

**Comment by shafaypro** [comment]
For those who are having Language issues,
There is a language attribute with every recognition assets `as:```



`import speech_recognition as sr

# obtain audio from the microphone
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

# recognize speech using Sphinx
try:
    print("Sphinx thinks you said " + r.recognize_sphinx(audio,language='en-GB'))
except sr.UnknownValueError:
    print("Sphinx could not understand audio")
except sr.RequestError as e:
    print("Sphinx error; {0}".format(e))

# recognize speech using Google Speech Recognition
try:
    # for testing purposes, we're just using the default API key
    # to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
    # instead of `r.recognize_google(audio)`
    print("Google Speech Recognition thinks you said " + r.recognize_google(audio,language='en-GB'))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))

# recognize speech using Google Cloud Speech
GOOGLE_CLOUD_SPEECH_CREDENTIALS = r"""INSERT THE CONTENTS OF THE GOOGLE CLOUD SPEECH JSON CREDENTIALS FILE HERE"""
try:
    print("Google Cloud Speech thinks you said " + r.recognize_google_cloud(audio, credentials_json=GOOGLE_CLOUD_SPEECH_CREDENTIALS, language='en-GB'))
except sr.UnknownValueError:
    print("Google Cloud Speech could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Cloud Speech service; {0}".format(e))

# recognize speech using Wit.ai
WIT_AI_KEY = "INSERT WIT.AI API KEY HERE" # Wit.ai keys are 32-character uppercase alphanumeric strings
try:
    print("Wit.ai thinks you said " + r.recognize_wit(audio, key=WIT_AI_KEY))
except sr.UnknownValueError:
    print("Wit.ai could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Wit.ai service; {0}".format(e))

# recognize speech using Microsoft Bing Voice Recognition
BING_KEY = "INSERT BING API KEY HERE" # Microsoft Bing Voice Recognition API keys 32-character lowercase hexadecimal strings
try:
    print("Microsoft Bing Voice Recognition thinks you said " + r.recognize_bing(audio, key=BING_KEY,language='en-GB'))
except sr.UnknownValueError:
    print("Microsoft Bing Voice Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Microsoft Bing Voice Recognition service; {0}".format(e))

# recognize speech using Houndify
HOUNDIFY_CLIENT_ID = "INSERT HOUNDIFY CLIENT ID HERE" # Houndify client IDs are Base64-encoded strings
HOUNDIFY_CLIENT_KEY = "INSERT HOUNDIFY CLIENT KEY HERE" # Houndify client keys are Base64-encoded strings
try:
    print("Houndify thinks you said " + r.recognize_houndify(audio, client_id=HOUNDIFY_CLIENT_ID, client_key=HOUNDIFY_CLIENT_KEY,language='en-GB'))
except sr.UnknownValueError:
    print("Houndify could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Houndify service; {0}".format(e))

# recognize speech using IBM Speech to Text
IBM_USERNAME = "INSERT IBM SPEECH TO TEXT USERNAME HERE" # IBM Speech to Text usernames are strings of the form XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
IBM_PASSWORD = "INSERT IBM SPEECH TO TEXT PASSWORD HERE" # IBM Speech to Text passwords are mixed-case alphanumeric strings
try:
    print("IBM Speech to Text thinks you said " + r.recognize_ibm(audio, username=IBM_USERNAME, password=IBM_PASSWORD, language='en-GB'))
except sr.UnknownValueError:
    print("IBM Speech to Text could not understand audio")
except sr.RequestError as e:
    print("Could not request results from IBM Speech to Text service; {0}".format(e))`

**Comment by Siddharthpratapsingh** [comment]
I am using pocketsphinx and it doesnt recognise the speech properly.Moreover i searched for 'en-GB' language model but i didnt got anything.

**Comment by Uberi** [comment]
We don't bundle a UK English model with Pocketsphinx, unfortunately. Since @dshivani's original issue should be solved by either adding a language parameter, or upgrading to the latest version of all the libraries, I'll close this now. Please feel free to reopen if there are remaining issues!

**Comment by SudeepDeyondi** [comment]
Hi,
for this I think you should use 
'Sample_rate=48000 
& Chunk_size= 2048

(work as a buffering stores as most as 2048 samples bytes of data).

**Comment by BohdanOpyr** [comment]
I use raspberrypi and it returns this error almous instantly, even without sending audio to google.
I said **audio**, not **data**
I use much more simple code, which does the same
adding `language='en_GB', key="GOOGLE_SPEECH_RECOGNITION_API_KEY"` wasn't helpful
What's wrong?:
```#!/usr/bin/env python3
import speech_recognition as sr
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)
try:
    print("Google Speech Recognition thinks you said " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))```

**Comment by BohdanOpyr** [comment]
Oh, sorry. I found an answer. Just use this:
```python
#!/usr/env/python3
import speech_recognition as sr

r = sr.Recognizer()
m = sr.Microphone()

try:
    print("A moment of silence, please...")
    with m as source: r.adjust_for_ambient_noise(source)
    print("Set minimum energy threshold to {}".format(r.energy_threshold))
    while True:
        print("Say something!")
        with m as source: audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            value = r.recognize_google(audio)

            if str is bytes:
                print(u"You said {}".format(value).encode("utf-8"))
            else:
                print("You said {}".format(value))
        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except sr.RequestError as e:
            print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
except KeyboardInterrupt:
    pass
```
It's actually *__main.py__* from speech_recognition module
For me, it worked really well

**Comment by ahammad52003** [comment]
> Oh, sorry. I found an answer. Just use this:
> 
> ```python
> #!/usr/env/python3
> import speech_recognition as sr
> 
> r = sr.Recognizer()
> m = sr.Microphone()
> 
> try:
>     print("A moment of silence, please...")
>     with m as source: r.adjust_for_ambient_noise(source)
>     print("Set minimum energy threshold to {}".format(r.energy_threshold))
>     while True:
>         print("Say something!")
>         with m as source: audio = r.listen(source)
>         print("Got it! Now to recognize it...")
>         try:
>             value = r.recognize_google(audio)
> 
>             if str is bytes:
>                 print(u"You said {}".format(value).encode("utf-8"))
>             else:
>                 print("You said {}".format(value))
>         except sr.UnknownValueError:
>             print("Oops! Didn't catch that")
>         except sr.RequestError as e:
>             print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
> except KeyboardInterrupt:
>     pass
> ```
> 
> It's actually _**main.py**_ from speech_recognition module
> For me, it worked really well

recognize_google() function didn't work on my PC. could you please help me?
