### ISSUE TITLE
Can't get it work

### ISSUE THREAD

**Issue by youle31** [Uberi/speech_recognition#20]
Hello! I tried speech recognition 1.1.4 with python 3.4.0 64 bits and pyaudio 0.2.8 64 bits for python 3.4 but it does not work on my computer. I'm running on a windows 8.1 64 bits OS. 

With the default test code:

import speech_recognition as sr
r = sr.Recognizer()
with sr.Microphone() as source:                 # use the default microphone as the audio source
    audio = r.listen(source)                           # listen for the first phrase and extract it into audio data

try:
    print("You said " + r.recognize(audio))    # recognize speech using Google Speech Recognition
except LookupError:                                   # speech is unintelligible
    print("Could not understand audio")

nothing happens (Microphone seems not detected)

So I tried to replace:

with sr.Microphone() as source:

by:

with sr.Microphone(2) as source:

and I get this error:

Traceback (most recent call last):
  File "C:/Users/yul/Desktop/test.py", line 3, in <module>
    with sr.Microphone(2) as source:                # use the default microphone as the audio source
  File "C:\Python34\lib\site-packages\speechrecognition-1.1.4-py3.4.egg\speech_recognition\__init__.py", line 47, in __enter__
    input = True, # stream is an input stream
  File "C:\Python34\lib\site-packages\pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Python34\lib\site-packages\pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno Invalid number of channels] -9998

Do I have to configure something in pyaudio to make this work? Thanks very much for your answer!!

**Comment by Uberi** [comment]
Hi @youle31,

Are you able to get any PyAudio examples working? Try posting the output of the following code here:

    import pyaudio
    p = pyaudio.PyAudio()
    for i in range(p.get_device_count())
        print(p.get_device_info_by_index(i))

This should work on Python 2 and 3.

**Comment by youle31** [comment]
Hi! Yes. Here is the output:
http://www.mediafire.com/view/3ft7fm1xb69pnhc/out.txt

(Finally I did my stuff with pyspeech (which uses Microsoft speech recognition) but it will be cool for me to make some tests with google speech :)

Thanks for your help!

**Comment by Uberi** [comment]
Hmm, try one of the following and see if they work:

    with sr.Microphone(1) as source:
    with sr.Microphone(7) as source:
    with sr.Microphone(15) as source:
    with sr.Microphone(18) as source:

By default the library will use index 0, but that seems to be Microsoft Input Mapper for you.

**Comment by youle31** [comment]
Thanks for your answer. I tried all what you suggested without success, but when I take Microphone(7) as source, I get the message "Could not understand audio". Recognition fails whatever I say. 

About the API key, I just use : 
sr.Recognizer(key = "AIzaSyDt1grezgK0lYdBuhCgrez7uu6ebR-ZggqaoSGw")

Is that correct? I do not know what I'm missing. Some screenshots:

http://www.mediafire.com/download/i3rc4a4uvkd132x/screenshots.rar

Good evening!

**Comment by Uberi** [comment]
Have you tried it with the default API key? If you don't specify a key, it will use the default Chrome key. At least we now know that your audio devices are working correctly with PyAudio.

**Comment by youle31** [comment]
Yes. Thanks for your answer. With or without key, when I put the code in a while loop and then make CTRL+c keyboard interrupt, I get this message:

http://www.mediafire.com/view/0seqo6z1s73bxor/withoutKey.jpg

I don't know if this helps...

**Comment by Suddstar** [comment]
r = sr.Recognizer()
r.energy_threshold = 500

Increasing the energy_threshold seemed to resolve this issue for me. It appears that under quiet conditions, my microphone returns an energy level of 300~ forcing the recorder to record indefinitely.

**Comment by youle31** [comment]
Thanks very much! It solved the problem! I had to increased threshold to 4000 make it work but now I can tell myself stories! Great! 

Finally I didn't change anything to the default demo script except threshold.

Thanks very much again for you precious help! SOLVED

**Comment by youle31** [comment]
Thank you both!

**Comment by youle31** [comment]
(I changed the language too r = sr.Recognizer(language = "fr-FR"))

**Comment by Uberi** [comment]
Thanks for the tip @Suddstar! I've added this to the documentation for future reference.

**Comment by dshivani** [comment]
Hi! sorry for reopening this issue but every time I say something it can't understand it. I even tried  r.adjust_for_ambient_noise(source)
Here is the code I'm working with:

`import speech_recognition as sr
from time import ctime
import time
import os
from gtts import gTTS
 
def recordAudio():
    # Record Audio
    r = sr.Recognizer()
    
 # obtain audio from the microphone
    
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source)
        print("Say something!")
        audio = r.listen(source)
        
 
    # Speech recognition using Google Speech Recognition
        data = ""
    try:
        # Uses the default API key
        # To use another API key: `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
        data = r.recognize_google(audio)
        print("You said: " + data)
    except sr.UnknownValueError:
        speak("Sorry sir, but, I could not understand what you said!")
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))
 
    return data`

**Comment by Uberi** [comment]
Hi @dshivani,

Oops, I missed your comment since the issue was closed. I expect that the issue is likely due to microphone issues. Can you try the following code?

```python
import speech_recognition as sr

r = sr.Recognizer()    
with sr.Microphone() as source:
    r.adjust_for_ambient_noise(source)
    print("Say something!")
    audio = r.listen(source)
    print("Done listening!")
with open("microphone-results.wav", "wb") as f:
    f.write(audio.get_wav_data())
```

This will create a WAV file called `microphone-results.wav`, containing the recorded audio, which we can then use to figure out what's going wrong.

**Comment by swapnilkumar25** [comment]
Hello,

i have tried as per the above comments and the last update by you, but still now able to achieve the answer ... please find the below code and error  


import speech_recognition as sr
import pyaudio as p

# obtain audio from the microphone

r = sr.Recognizer()
with sr.Microphone() as source:
    r.adjust_for_ambient_noise(source)
    print("Say something!")
    audio = r.listen(source)
    print("Done listening!")
with open("microphone-results.wav", "wb") as f:
    f.write(audio.get_wav_data())

# recognize speech using Sphinx
try:
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
except sr.UnknownValueError:
    print("Sphinx could not understand audio")
except sr.RequestError as e:
    print("Sphinx error; {0}".format(e))

# recognize speech using Google Speech Recognition
try:
    # for testing purposes, we're just using the default API key
    # to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
    # instead of `r.recognize_google(audio)`
    print("Google Speech Recognition thinks you said " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))
===============================================================================
Error:
==========================================================================
Traceback (most recent call last):
  File "/home/swapnil/PycharmProjects/speech/google_api.py", line 7, in <module>
    with sr.Microphone() as source:
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 113, in get_pyaudio
    raise AttributeError("PyAudio 0.2.11 or later is required (found version {})".format(pyaudio.__version__))
AttributeError: PyAudio 0.2.11 or later is required (found version 0.2.8)

Process finished with exit code 1

**Comment by Uberi** [comment]
Hi @swapnilkumar25,

As the error says, you have PyAudio 0.2.8, but the library requires PyAudio 0.2.11. Please upgrade your PyAudio library.

If issues persist, please open a new issue on the [issue tracker](https://github.com/Uberi/speech_recognition/issues/)!

**Comment by shreysoni12718** [comment]
> import pyaudio
> p = pyaudio.PyAudio()
> for i in range(p.get_device_count())
>     print(p.get_device_info_by_index(i))

invalid syntax error
