### ISSUE TITLE
Azure support for Cognitive  (Speech to Text)

### ISSUE THREAD

**Issue by RustyE** [Uberi/speech_recognition#200]
I am currently using the Project Oxford entry point for Speech to Text.
Azure has informed me that this support will be discontinued in April.
Is there a way to port my existing API keys etc. to Azure?  Also, what changes need to be made in code to access the new API?

**Comment by Uberi** [comment]
Hi @RustyE,

I am confused about this issue, for the following reasons:

* The Project Oxford entry point for API keys stopped working months ago already (assuming you meant `https://oxford-speech.cloudapp.net/token/issueToken`). We now use the official Microsoft Cognitive Services API. Do you happen to have a link with more info?
* What does it mean to port an API key to Azure?

If you meant code changes caused by changes to the Cognitive Services API, I can assure you that we will not be breaking backwards compatibility for documented interfaces :)

**Comment by RustyE** [comment]
Hi Anthony,
Thank you for your kind response to my query.
I've been using the Microsoft Cognitive Services mostly for Speech to Text in my application.  I also do translation from multiple languages and currently use Google Translate, but would like to consolidate to the Microsoft solution.
However, I've been receiving emails from Microsoft titled : "CTF: Migrate your collaborative translations before April 30, 2017 from Azure DataMarket to Azure" and indicating that I MUST migrate to the Asure market.
Maybe I'm confused.  Hopefully by using the Bing Speech API (which is what I am currently using successfully), I won't need to "migrate".
In my web browsing in researching the "migration" requirement, I understood that there would be code/entry point changes and that the Client Key/Client Secrets needed to be and can be "ported" to the Azure solution.
It is fantastic to hear you will not be breaking backwards compatibility as this reason is the main reason I'm choosing Microsoft over the Google speech services.
Regards,
RustyE

**Comment by RustyE** [comment]
Also, I found this on the Microsoft Cognitive Services page (https://www.microsoft.com/cognitive-services/en-US/subscriptions):
"Starting on 1/17, our endpoints will be changing. If your API is currently using "api.projectoxford.ai" endpoint, you will need to switch to the new API endpoint starting on 1/17. If you continue to use the legacy endpoint after 1/17, you may experience latency. To know if you are affected, visit your API homepage and click on the “API Reference” button for more information on your API’s endpoint change. We thank you for your cooperation as we continue to improve our services. The old API endpoints will be deprecated 90 days following this change (on 4/15)."

**Comment by Uberi** [comment]
Hi @RustyE,

I see now. The email you refer to is actually about the Microsoft Translator Text API, at least if it's this email: https://translatorbusiness.uservoice.com/knowledgebase/articles/1119544-ctf-migrate-your-collaborative-translations-from

Additionally, we've migrated away from that endpoint a few releases ago, so I think there shouldn't be anything to worry about here. Thanks for the link and write-up.
