### ISSUE TITLE
how to get number reply from Bing Speech service? 

### ISSUE THREAD

**Issue by ryo96** [Uberi/speech_recognition#204]
I wanted to get the number 10000 when speak "ten thousand" however, Bing speech service replied with the string "ten thousand" instead of "10000"
I found on stackoverflow the you can select field from Bing Speech respond like below.
[{
"lexical": "fifteen dollars and seven cents",
"display": "$15.07.",
"inverseNormalization": null,
"maskedInverseNormalization": null,
"transcript": "$15.07.",
"confidence": 0.9474185
}]
is there away to do this in this speech_recognition api? Or get the respond in form of number like "10000" at least?

Thank you so much,

**Comment by Uberi** [comment]
Hi @ryo96,

Check out the `show_all` parameter of [recognize_bing](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instancerecognize_bingaudio_data-key-language--en-us-show_all--false).

Specifically, you can retrieve the `display` field from that result. Let me know if you'd like an example.

**Comment by ryo96** [comment]
It's perfect. Thank you!
