### ISSUE TITLE
GOOGLE_CLOUD_SPEECH Error when running the example

### ISSUE THREAD

**Issue by ryo96** [Uberi/speech_recognition#205]
I was running the example code 
```python
GOOGLE_CLOUD_SPEECH_CREDENTIALS = r"""INSERT THE CONTENTS OF THE GOOGLE CLOUD SPEECH JSON CREDENTIALS FILE HERE"""
try:
    print("Google Cloud Speech recognition results:")
    pprint(r.recognize_google_cloud(audio, credentials_json=GOOGLE_CLOUD_SPEECH_CREDENTIALS, show_all=True)) # pretty-print the recognition result
except sr.UnknownValueError:
    print("Google Cloud Speech could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Cloud Speech service; {0}".format(e))
```

I inserted the content of google could speech json, and received this  error when run
```
Traceback (most recent call last):
  File "C:\Users\loctruong96\Desktop\voice reg test\Computer reg project\CloudSpeechtest.py", line 25, in <module>
    VoiceToText()
  File "C:\Users\loctruong96\Desktop\voice reg test\Computer reg project\CloudSpeechtest.py", line 19, in VoiceToText
    pprint(r.recognize_google_cloud(audio, credentials_json=GOOGLE_CLOUD_SPEECH_CREDENTIALS, show_all=True)) # pretty-print the recognition result
  File "C:\Users\loctruong96\AppData\Local\Programs\Python\Python35-32\lib\site-packages\speech_recognition\__init__.py", line 786, in recognize_google_cloud
    api_credentials = GoogleCredentials.from_stream(f.name)
  File "C:\Users\loctruong96\AppData\Local\Programs\Python\Python35-32\lib\site-packages\oauth2client\client.py", line 1283, in from_stream
    credential_filename)
  File "C:\Users\loctruong96\AppData\Local\Programs\Python\Python35-32\lib\site-packages\oauth2client\client.py", line 1378, in _get_application_default_credential_from_file
    with open(filename) as file_obj:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\LOCTRU~1\\AppData\\Local\\Temp\\tmp2fvne80a'
```

I tried to input file path of the json file as oppose to string value but still the same deal, can anyone confirm the problem  as  bug ?

NOTE: only happen with recognize_google_cloud, other service like bing and google recognize works fine.

**Comment by Uberi** [comment]
Hi @ryo96,

This is a bug in the library on Windows, and is now fixed in 65b5634f81d56ed13275fab9834e333fece6b896. The issue should be gone in the next release, or you can install the development version to get the fixes right away!

**Comment by mikep2016** [comment]
Has this been released yet? I have the same issue.

**Comment by loctruong96** [comment]
@mikep2016 just download the updated file and place it into the site-package folder, make sure to backup the original one. That's what i did to get it working again! Thanks @Uberi for fixing this issue!

**Comment by projectdrone2** [comment]
Hello all, I'm getting the same error: "PermissionError: [Errno 13] Permission denied:". How can I know if I downloaded the right package (including the https://github.com/Uberi/speech_recognition/commit/65b5634f81d56ed13275fab9834e333fece6b896)?
