### ISSUE TITLE
recognize_google not matching the exact words and translation

### ISSUE THREAD

**Issue by shafaypro** [Uberi/speech_recognition#211]
**PROBLEMS**
google api was tokenizing the speech perfect till the last day, until today it started doing wrong parsing including the Short english words , The **recognize_google(audio) was working** well with 1 error (wrong output) / 100. But since yesterday i am facing **difficulty** in the pronounced words such as ->
**What —> wat
date —> dead
show —> so
stop —- > top
stop listening —> stopped listenning or top listenning
joke —> job**
if you say "what is the date " --> it recognize 'what is the dead", but if you say "what is the dates" --> it recognizes as --> what is the date or what is the dates. Same goes with time.

I have tried playing with the frames as well as the threshold but still its not parsing correctly , while before that it was identifying the accurate spoken words ( i tested them with atleast 10 different people) 
`----------------------------------------------------------------------------------------------------`
The code is : 
```
  def speech_to_text(self):

        r = sr.Recognizer()
        with sr.Microphone() as source:
            CHUNK = 1024
            FORMAT = pyaudio.paInt16  # the Format is picked up from the pyaudio
            CHANNELS = 2  # The Cross Channels
            source.CHUNK = CHUNK
            source.format = FORMAT  # FORMATING THE SOURCE FILE
            print("Say something!")
            print(r.energy_threshold)
            r.energy_threshold -= 80
            # print(r.adjust_for_ambient_noise(source,duration=1))
            audio = r.listen(source)
        try:
            text = r.recognize_google(audio, language='en-US')
            print("You said: " + text)
            return text  # returning the text which has been inputed.
        except sr.UnknownValueError:
            print("Google Speech Recognition could not understand audio")
        except sr.RequestError as e:
            print("Could not request results from Google Speech Recognition service; {0}".format(e))



```

**Comment by shafaypro** [comment]
-- Got it corrected, the threshold was set too low and the language accent was changed to British so that the slang language could be avoided, therefore was missing frames. currently value has been set to r.energy_threshold += 280 (580) and its working.
`r = sr.Recognizer()
        with sr.Microphone() as source:
            r.adjust_for_ambient_noise(source, duration=1)
            # print(r.energy_threshold)
            print("Chucking rate: ", source.CHUNK)
            print("format rate :", source.format)
            # CHUNK = 1024
            # FORMAT = pyaudio.paInt16  # the Format is picked up from the pyaudio
            # CHANNELS = 2  # The Cross Channels
            # # RATE = 44100
            # source.CHUNK = CHUNK
            # source.format = FORMAT  # FORMATING THE SOURCE FILE
            # print(dir(source))
            print("Say something!...")
            # print(r.energy_threshold)
            r.energy_threshold += 280
            # # print(r.adjust_for_ambient_noise(source,duration=1))
            audio = r.listen(source)

            # Speech recognition using Google Speech Recognition
        try:
            print("Parsing ...")  # Debugging To
            # for testing purposes, we're just using the default API key
            # to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
            # instead of `r.recognize_google(audio)`
            # print(r.energy_threshold )
            # print(help(r.recognize_google))
            # text = r.recognize_google(audio, language='en-US')

            text = r.recognize_google(audio, language='en-GB')
            # text = r.recognize_ibm(audio,"mshafayamjad@gmail.com", "shafay12332100s")
            # r.re
            # r.re
            print("You said: " + text)
            self.total_saying = text
            self.process_text_input(self.total_saying)
            return text  # returning the text which has been inputed.
        except sr.UnknownValueError:
            print("Google Speech Recognition could not understand audio")

        except sr.RequestError as e:
            print("Could not request results from Google Speech Recognition service; {0}".format(e))`

**Comment by juanoliveros18** [comment]
Hello shafaypro, how are you?
You know how I can include the Spanish language in this code, for a good translation. Thank you very much.
import os
import speech_recognition as sr
from tqdm import tqdm
import sys, traceback

 
with open("api-key.json") as f:
    GOOGLE_CLOUD_SPEECH_CREDENTIALS = f.read()

r = sr.Recognizer()
files = os.listdir('audios/')

all_text = []

for f in tqdm(files):
    name = "audios/" + f
    # Load audio file

    with sr.AudioFile(name) as source:
        audio = r.record(source)
      
        
    # Transcribe audio file
    #text2 = r.recognize_google_cloud(audio,language='en-GB',credentials_json=GOOGLE_CLOUD_SPEECH_CREDENTIALS)
    text = r.recognize_google_cloud(audio,credentials_json=GOOGLE_CLOUD_SPEECH_CREDENTIALS)
    
    all_text.append(text)
    

transcript = ""

for i, t in enumerate(all_text):
    total_seconds = i * 30
    # Cool shortcut from:
    # https://stackoverflow.com/questions/775049/python-time-seconds-to-hms
    # to get hours, minutes and seconds
    m, s = divmod(total_seconds, 60)
    h, m = divmod(m, 60)
 
    # Format time as h:m:s - 30 seconds of text
    transcript = transcript + "{:0>2d}:{:0>2d}:{:0>2d} {}\n".format(h, m, s, t)
 
print(transcript)
 
with open("transcript.txt", "w") as f:
    f.write(transcript)
