### ISSUE TITLE
SwigPyObject error

### ISSUE THREAD

**Issue by sravanth** [Uberi/speech_recognition#212]
hi, I was trying to use the sphinx recogniser but ending up with 'SwigPyObject' object has no attribute 'set_string' error all the time, it bumps up at the decoder config portion of the code.. can anyone let me know what the error is? let me know if I need to provider more info on the error..I am trying this on Windows 7 64 bit with python3.5
I am using a similar code to that of in examples but added it anyways for reference below

audio_file='C:/Users/tester/Downloads/joey.wav'
r = sr.Recognizer()
with sr.AudioFile(audio_file) as source:
    audio = r.record(source)
    try:
        print("Sphinx thinks you said " + r.recognize_sphinx(audio))
    except sr.UnknownValueError:
        print("Sphinx could not understand audio")
    except sr.RequestError as e:
        print("Sphinx error; {0}".format(e))

Traceback:
File "C:\Users\tester\AppData\Local\Programs\Python\Python35\lib\site-packages\speech_recognition\__init__.py", line 665, in recognize_sphinx
    config.set_string("-hmm", acoustic_parameters_directory)  # set the path of the hidden Markov model (HMM) parameter files
AttributeError: 'SwigPyObject' object has no attribute 'set_string'

**Comment by Uberi** [comment]
Hi @sravanth,

What version of PocketSphinx do you have?

You can check this by running the code snippet in the issue template.

**Comment by sravanth** [comment]
Hi @Uberi 

I have the 0.0.9 version..

I followed the notes from the section below to install ps on windows.. 
https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst

**Comment by dodysw** [comment]
Experiencing the same issue. Using Anaconda3 on Windows 7 with Python 3.5.2.

**Comment by dodysw** [comment]
I've fixed this by download the wheel package found at this page instead: 
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pocketsphinx

Specifically this one: pocketsphinx‑0.1.3‑cp35‑cp35m‑win_amd64.whl

**Comment by Uberi** [comment]
Seems like this issue is resolved - please re-open if @dodysw's solution doesn't work!

**Comment by jchwenger** [comment]
I just came across the same problem:
- Linux Mint 18.2
- Conda 4.8.1
- Python 3.6.9

```
speechrecognition         3.6.3                 py36_1000    conda-forge
pocketsphinx              0.8               h14c3975_1002    conda-forge
pocketsphinx-python       0.1.3            py36h470a237_0    conda-forge
sphinxbase                0.8.5prealpha     h14c3975_1000    conda-forge
swig                      4.0.1                he1b5a44_0    conda-forge
pyaudio                   0.2.11           py36h14c3975_2    nwani
```

The message:
```
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Say something!
Traceback (most recent call last):
  File "microphone_recognition.py", line 16, in <module>
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
  File "/home/default/miniconda3/envs/p36/lib/python3.6/site-packages/speech_recognition/__init__.py", line 666, in recognize_sphinx
    config.set_string("-hmm", acoustic_parameters_directory)  # set the path of the hidden Markov model (HMM) parameter files
AttributeError: 'SwigPyObject' object has no attribute 'set_string'
swig/python detected a memory leak of type 'Config *', no destructor found.
```
It works once (without recognizing what I'm saying), then throws that error. 

I am not super experienced with installing from wheel files, and notice that the pocketsphinx versions are far beyond what they were in 2017. Would you still recommend I try install pocketsphinx from the link @dodysw used, and is it ok to use that in parallel with Conda? 

Thanks a lot!
