### ISSUE TITLE
Recognize given audio data directly

### ISSUE THREAD

**Issue by jhoelzl** [Uberi/speech_recognition#213]
Hello,

in my application, i receive audio data in the form of byte code (variable `sound_bytes`):

So, for the speech recognition, i save the audio as file and then read it again:
```python
import speech_recognition as sr

r = sr.Recognizer()

filename = 'temp.wav'

# Save audio data
f = open(filename, 'wb+')
        f.write(sound_bytes)
        f.close()

# Read audio data
with sr.AudioFile(audio_filename) as source:
    audio_source = r.record(source)  # read the entire audio file

# Speech Recognition
text = r.recognize_google(audio_data=audio_source,
                                               key='xxx', 'en-US', show_all=False)

```
I am wondering if i can avoid the file save and read process and directly pass the variable `sound_bytes` into the recognize() function or transform it to a type `audio_source`?

When i replace 

```python
text = recognizer.recognize_google(audio_data=audio_source,
                                               key='xxx', 'en-US', show_all=False)
```

with

```python
text = recognizer.recognize_google(audio_data=sound_bytes,
                                               key='xxx', 'en-US', show_all=False)
```

i get 
> "Source must be an audio source"

**Comment by jhoelzl** [comment]
I could solve it using this function to convert my audio frame data into an audio source type:

```python
import speech_recognition as sr

r = sr.Recognizer()

# Convert Audio to Audio Source Format
audio_source = sr.AudioData(sound_bytes, 16000, 2)

text = recognizer.recognize_google(audio_data=audio_source,
                                               key='xxx', 'en-US', show_all=False)
```

**Comment by raghavrathi10** [comment]
As mentioned by the author i am also trying to convert speech to text directly without using a .wav file. 
I am using pyaudio to record an audio stream and i am trying to convert the stream directly once i stop recording. 
To verify that the recording is correct, i am also saving the stream into a .wav file. 
below is the implementation.

`

CHUNK = 1024
FORMAT = pyaudio.paInt16
CHANNELS = 2
RATE = 44100
RECORD_SECONDS = 5
WAVE_OUTPUT_FILENAME = get_nonexistant_path("voice.wav")


p = pyaudio.PyAudio()

stream = p.open(format=FORMAT,
                channels=CHANNELS,
                rate=RATE,
                input=True,
                frames_per_buffer=CHUNK)

print("* recording")
aud_width = p.get_sample_size(FORMAT)
frames = []

for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
    data = stream.read(CHUNK)
    frames.append(data)

print("* done recording")

r = sr.Recognizer()

audio_bytes = b''.join(frames)
audio_source = sr.AudioData(audio_bytes, RATE, aud_width)

try:
    print('Trying to convert')
    text = r.recognize_google(audio_data=audio_source, language='en-US', show_all=True)
    print(text)

except sr.UnknownValueError:
    print("Could not understand")

stream.stop_stream()
stream.close()
p.terminate()

wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
wf.setnchannels(CHANNELS)
wf.setsampwidth(p.get_sample_size(FORMAT))
wf.setframerate(RATE)
wf.writeframes(b''.join(frames))
wf.close()

`
When i run the program the output is '[ ]'.
When i run the translating using the wave file, i get correct output. Can someone please help me.

**Comment by rayavarapuvikram1** [comment]
> As mentioned by the author i am also trying to convert speech to text directly without using a .wav file.
> I am using pyaudio to record an audio stream and i am trying to convert the stream directly once i stop recording.
> To verify that the recording is correct, i am also saving the stream into a .wav file.
> below is the implementation.
> 
> `CHUNK = 1024
> FORMAT = pyaudio.paInt16
> CHANNELS = 2
> RATE = 44100
> RECORD_SECONDS = 5
> WAVE_OUTPUT_FILENAME = get_nonexistant_path("voice.wav")
> 
> p = pyaudio.PyAudio()
> 
> stream = p.open(format=FORMAT,
> channels=CHANNELS,
> rate=RATE,
> input=True,
> frames_per_buffer=CHUNK)
> 
> print("* recording")
> aud_width = p.get_sample_size(FORMAT)
> frames = []
> 
> for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
> data = stream.read(CHUNK)
> frames.append(data)
> 
> print("* done recording")
> 
> r = sr.Recognizer()
> 
> audio_bytes = b''.join(frames)
> audio_source = sr.AudioData(audio_bytes, RATE, aud_width)
> 
> try:
> print('Trying to convert')
> text = r.recognize_google(audio_data=audio_source, language='en-US', show_all=True)
> print(text)
> 
> except sr.UnknownValueError:
> print("Could not understand")
> 
> stream.stop_stream()
> stream.close()
> p.terminate()
> 
> wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
> wf.setnchannels(CHANNELS)
> wf.setsampwidth(p.get_sample_size(FORMAT))
> wf.setframerate(RATE)
> wf.writeframes(b''.join(frames))
> wf.close()
> `
> When i run the program the output is '[ ]'.
> When i run the translating using the wave file, i get correct output. Can someone please help me.

same issue for me also did u solve it?

**Comment by raghavrathi10** [comment]
> > As mentioned by the author i am also trying to convert speech to text directly without using a .wav file.
> > I am using pyaudio to record an audio stream and i am trying to convert the stream directly once i stop recording.
> > To verify that the recording is correct, i am also saving the stream into a .wav file.
> > below is the implementation.
> > `CHUNK = 1024
> > FORMAT = pyaudio.paInt16
> > CHANNELS = 2
> > RATE = 44100
> > RECORD_SECONDS = 5
> > WAVE_OUTPUT_FILENAME = get_nonexistant_path("voice.wav")
> > p = pyaudio.PyAudio()
> > stream = p.open(format=FORMAT,
> > channels=CHANNELS,
> > rate=RATE,
> > input=True,
> > frames_per_buffer=CHUNK)
> > print("* recording")
> > aud_width = p.get_sample_size(FORMAT)
> > frames = []
> > for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
> > data = stream.read(CHUNK)
> > frames.append(data)
> > print("* done recording")
> > r = sr.Recognizer()
> > audio_bytes = b''.join(frames)
> > audio_source = sr.AudioData(audio_bytes, RATE, aud_width)
> > try:
> > print('Trying to convert')
> > text = r.recognize_google(audio_data=audio_source, language='en-US', show_all=True)
> > print(text)
> > except sr.UnknownValueError:
> > print("Could not understand")
> > stream.stop_stream()
> > stream.close()
> > p.terminate()
> > wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
> > wf.setnchannels(CHANNELS)
> > wf.setsampwidth(p.get_sample_size(FORMAT))
> > wf.setframerate(RATE)
> > wf.writeframes(b''.join(frames))
> > wf.close()
> > `
> > When i run the program the output is '[ ]'.
> > When i run the translating using the wave file, i get correct output. Can someone please help me.
> 
> same issue for me also did u solve it?

I didn't find a fix for it but I found a workaround which worked fine for me. Instead of directly trying to convert the stream to text, I first the stream to a .wav file and then used speech recognition on that file. So basically I was just rewriting on that .wav file after speech to text conversion.
Hope this helps.

**Comment by rayavarapuvikram1** [comment]
> > > As mentioned by the author i am also trying to convert speech to text directly without using a .wav file.
> > > I am using pyaudio to record an audio stream and i am trying to convert the stream directly once i stop recording.
> > > To verify that the recording is correct, i am also saving the stream into a .wav file.
> > > below is the implementation.
> > > `CHUNK = 1024 FORMAT = pyaudio.paInt16 CHANNELS = 2 RATE = 44100 RECORD_SECONDS = 5 WAVE_OUTPUT_FILENAME = get_nonexistant_path("voice.wav") p = pyaudio.PyAudio() stream = p.open(format=FORMAT, channels=CHANNELS, rate=RATE, input=True, frames_per_buffer=CHUNK) print("* recording") aud_width = p.get_sample_size(FORMAT) frames = [] for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)): data = stream.read(CHUNK) frames.append(data) print("* done recording") r = sr.Recognizer() audio_bytes = b''.join(frames) audio_source = sr.AudioData(audio_bytes, RATE, aud_width) try: print('Trying to convert') text = r.recognize_google(audio_data=audio_source, language='en-US', show_all=True) print(text) except sr.UnknownValueError: print("Could not understand") stream.stop_stream() stream.close() p.terminate() wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb') wf.setnchannels(CHANNELS) wf.setsampwidth(p.get_sample_size(FORMAT)) wf.setframerate(RATE) wf.writeframes(b''.join(frames)) wf.close() `
> > > When i run the program the output is '[ ]'.
> > > When i run the translating using the wave file, i get correct output. Can someone please help me.
> > 
> > 
> > same issue for me also did u solve it?
> 
> I didn't find a fix for it but I found a workaround which worked fine for me. Instead of directly trying to convert the stream to text, I first the stream to a .wav file and then used speech recognition on that file. So basically I was just rewriting on that .wav file after speech to text conversion.
> Hope this helps.

Can you please share how you did it to me?  
My mail id is rayavarapuvikram1@gmail.com
