### ISSUE TITLE
audioop.error: Size should be 1, 2 or 4

### ISSUE THREAD

**Issue by sudevschiz** [Uberi/speech_recognition#214]
Steps to reproduce
------------------

1. While calling `record(source)`

Expected behaviour
------------------
.flac file sourced without error

Actual behaviour
----------------

(What happened instead? How is it different from what you expected?)

```
Traceback (most recent call last):
  File "recog.py", line 14, in <module>
    audio = r.record(source) # read the entire audio file
  File "/home/ubuntu/speech_recognition/speech_recognition/__init__.py", line 471, in record
    buffer = source.stream.read(source.CHUNK)
  File "/home/ubuntu/speech_recognition/speech_recognition/__init__.py", line 276, in read
    buffer = audioop.tomono(buffer, sample_width, 1, 1)  # convert stereo audio data to mono
audioop.error: Size should be 1, 2 or 4
```

Saw the issue earlier. But it was mentioned that it was fixed. 
Am I missing something?

System information
------------------

(Delete all the statements that don't apply.)

My **system** is "Ubuntu 16.04 LTS x64"

My **Python version** is Python 3.5.2

My **Pip version** is pip 9.0.1

My **SpeechRecognition library version** is 3.6.3

I don't have PyAudio installed. 

I **installed PocketSphinx from** pip

**Comment by Uberi** [comment]
Thanks for reporting this @sudevschiz, this is now fixed in f9fdfb628318dd6c32a9862a470459329d9ee1f0. Expect to see it in the next release!
