### ISSUE TITLE
Houndify response call is not giving transcription of full audio

### ISSUE THREAD

**Issue by voidabhi** [Uberi/speech_recognition#216]
Uploaded a 6 minute audio file for which got 20% of text in result

Code

```python
import speech_recognition as sr
from os import path

AUDIO_FILE = path.join(path.dirname(path.realpath(__file__)), "6min.wav")
HOUNDIFY_CLIENT_ID = ""
HOUNDIFY_CLIENT_KEY = ""

try:
    r = sr.Recognizer()
    with sr.AudioFile(AUDIO_FILE) as source: audio = r.record(source)
    print("Houndify thinks you said " + r.recognize_houndify(audio, client_id=HOUNDIFY_CLIENT_ID, client_key=HOUNDIFY_CLIENT_KEY))
except sr.UnknownValueError:
    print("Houndify could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Houndify service; {0}".format(e))
```

**Comment by Uberi** [comment]
Hi @voidabhi,

See: https://www.houndify.com/pricing#how-do-credits-work

All Houndify requests will cost a Houndify credit per every 4 seconds. If you're on a free plan, you get 100 free credits a day. This works out to about 6.7 minutes before your audio no longer gets processed.

I suspect running out of credits is the issue. In other words, Houndify won't let you recognize longer audio files unless you go for a paid plan.

I recommend PocketSphinx or Google Cloud Speech if you're trying to do longer form text.
