### ISSUE TITLE
AssertError

### ISSUE THREAD

**Issue by Ain29** [Uberi/speech_recognition#222]
while executing __main__.py, I had to face this error

 ```
File "C:\Python27\lib\site-packages\speech_recognition\__init__.py", line 495, in adjust_for_ambient_noise
    assert self.pause_threshold >= self.non_speaking_duration >= 0
AssertionError
```

I donot know how to resolve this problem

**Comment by Uberi** [comment]
Your recognizer settings are incorrect, but without any of the information requested in the issue template, I can't tell you why.

I'm going to close this now, but feel free to re-open after filling in that information!
