### ISSUE TITLE
use google cloud api

### ISSUE THREAD

**Issue by tsuperprince** [Uberi/speech_recognition#223]
hi all
i am new in python.
I have install speech_recognition and consider to use google speech cloud. 
but i don't know how to config the google cloud speech json.
Anyone please help me. Thank you

**Comment by Uberi** [comment]
Hi @tsuperprince,

There are detailed instructions in the documentation: https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instancerecognize_google_cloudaudio_data-credentials_json--none-language--en-us-preferred_phrases--none-show_all--false

Also see the Google Cloud Speech example: https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py#L33

Please feel free to ask if you have any specific questions.
