### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Towerss** [Uberi/speech_recognition#227]
Steps to reproduce
------------------

1. After running the __main__.py file in a Windows machine, using a direct import to the __init__.py file, the pyspeechrecognition starts to work (it recognizes the local microphone, calibrates the initial energy threshold and awaits for speech). The speech is detected when started and recorded, but when invocating any of the recognition methods to process the file, the error occurs. The files are working in Linux Debian. This error was reproduced in Windows 8 and windows 10 machines.

Expected behaviour
------------------

The expected behavior is as in Linux testing, for the app to return the recognized speech to text.

Actual behaviour
----------------

```
C:\Python27\python.exe "C:/Users/Diego/Documents/Acme/Python Speech Recognition/Pi GCP Boris/__main__.py"
A moment of silence, please...
Set minimum energy threshold to 125.527872912
Say something!
Got it! Now to recognize it...
Traceback (most recent call last):
  File "C:/Users/Diego/Documents/Acme/Python Speech Recognition/Pi GCP Boris/__main__.py", line 28, in <module>
    value = r.recognize_google(audio)
  File "C:\Users\Diego\Documents\Acme\Python Speech Recognition\Pi GCP Boris\__init__.py", line 726, in recognize_google
    convert_width=2  # audio samples must be 16-bit
  File "C:\Users\Diego\Documents\Acme\Python Speech Recognition\Pi GCP Boris\__init__.py", line 438, in get_flac_data
    ], stdin=subprocess.PIPE, stdout=subprocess.PIPE, startupinfo=startup_info)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Process finished with exit code 1

System information
------------------

(Delete all the statements that don't apply.)

My **system** is <Windows 10 x64>.

My **Python version** is <Python 2.7.13>.

My **Pip version** is <pip 9.0.1>.

My **SpeechRecognition library version** is <3.6.3>.

My **PyAudio library version** is <0.2.11>.

I **installed PocketSphinx from** <Homebrew>.

**Comment by Uberi** [comment]
Hi @Towerss,

It seems like you're directly copying `__init__.py` into your project. Instead, you'll want to at least copy in all the `flac-*` files, or better yet, the entire `speech_recognition` folder, which contains several other files that make this library work better. For example, the `speech_recognition/pocketsphinx-data` folder is required to use most languages with `recognize_sphinx`.

Please reopen this issue if that doesn't solve the problem!
