### ISSUE TITLE
Library exception: simple fix required

### ISSUE THREAD

**Issue by soumya-gk** [Uberi/speech_recognition#228]
Issue details: Library exception, everytime

Steps to reproduce:

1)  From examples modify(add necessary credentials) microphone_recognition.py to run google cloud recognizer.
2) Run microphone_recognition.py

Alternative:
Create an instance of the PortableNamedTemporaryFile class defined in __init__.py

Error observed:
```
Traceback (most recent call last):
  File "audio_recognize.py", line 64, in <module>
    print("Google Cloud Speech thinks you said " + r.recognize_google_cloud(audio, credentials_json=GOOGLE_CLOUD_SPEECH_CREDENTIALS))
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 750, in recognize_google_cloud
    with PortableNamedTemporaryFile("w") as f:
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 1038, in __enter__
    self._file = open(file_descriptor, self.mode)
TypeError: coercing to Unicode: need string or buffer, int found
```
Suggested fix:
 In "__init__.py", inside PortableNamedTemporaryFile class definition, modify line 5 in "__enter__" method from - 
```
def __enter__(self):
        # create the temporary file and open it
        import tempfile
        file_descriptor, file_path = tempfile.mkstemp()
        self._file = open(file_descriptor, self.mode)     #line 5 

        # the name property is a public field
        self.name = file_path
        return self
```
to:

`self._file = open(file_path, self.mode)`

System information
------------------

(Delete all the statements that don't apply.)

My **system** is "Ubuntu 16.04 LTS x64"

My **Python version** is 2.7.12

My **Pip version** is 9.0.1

My **SpeechRecognition library version** is 3.6.3

My **PyAudio library version** is 0.2.11

I **installed PocketSphinx from** source code

**Comment by Uberi** [comment]
Hey @soumya-gk,

This should be fixed in version 3.6.5! Previously, it was always broken on Python 2.
