### ISSUE TITLE
No error - no output

### ISSUE THREAD

**Issue by tsvetomir777** [Uberi/speech_recognition#23]
Hello ,
I am developing voice recognition in virtual reality. I am using Vizard (32 bit) and python 2.7
i was able to install all the libraries needed but still when i run the code i get no output.
![code packages](https://cloud.githubusercontent.com/assets/9430626/6598754/153f32b0-c806-11e4-9376-c3a2ddb28e36.png)

![output](https://cloud.githubusercontent.com/assets/9430626/6598760/251047ce-c806-11e4-8c7f-f0b7eee60ecd.png)

**Comment by Uberi** [comment]
Hi @tsvetomir777,

Does the library wait until you stop speaking, or does it terminate immediately? Is your microphone gain at a suitable value? Have you tried the library with a WAV audio sample?

**Comment by tsvetomir777** [comment]
Hi @Uberi ,

I am not sure if I must create some kind of listener function that listens all the time. I have tried the WAV audio sample as the code that you suggested in the other issues(2nd picture a bit up). I have tried also r.energy_threshold = 500.
