### ISSUE TITLE
Google Cloud speech recognition temporary file error

### ISSUE THREAD

**Issue by beeedy** [Uberi/speech_recognition#231]
Steps to reproduce
------------------

1. paste JSON string into variable GOOGLE_CLOUD_SPEECH_CREDENTIALS in microphone_recognition.py
2. run microphone_recognition.py
3. Speek into microphone to begin process of speech recogition
------------------

Expected it to return a json string/file with the Google cloud speech results

Actual behavior
----------------

Failed to open temporary file after creation. 

```
Traceback (most recent call last):
  File "microphone_recognition.py", line 38, in <module>
    print("Google Cloud Speech thinks you said " + r.recognize_google_cloud(audio, credentials_json=GOOGLE_CLOUD_SPEECH_CREDENTIALS))
  File "/Users/Me/speech_recognition/speech_recognition/__init__.py", line 904, in recognize_google_cloud
    with PortableNamedTemporaryFile("w") as f:
  File "/Users/Me/speech_recognition/speech_recognition/__init__.py", line 1213, in __enter__
    self._file = open(file_descriptor, self.mode)
TypeError: coercing to Unicode: need string or buffer, int found
```

At this point ```file_descriptor``` was a int of value 5 and ```self.mode``` is a string of value "w"

Paste of the 3 lines leading up to the crash:
```
import tempfile
file_descriptor, file_path = tempfile.mkstemp()
self._file = open(file_descriptor, self.mode)
```

System information
------------------

My **system** is OSX 10.12.4 (16E195)

My **Python version** is 2.7.10

My **Pip version** is 9.0.1

My **SpeechRecognition library version** is 3.6.3. 

My **PyAudio library version** is 0.2.11

**Comment by Uberi** [comment]
Hi @beeedy,

You're running version 3.6.3. The latest version, 3.6.5, already has a fix for this. Try updating to that version, and see if it helps!

**Comment by beeedy** [comment]
I have the most recent version from github, which seems to still have __version__ set to 3.6.3 so as far as I can tell, this issue exists in the most up-to-date codebase unless the releases are being pulled from somewhere else
