### ISSUE TITLE
Houndify : Can anyone help me how to login "/login" with python ? 

### ISSUE THREAD

**Issue by DarKWinGTM** [Uberi/speech_recognition#234]
Houndify : Can anyone help me how to login "/login" with python ? 

I trying work with houndify but some time they remove account without reason , So now i trying do check account is in working or not , But i don known how to login webpage "https://www.houndify.com/login" with python. if respond back this account is not already it's mean this account is not active anymore 

Thanks.

**Comment by Uberi** [comment]
Hi @DarKWinGTM,

This is a speech recognition library. You may want to look into web scraping tools like [mechanize](http://wwwsearch.sourceforge.net/mechanize/).
