### ISSUE TITLE
PocketSphinx other languages package link depracated 

### ISSUE THREAD

**Issue by MarkWh1te** [Uberi/speech_recognition#236]
the link in [pocketsphinx.rst](https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst#installing-other-languages) depracate 
https://www.dropbox.com/s/0iwx5ypp9uym66c/zh-CN.zip?dl=1
https://www.dropbox.com/s/115e3mf3y21x0b8/fr-FR.zip?dl=1

**Comment by Juanvulcano** [comment]
Yes! Having the same issue, also instructions on how to install a new language are confusing.
Can someone help?

**Comment by Uberi** [comment]
Hi @MarkWh1te,

Thanks for reporting! Fixed in d7c62ee56f0e43ac88235fbd367438a978aec206.

@Juanvulcano, sure - do you have a specific question?
