### ISSUE TITLE
PyAudio installation instructions for OS X are out of date

### ISSUE THREAD

**Issue by jdanford** [Uberi/speech_recognition#240]
As a prerequisite to installing PyAudio on OS X, the readme says to install PortAudio with the command `brew install portaudio && sudo brew link portaudio`. Homebrew >= 1.1.0 doesn't allow itself to run as root, and when I run `brew link portaudio` without `sudo`, Homebrew says that it's already linked, so I'm thinking the command can be changed to just `brew install portaudio`.

**Comment by Uberi** [comment]
Thanks @jdanford - as I test mainly on Linux, bug reports about these sorts of issues are highly welcome!

This is now fixed in 1953884f33f1c72eaec2776333dc7771a9cfdb12, and a new release will be out pretty soon.
