### ISSUE TITLE
Bundled PocketSphinx-Python is out of date

### ISSUE THREAD

**Issue by jdanford** [Uberi/speech_recognition#241]
The installation instructions for PocketSphinx-Python suggest installing the bundled wheel or building from source, but the wheel is for version 0.0.9 while the upstream project is on 0.1.3.

**Comment by ZmorzynskiK** [comment]
Today I was playing with PocketSphinx and I can see that currently, the wheel bundle is for version 0.1.3

**Comment by jdanford** [comment]
You're right, looks like this was fixed by 566a70b!
