### ISSUE TITLE
getting segmentation fault while listening from microphone

### ISSUE THREAD

**Issue by surajhes** [Uberi/speech_recognition#248]
hi while running the sample code to listen to speech from mic and then perform the speech to text on that input speech, i am getting a segmentation fault while listening.
Below is the source code for the described issue. How to proceed this?
import speech_recognition as sr

# Record Audio
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

**Comment by Uberi** [comment]
Hi @surajhes,

Please fill in all of the requested fields in the issue template, and feel free to re-open the issue once this is done. For example, the template asks for your OS, the entire code listing, and details about how you installed the library.
