### ISSUE TITLE
Different results on different machines

### ISSUE THREAD

**Issue by Aphire** [Uberi/speech_recognition#25]
I'm not sure if this counts as an "error" as such, however I feel it is worth noting.
I used the exact same .wav file on two separate machines, one windows, one linux and used the exact same python script to access the api.

The windows machine gave me the result "Don" whereas the linux machine gave me "Dance" (Don not even being in the list of possible transcriptions)

Is there any reason for this? and is one OS better than the other?

Thanks,
Alexon

**Comment by Uberi** [comment]
Hi @Aphire,

There are two possible causes for this, assuming that your audio input is exactly the same:

1. The FLAC encoder might function slightly differently on Windows compared to on Linux. This is quite likely if the library was unable to use its bundled FLAC encoder and fell back on using the system version, which might have entirely different encoding options and defaults.
2. The API itself might be returning different results based on the request user agent. This is unlikely in my opinion, but is still possible.

Both OSs are equally supported, but personally I test it on Windows a bit less

**Comment by Aphire** [comment]
Interesting anyway!

Cheers for the library.

**Comment by benreaves** [comment]
I encountered the same problem 2 years ago, and the unofficial answer from Google was that different requests go to different servers, and each may have a slightly different Language Model and even Acoustic Models. They're continuously updated. So this is the expected behavior.
