### ISSUE TITLE
Can you run background_listening.py in nohup

### ISSUE THREAD

**Issue by akvkickstart** [Uberi/speech_recognition#250]
Steps to reproduce
------------------
I tried to run background_listening.py using nohup but nothing happens.

Basically, I want to autostart the background_listening.py using a headless unit. Is this possible ?

Thanks for your time.

**Comment by akvkickstart** [comment]
my script looks like...

_nohup python bg_voice.py &_

**Comment by Uberi** [comment]
Yes, this is possible. What happens when you run that command, and what did you expect would happen?

**Comment by akvkickstart** [comment]
Nothing is happening, when I run the code in command line, it works. Whenever I run nohup python bg_voice.py & , nothing happens:

ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline

That's all I see.

**Comment by akvkickstart** [comment]
This is how my /etc/rc.local looks like:

_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

cd /home/notna
#./run_voice.sh 1>> /home/notna/logs/voice_command.log &
nohup python bg_speech.py &
exit 0

**Comment by akvkickstart** [comment]
I know the issue, I installed python using my account and the script is being executed by root if I put it in rc.local. I simply change to sudo -u notna /home/notna/run_voice.sh .

And it is now working fine. Thanks for sharing this fantastic project.
