### ISSUE TITLE
How to recognize speech while recording ? [Question]

### ISSUE THREAD

**Issue by rena1234** [Uberi/speech_recognition#255]
Hi, there is a way to send chunks of the audio stream to wit.ai or another web api to be recognized while the recording process itself stills happening ?

**Comment by sujitvasanth** [comment]
listen and recognize are separate functions in the speech recognition library.
if you set up a background listen you can keep listening in 1 process and run the recognition in another process (most straightforwardly in the main process). you should set up some globals for the audiofile instances I have done this,.

**Comment by Uberi** [comment]
@sujitvasanth is correct - one way you can perform those operations simultaneously is to call `audio = r.listen(source)` on one thread, and `r.recognize_SOMETHING(audio)` on another. You can use `queue.Queue` to move the `audio` values from the listener thread to the recognizer thread.

I just added an example, [threaded_workers](https://github.com/Uberi/speech_recognition/blob/master/examples/threaded_workers.py), that demonstrates this in action. Check it out and see if it works for you!
