### ISSUE TITLE
Request: Add variable for "pronounciation-dictionary.dict" to the list of parameters of recognize_sphinx

### ISSUE THREAD

**Issue by 1account** [Uberi/speech_recognition#257]
Currently recognize_sphinx is defined as 
```
def recognize_sphinx(self, audio_data, language="en-US", keyword_entries=None, grammar=None, show_all=False)
```
and "pronounciation-dictionary.dict" is hard coded within this function. 

To be more flexible: Can you please add this to the header of the function so that the user can overwrite it? Thank you.

**Comment by Uberi** [comment]
Hi @1account,

In the interests of keeping things simple, I would prefer not to add too many options to these recognizer functions. That said, you can still specify your own dictionary, by modifying `pronounciation-dictionary.dict` files in `pocketsphinx-data/` folder. I'll close this now, but feel free to reopen if you have a strong use-case in mind!
