### ISSUE TITLE
Remote stream?

### ISSUE THREAD

**Issue by tfontoura** [Uberi/speech_recognition#258]
Is there a way to send the stream from computer 1 to computer 2 where speech_recognition (using google API) would be?
I'm asking because the second computer is a server that has less latency to  google and computer 3, where other processing steps happen.
The way I'm doing, recognizing on computer 1, retrieving the text, sending it back for further processing on computer 2 and 3, it's taking too long.

**Comment by Uberi** [comment]
Hi @tfontoura,

Yes, you can use any streaming software to get the audio across, and then (assuming you're on Linux with PulseAudio or JACK) route the streaming software's output to a loopback device. Here's a [tutorial](https://wiki.debian.org/audio-loopback) for PulseAudio (which is what you'll have in an out-of-the-box Ubuntu installation).

Once you have the loopback device set up, take the [microphone recognition](https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py) example, and replace `sr.Microphone` with `sr.Microphone(device_index=INDEX_OF_LOOPBACK_DEVICE)`.

You can figure out the correct value of `INDEX_OF_LOOPBACK_DEVICE` using the code in [this troubleshooting entry](https://github.com/Uberi/speech_recognition#the-recognizer-hangs-on-recognizer_instancelisten-specifically-when-its-calling-microphonemicrophonestreamread) - just replace `INDEX_OF_LOOPBACK_DEVICE` with the index corresponding to the loopback device from that code's output.

This should get you started. If you have further questions, feel free to re-open this issue.
