### ISSUE TITLE
It's can be worked offline on mobile phone?

### ISSUE THREAD

**Issue by danielparker00** [Uberi/speech_recognition#260]
I'm going to make a Voice Command Recognizer which can work offline on mobile.
STT is working accurately  under the noise.
Can I use this directly? Or should I improve the engine?
Thanks.

**Comment by Uberi** [comment]
Hi @danielparker00,

This library is not designed to work on mobile devices. Instead, you may want to consider the speech recognition capabilities built into most modern mobile OSs like Android or iOS, as well as the PocketSphinx bindings for these platforms - [here are Android bindings](https://github.com/cmusphinx/pocketsphinx-android), for example.
