### ISSUE TITLE
Python SpeechRecognition library doesn't work with Persian language

### ISSUE THREAD

**Issue by mohammadmh** [Uberi/speech_recognition#261]
This is my code:

```python
import speech_recognition as sr

r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

try:
 
    print("you said " + r.recognize_google(audio,key="fa-IR"))
except sr.UnknownValueError:
    print(" could not understand audio")

except sr.RequestError as e:
    print("Could not request results".format(e))
```

I got it working without ' key="fa_IR" ' but it doesn't work now and prints "Could not request results" every time.I tried other language keys but the same thing happened.
Is the problem with my code?
What can I do?

**Comment by Uberi** [comment]
Hi @mohammadmh,

Please refer to [the documentation](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instancerecognize_googleaudio_data-key--none-language--en-us-show_all--false) for `recognize_google` - the `key` parameter is for the API key, not the language. Instead, you can specify the language using the `language` parameter.

Persian should be supported - at least it is in the [Cloud Speech API](https://cloud.google.com/speech/docs/languages). Feel free to re-open this issue if that doesn't work!

**Comment by mr-pourghorban** [comment]
how can i use "fa-IR" in python when i am offline ?
