### ISSUE TITLE
Windows 10 audiodg.exe Recognizer.listen memory leak?

### ISSUE THREAD

**Issue by ZmorzynskiK** [Uberi/speech_recognition#265]
Steps to reproduce
------------------

1. I have a thread in which I call `Recognizer.listen` periodically, all the time. Something like this:

```python
# this is run method from the Thread subclass
def run(self):
    while self._stop_requested == False:
        with self._audio_source as s:
            try:
                audio = self._recognizer.listen(s, 0.5, self._hot_word_time_limit)
            except sr.WaitTimeoutError:  # listening timed out, just try again
                continue
```

2. When I open Task manager I can see that audiodg.exe Windows Audio Device Graph Isolation process is constantly eating up memory, up until the end.

3. `self._audio_source` is the `Microphone` class, `self._recognizer` is `Recognizer` class.

4. Looks like only Windows restart helps to free the memory. Closing the Python application does not free the memory.

Expected behaviour
------------------

Not eating up the entire memory.

Actual behaviour
----------------

Audiodg.exe process constantly eats up memory.

System information
------------------

My **system** is Windows 10 x64.

My **Python version** is Python 3.5.2 :: Anaconda 4.2.0 (64-bit)

My **Pip version** is pip 8.1.2

My **SpeechRecognition library version** is 3.7.1

My **PyAudio library version** is 0.2.11

I **installed PocketSphinx from** third-party directory

**Comment by ZmorzynskiK** [comment]
After a little digging, it looks like it's actually a bug in Windows and/or Lenovo (I have a thinkpad) drivers.
https://answers.microsoft.com/en-us/windows/forum/windows8_1-performance/audio-device-graph-isolation-eats-up-memory/3366347f-f9ed-43de-9254-ee21937d2531

Can someone maybe confirm it?

**Comment by ZmorzynskiK** [comment]
I've updated Realtek audio drivers, disabled all microphone enhancements and disabled microphone exclusive modes - after a restart, it looks much better, the audiodg.exe memory is increasing but much much slower.

I'll close this issue because it looks like it's not related to python.

**Comment by Uberi** [comment]
Thanks for the write-up @ZmorzynskiK - hope you can get it resolved entirely. Does the memory increase stop after a certain threshold, or does it grow until you're entirely out of it?

**Comment by ZmorzynskiK** [comment]
Right now my app is working for like an hour or so and it looks like audiodg.exe is keeping the RAM usage at about 36-40 MB.
Previously, after that period of time, it would've taken at least several 100s of MB, maybe event gigs.
