### ISSUE TITLE
[Feature Request] Progress bar to monitor progress in audio transcribe

### ISSUE THREAD

**Issue by potholiday** [Uberi/speech_recognition#266]
I am using this library to convert audio to text and it works without any error. I have used the [example](https://github.com/Uberi/speech_recognition/blob/master/examples/audio_transcribe.py) script to try out some of my audio files and it works perfectly in  google cloud, wit.ai and houndify api . The one thing I noticed is that smaller files (less than 1 minute audio) tends to give results faster whereas larger files (takes a longer time (more than 10 minutes for a 5 minute audio).

I would like a feature in which we can monitor the progress of our audio to text conversion. I assume the longer time for conversion of the file in my case can be caused by my lower internet speed . it is a request to add a progress bar to monitor the upload progress of the file to an external cloudapi.

**Comment by datatalking** [comment]
I might be able to help on this, there were a few progress bar projects that I looked at. If someone was able to collaborate we could come up with a prototype for python.

**Comment by Uberi** [comment]
Hi @potholiday,

I think this would be a useful thing to have! Unfortunately, the amount of time a given transcription takes isn't very consistent, and estimating the remaining time is pretty inaccurate. In other words, I'm not sure it's feasible given the way it's implemented now.
