### ISSUE TITLE
How to handle WaitTimeoutError exception?

### ISSUE THREAD

**Issue by tfontoura** [Uberi/speech_recognition#267]
Script catches RequestError and UnknownValueError exceptions but it doesn't catch WaitTimeoutError exception. Can you help?
My code, after `try` is

    except sr.WaitTimeoutError as e:
        print("Timeout; {0}".format(e))
    except sr.UnknownValueError:
        print("Google Speech Recognition could not understand audio")
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))

When there is a timeout, throws me the following:

```
  phrase = rec.listen(fala,timeout=5)
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 551, in listen
    raise WaitTimeoutError("listening timed out while waiting for phrase to start")
speech_recognition.WaitTimeoutError: listening timed out while waiting for phrase to start
sys.excepthook is missing
lost sys.stderr
```

**Comment by Uberi** [comment]
Hi @tfontoura,

That seems like it should be caught just fine, but can't be sure since it's only a snippet. Can you provide a working example that demonstrates the issue?

**Comment by tfontoura** [comment]
`
def reconhecimento():
    print("acender a luz branca")
    exitcode = call(["/home/pi/dev/speech/detectedmagic.sh"])
    rec = sr.Recognizer()
    with sr.Microphone(5,chunk_size=4096) as fala:
         rec.pause_threshold=0.8
         rec.phrase_time_limit=8 
         #rec.operation_timeout=10
         rec.instant_energy_threshold=300
         rec.dynamic_energy_threshold=True
         ##rec.dynamic_energy_adjustment_ratio=1.5
         rec.adjust_for_ambient_noise(fala,duration=0.5)
         exitcode = call(["/home/pi/dev/speech/detected.sh"])
         print("Pois não?")
         print("Apagar luz branca, acender a luz azul")
         frase = rec.listen(fala,timeout=5)
         #frase = rec.listen(fala)

    try:
        stt = rec.recognize_google(frase,language='pt-BR')
        print(stt)
        print("Piscar a luz por mais x segundos")
        subprocess.Popen(["/home/pi/.comandos/stt.sh",stt])

    except sr.WaitTimeoutError as e:
        print("Timeout; {0}".format(e))
    except sr.UnknownValueError:
        print("Google Speech Recognition could not understand audio")
        exitcode = call(["/home/pi/speech/nao-entendi.sh"])
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))        
        exitcode = call(["/home/pi/speech/erro.sh"])`

**Comment by tfontoura** [comment]
[ariel.py.txt](https://github.com/Uberi/speech_recognition/files/1268453/ariel.py.txt)

**Comment by Uberi** [comment]
Hi @tfontoura,

The exception is being thrown by `frase = rec.listen(fala,timeout=5)`, which is outside of the `try` block. If you want to catch an exception, it has to be inside a `try` block.

Feel free to re-open if this doesn't solve the issue.

**Comment by taishi-nammoto** [comment]
Hi @tfontoura 

In case, you want to specify the listening duration instead of the timeout, you can use "record" instead of "listen"

r = sr.Recognizer()
with sr.Microphone() as source:
        audio = r.record(source, duration = 4)
