### ISSUE TITLE
Experiencing issues with pyaudio integration.

### ISSUE THREAD

**Issue by rahul1205** [Uberi/speech_recognition#269]
Hi, so I just cloned a fresh copy of your repository and ran the __main__.py and ended up getting the following error.

```
$ python __main__.py 
Traceback (most recent call last):
  File "__main__.py", line 4, in <module>
    m = sr.Microphone()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 86, in __init__
    device_info = audio.get_device_info_by_index(device_index) if device_index is not None else audio.get_default_input_device_info()
  File "build/bdist.linux-x86_64/egg/pyaudio.py", line 949, in get_default_input_device_info
    device_index = pa.get_default_input_device()
IOError: No Default Input Device Available
```

Any help would be appreciated.

**Comment by Uberi** [comment]
Hi @rahul1205,

You'll want to either use `sr.Microphone(device_index=INSERT_DEVICE_INDEX_HERE)`, where `INSERT_DEVICE_INDEX_HERE` is the index of the microphone you want to use, or set a default microphone in your audio settings.

To get the index of the microphone, try running this script:

```python
import speech_recognition as sr
for index, name in enumerate(sr.Microphone.list_microphone_names()):
    print("Microphone with name \"{1}\" found for `Microphone(device_index={0})`".format(index, name))
```

**Comment by rahul1205** [comment]
Hi @uberi
So I am a newbie in python, but what I can tell you for sure is that pyaudio doesn't detect any of my input microphones, including the default mic of my laptop. 
I ran this script pyaudio.PyAudio().get_device_count() and this returned me 0. It's strange because just yesterday, the script was running fine and just restarting the device caused this error. 
I searched for this error but couldn't find anything on internet. Kindly help me resolve this.

**Comment by Uberi** [comment]
Hi @rahul1205,

Did you run the script I posted above? What was the output?

**Comment by rahul1205** [comment]
Hi @Uberi 
The script you posted above shows this error
AttributeError: type object 'Microphone' has no attribute 'list_microphones_names'
I am guessing it is unable to find a microphone, although the mic works fine for other applications.

**Comment by giftig** [comment]
> I am guessing it is unable to find a microphone
Incorrect; that means the method `list_microphones_names` doesn't exist. It was a typo: it should be `list_microphone_names`.

**Comment by rahul1205** [comment]
Hi @giftig
Yeah sorry, my bad.! So after repeated attempts on fixing this error and going through pyaudio documentations and manually installing ALSA libraries, I gave up and installed everything from scratch on a fresh instance of Ubuntu and everything seems to be running perfectly fine now. 

It seems that the problem arises because pyaudio installed through portaudio is probably unstable. I would suggest you guys to look into this 
https://github.com/larsimmisch/pyalsaaudio as a replacement of pyaudio-portaudio extension. 
P. S. Thanks for fast responses @uberi and I'll surely disturb you once again if I get stuck ;)
