### ISSUE TITLE
Am I correct that there's no way to have SpeechRecognition get time offsets from Google Speech's API?

### ISSUE THREAD

**Issue by NathanWailes** [Uberi/speech_recognition#271]
I need the time offsets for each transcribed word, as described [here](https://cloud.google.com/speech/docs/basics#time-offsets). It looks like there's no way to do that with SpeechRecognition, and so I'd need to just use Google's Python client. Is that correct?

**Comment by Uberi** [comment]
Hi @NathanWailes,

Until 6f61f6b, this was not supported. However, support for this is now available in the latest development version! Until the next release, you may want to stay with Google's Python client, but you may be able to simplify your code soon.

**Comment by NathanWailes** [comment]
Thanks for the heads-up!
