### ISSUE TITLE
SpeechRecognition installed with pip and pip3 but can't import it in either terminal or atom.io

### ISSUE THREAD

**Issue by sanster9292** [Uberi/speech_recognition#272]
Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)
Every time I try to import speech_recogntion in a python file, it can't be imported and I get an error.
2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)
I wrote a one-line file with simple command 
import speech-recognition and it gives me the following error:
               import speech_recognition as sr
               ImportError: No module named speech_recognition
I have this module installed using both pip and pip3 and it appears in
their list of installed modules but I can't seem to get it to be imported when i try executing a script either from the terminal or in atom.io. I am not sure why this is, I would really appreciate any help in this regard

3. (If there are any files, like audio recordings, don't forget to include them.)

Expected behaviour
------------------

(What did you expect to happen?)

Actual behaviour  for the module to be imported properly without any error
----------------

(What happened instead? How is it different from what you expected?)

```I get an ImportError and I am not sure why 
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all the statements that don't apply.)

My **system** is <Ubuntu 16.04 LTS >

My **Python version** is <Python 2.7.12>. 

My **Pip version** is <pip 9.0.1>. 

My **SpeechRecognition library version** is <SpeechRecognition (3.6.5)
>.

My **PyAudio library version** is 0.2.8

**Comment by shafaypro** [comment]
You must have multiple versions like anaconda also installed which overrides the running instances but the module is installed in the pip versions. Also if you are using pycharm : you can configure your idle through File --> settings --> Project intrepreter --> choose the intrepreter for the project. The problem is that there are multiple pip's of 2 and 3
Like Anaconda pip itself, and then python pip2 and python pip3 
while the pip is the main thing that It might be possibility that anaconda is being overriden on all pips so for that  use 
"CONDA INSTALL Speech_recognition" and then try

**Comment by sanster9292** [comment]
I actually don't have anaconda installed on my system. I had it in the past and i removed it from my system and the scripts I am trying to execute now had worked in the past after I had removed the anaconda package which is why I am not sure why they stopped working now

**Comment by shafaypro** [comment]
Check the default environment settings, there must be a missing environment of python there.
and which python version are you using ?

**Comment by sanster9292** [comment]
I am just getting started with the whole python environment thing so please excuse me asking such simple questions, but how would i check the default environment settings, or a missing python environment?

**Comment by sanster9292** [comment]
When i input this command into the terminal 
readlink -f $(which python)

it gives me 

/usr/bin/python2.7


Is this what you were asking for about the version of python

**Comment by Uberi** [comment]
Hi @sanster9292,

Can you post the following outputs?

* `which pip` and `which python`.
* The full output of `pip install --upgrade speechrecognition`.
* `python -c 'import sys; print(sys.path)'`.

We can probably figure out what the problem is from these outputs.

**Comment by sanster9292** [comment]
Hey guys thanks a lot for helping me out. Here are the requested outputs

which pip : /home/sanwal092/anaconda3/bin/pip
which python: /home/sanwal092/anaconda3/bin/python

pip install --upgrade speechrecognition:
Collecting speechrecognition
  Downloading SpeechRecognition-3.8.1-py2.py3-none-any.whl (32.8MB)
    100% |████████████████████████████████| 32.8MB 42kB/s 
Installing collected packages: speechrecognition
  Found existing installation: SpeechRecognition 3.6.1
    Uninstalling SpeechRecognition-3.6.1:
      Successfully uninstalled SpeechRecognition-3.6.1
Successfully installed speechrecognition-3.8.1

python -c 'import sys; print(sys.path)':


['', '/home/sanwal092/anaconda3/lib/python36.zip', '/home/sanwal092/anaconda3/lib/python3.6', '/home/sanwal092/anaconda3/lib/python3.6/lib-dynload', '/home/sanwal092/anaconda3/lib/python3.6/site-packages']

**Comment by Uberi** [comment]
Hmm, can you check if there's a `speech_recognition` folder in the `/home/sanwal092/anaconda3/lib/python3.6/site-packages` folder? I don't use Anaconda myself, so wouldn't be able to offer much advice having to do with its unusual packaging situation.

**Comment by sanster9292** [comment]
Sorry for the super late reply, i just checked and these 2 folders are located there 

speech_recognition
SpeechRecognition-3.8.1.dist-info

**Comment by Uberi** [comment]
Strange, that should be the correct directory structure. Can you list the contents of that `speech_recognition` directory above?

**Comment by sanster9292** [comment]
Hey guys thanks so much for your help. Here are the contents of this folder. 

flac-linux-x86     flac-mac        __init__.py  pocketsphinx-data
flac-linux-x86_64  flac-win32.exe  __main__.py  __pycache__

**Comment by Jayqianonedream** [comment]
just change the default environment settings to the anaconda environment, that works for me.

**Comment by Yashsaraf27** [comment]
> You must have multiple versions like anaconda also installed which overrides the running instances but the module is installed in the pip versions. Also if you are using pycharm : you can configure your idle through File --> settings --> Project intrepreter --> choose the intrepreter for the project. The problem is that there are multiple pip's of 2 and 3
> Like Anaconda pip itself, and then python pip2 and python pip3
> while the pip is the main thing that It might be possibility that anaconda is being overriden on all pips so for that use
> "CONDA INSTALL Speech_recognition" and then try

bro thanks I was stuck because of this problem but know I resolved it because of you

**Comment by shafaypro** [comment]
> > You must have multiple versions like anaconda also installed which overrides the running instances but the module is installed in the pip versions. Also if you are using pycharm : you can configure your idle through File --> settings --> Project intrepreter --> choose the intrepreter for the project. The problem is that there are multiple pip's of 2 and 3
> > Like Anaconda pip itself, and then python pip2 and python pip3
> > while the pip is the main thing that It might be possibility that anaconda is being overriden on all pips so for that use
> > "CONDA INSTALL Speech_recognition" and then try
> 
> bro thanks I was stuck because of this problem but know I resolved it because of you

Cheers mate.

**Comment by Alenabraham07** [comment]
That was quite helpful✌

**Comment by malhotrajagriti** [comment]
will uninstalling anaconda work in this case??
