### ISSUE TITLE
google cloud speech not returning full text

### ISSUE THREAD

**Issue by malikkamranabid** [Uberi/speech_recognition#274]
I am working on google cloud speech api i tried their api with my flac file but they are just transcripting a some part of my flac format file.Is there anything i can do with my file to make it work perfectly.I tried testing their api on their [link](https://cloud.google.com/speech/reference/rest/v1/speech/recognize#SpeechRecognitionResult).I Pass this in the request body{ "audio": { "uri": "gs://kami1994/file-1506682082651.flac" }, "config": { "encoding": "FLAC", "languageCode": "en-US" } }But it is not returning text exactly like i spoke.

**Comment by Uberi** [comment]
Hi @malikkamranabid,

There's a limit of around 1 minute of audio for the cloud speech API - if your audio is longer than that, you may get a cut-off transcription. For longer-form text, I'd recommend `recognize_ibm` or `recognize_sphinx`.

Changes with regards to this are coming soon!
