### ISSUE TITLE
Can not set another IBM api url without changing the source code

### ISSUE THREAD

**Issue by Langhalsdino** [Uberi/speech_recognition#275]
Steps to reproduce
------------------
1. Setup a watson service in a location e.g. Germany.
2. Using the default api_url will introduce a higher latency, then changing it manually to `"https://stream-fra.watsonplatform.net/speech-to-text/api"`

Expected behaviour
------------------
I expected an option to set the api url manually to lower the latency.

Please excuse the short issue report, but fixing this should be pretty much straight forward.
May be i will try to do it by my self ;D

**Comment by Uberi** [comment]
Hi @Langhalsdino,

Thanks for the report! I added a comment on #276, but for any future readers:

An alternative is to set up a local DNS CNAME or A entry to resolve the standard Watson API to the desired host. The hosts file should work for this purpose as well.
