### ISSUE TITLE
Audio must be mono

### ISSUE THREAD

**Issue by srijiths** [Uberi/speech_recognition#28]
When runnning , i am getting the error below

File "/usr/lib/python2.6/site-packages/SpeechRecognition-1.1.4-py2.6.egg/speech_recognition/__init__.py", line 74, in __enter__
    assert self.CHANNELS == 1 # audio must be mono

I confirmed that the input audio is mono.

**Comment by Uberi** [comment]
Can you upload the audio somewhere for testing purposes? I have not been able to reproduce this.

**Comment by RasJay** [comment]
https://www.dropbox.com/s/bhunw6r3ptqzjw7/Notorious%20BIG%20-%20Biggie%20-%20Dead%20Wrong%20%28Acapella%29.wav?dl=0

**Comment by RasJay** [comment]
I'm not sure how to check whether or not my Wav file is Mono or Stereo, but I'm getting the same error.

**Comment by Uberi** [comment]
Hi @RasJay,

Your file is definitely stereo:

![screenshot - 2015-04-21 - 09 26 13 pm](https://cloud.githubusercontent.com/assets/437196/7265779/351fa5f6-e86d-11e4-8d13-3eb7680e6045.png)

A future version of this library might convert the audio to mono automatically, but for now you can convert the audio to mono manually using tools like Audacity.

**Comment by kamushadenes** [comment]
Just for reference, sox original_file.wav -c1 mono_file.wav, will convert the file to mono.

Original file can be mp3 or just whatever sox recognizes.

**Comment by Uberi** [comment]
b16101acf9bce667aac0f19c1371cabc5980497e adds support for stereo audio!
