### ISSUE TITLE
Update to use v1 of Google API

### ISSUE THREAD

**Issue by nate-byrnes** [Uberi/speech_recognition#280]
Google has emailed me indicating that I have been using v1beta instead of v1 of the speech API. 

'''
We released the Generally Available (GA) version of the Cloud Speech API on April 18, 2017, and the service will be fully graduating from Cloud Speech API Beta on November 30, 2017. This is an extension of our original timeline for a July 31 transition. Our records show that you have recently been using the beta endpoint even after the prior notice. In order to continue using Cloud Speech API, you must migrate to the Cloud Speech API GA version before November 30, 2017. Google Cloud Speech API Beta endpoint will cease to function from this date.
'''

The only way I am using this endpoint is through the speech_recognition module. 

Are there plans to update this module to make use of the v1 API?

**Comment by sujitvasanth** [comment]
works fine for me....how did they identify your email?
I have signed up for loud speech api which actually doesnt seem all that better...

**Comment by nate-byrnes** [comment]
I guess I'll find out today if it will be shutdown.... They got my email as it is linked to the API key I am using...

**Comment by Uberi** [comment]
Hi @nate-byrnes,

Fortunately, @oort7 has already fixed this at the time in 3379e4ae6aa7952417b34c3b4ce42e101addb60b. I'll be putting together a new release pretty soon, but in the meantime you may want to install the latest version from GitHub.
