### ISSUE TITLE
how can I conduct Asynchronous Recognition when use recognize_google

### ISSUE THREAD

**Issue by d03849007** [Uberi/speech_recognition#283]
Steps to reproduce
------------------

Hi, I try to the code you provide to do speech recognition and it works on Synchronous Recognition, which the audio file is less than 1 minute. 

However, when I tried to conduct Asynchronous Recognition (less than 1 minute), I found the content limit in google's statement that user should provide the uri reference for file. 

This is my audio file. 
https://goo.gl/Erxgaf

My original code for transcribe is the following: 

 ```python
import speech_recognition as sr
# obtain path to "english.wav" in the same folder as this script
AUDIO_FILE = "C:\\Users\\Yi-LungChen\\Downloads\\test2.wav"
# use the audio file as the audio source
r = sr.Recognizer()
with sr.AudioFile(AUDIO_FILE) as source:
    audio = r.record(source)  # read the entire audio file
print("Google Speech Recognition thinks you said " + r.recognize_google(audio, language = 'zh-TW'))
```
System information
------------------
My **system** is <INSERT SYSTEM HERE>. ( "Windows 10 x64")

My **Python version** is <python -3.6.)

My **Pip version** is <INSERT VERSION HERE>. (9.0.1)

My **SpeechRecognition library version** is <3.7.1>. (You can check this by running `python -c "import speech_recognition as sr;print(sr.__version__)"`.)

**Comment by Uberi** [comment]
Hi @d03849007,

We don't support async recognition of that length, due to the requirement that all the files be uploaded first. A good alternative here would be `recognize_ibm` and `recognize_sphinx`, which both support the desired language.
