### ISSUE TITLE
How to send text result back to main thread when using listen_in_background?

### ISSUE THREAD

**Issue by ajbogh** [Uberi/speech_recognition#284]
I've gone through as many of the examples and issues as I could possibly find and I haven't been able to come across a good solution. I have a main class which starts the recognizer class. The recognizer listens in the background and then calls the callback function while the main class performs other tasks (starting the UI, handling config file changes, etc.). When I try to pause listening the system throws a "cannot join current thread" error. I know that this is because I'm calling `stop_listening` while it's on the child thread, but I'm unsure how to get the callback function to send data back to the main thread so that the main thread can call the `stop_listening` function instead of the child thread.

Please help me understand this. Thanks!

Steps to reproduce
------------------

Using `listen_in_background`, set a callback function to be used when the audio is recognized. Within the callback function, emit a message to another waiting class.

```
import speech_recognition as sr
from threading import Thread,current_thread
import gi
from gi.repository import GObject as gobject

class MainThreadClass:
    def __init__(self, opts):
        self.recognizer = Recognizer()
        self.recognizer.connect('finished', self.recognizer_finished)
        self.recognizer.listen()

    def self.recognizer_finished:
        print current_thread()  // Child thread
        self.recognizer.pause()

class Recognizer(gobject.GObject):
    __gsignals__ = {
        'finished' : (gobject.SIGNAL_RUN_LAST, gobject.TYPE_NONE, (gobject.TYPE_STRING,))
    }
    def __init__(self):
        self.r = sr.Recognizer()
        self.m = sr.Microphone()
        with self.m as source: 
            self.r.adjust_for_ambient_noise(source)

    def callback(self, recognizer, audio):
        try:
            text = recognizer.recognize_sphinx(audio, "en-US", self.keywords, None)
            self.emit("finished", text)
        except sr.UnknownValueError:
            print("Sphinx could not understand audio")
            self.emit("finished", '')
        except sr.RequestError as e:
            print("Sphinx error; {0}".format(e))

    def listen(self):
        print current_thread()  // Main Thread
        self.stop_listening = self.r.listen_in_background(self.m, self.callback)

    def pause(self):
        print current_thread() // Child thread
        self.stop_listening()
```

Expected behaviour
------------------

The recognizer_finished function should be in the main thread, and the call to `recognizer.pause()` should work.

Actual behaviour
----------------

Code throws a "cannot join current thread" error.

```
Say something! (listen function)
<_MainThread(MainThread, started 140642979739456)>

Got it! Now to recognize it (Callback function)...
<Thread(Thread-1, started daemon 140642575804160)>

++++++++++++++
Pausing (Pause function)
<Thread(Thread-1, started daemon 140642575804160)>
Traceback (most recent call last):
  File "./Blather.py", line 183, in recognizer_finished
    self.checkCommandFile()
  File "./Blather.py", line 201, in checkCommandFile
    self.read_commands()
  File "./Blather.py", line 114, in read_commands
    self.recognizer.pause()
  File "/mnt/Sage/Projects/blather/Recognizer.py", line 79, in pause
    self.stop_listening()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 627, in stopper
    listener_thread.join()  # block until the background thread is done, which can be up to 1 second
  File "/usr/lib/python2.7/threading.py", line 931, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

System information
------------------

My **system** is Ubuntu 17.04 x64

My **Python version** is Python 2.7.14.

My **Pip version** is pip 9.0.1 from /usr/local/lib/python2.7/dist-packages

My **SpeechRecognition library version** is 3.7.1

My **PyAudio library version** is 0.2.11

I **installed PocketSphinx from** pip.

**Comment by Uberi** [comment]
Hi @ajbogh,

`listen_in_background` will create its own thread, and you have to call `stop_listening` from the same thread as you originally called it from. That said, if you install the latest library version (301f889399772bbb9ebc41e3748032ef83e1d48a or later), you can now call `stop_listening(False)` instead of `stop_listening()`, and this will fix your issue!
