### ISSUE TITLE
Could not request results from Google Speech API - audio file processing

### ISSUE THREAD

**Issue by NenadPantelic** [Uberi/speech_recognition#285]
Hi guys,
I'm trying some things and I want to compare and analyze speech recognition services performance and their effectiveness. I'm trying to compare precision between English and Serbian. It works fine when I use my microphone as source, but when I try using wav file as source, I'm getting Could not request results from Google Speech API.... Bad Gateway. I read article about limits of Google Service - my wav file props:
15s length, less than 100 words surely. Code is fine - it is example from library - only replaced some details - language, chunk size... nothing special.

I read in source code sample rate characteristics: it is mentioned about 8kHz - 16kHz. I downloaded my file from YT - convert it and trim it. My sample rate is 48kHz and Channel is Mono. I think there might be problem with sampling and frequency characteristics. Any hint?

**Comment by jehoshua7** [comment]
@ NenadPantelic - Take a look at their API limits: https://cloud.google.com/speech/limits

I have a small .WAV file, length is 1 minute and I keep getting 

> Could not request results from Google Speech Recognition service; recognition connection failed: [Errno 32] Broken pipe

The script I was using has the Google Speech Recognition code in it.

**Comment by Uberi** [comment]
Hi @NenadPantelic,

If you can post a sample audio file, I'd be happy to take a look at what's going wrong. The sample rate will be automatically converted if it's outside of the accepted range, so that shouldn't be an issue.

**Comment by NenadPantelic** [comment]
Hi @Uberi, 
sorry for my late response, I had some things to do. Well, I solved the problem, I cannot actually remeber how :) - I think I used sox tool in Linux, instead of the ffmpeg which I used at first 
and with which I made the first file that made problems. 
Thank you for your help and interest,
Nenad

**Comment by Uberi** [comment]
Great to hear!
