### ISSUE TITLE
listen_in_background not working

### ISSUE THREAD

**Issue by Meorge** [Uberi/speech_recognition#29]
I'm trying to use the listen_in_background command to listen for a certain phrase, but when I try to run my code, it gives the following big error: http://pastebin.com/38ZtCaLc

This is my code: http://pastebin.com/re1WwJti

I'm not sure if I'm doing anything wrong or if it has to do with PyAudio/SR. Do you know?
Thanks,
Meorge

**Comment by Uberi** [comment]
Oops, that's embarrassing, it's a misnamed variable. Fix will be out in a few minutes.

**Comment by Meorge** [comment]
Ok, thanks for the quick reply! :smile:

**Comment by Uberi** [comment]
Fixed in bd592ed22a2d4f8f76e24a4a2ba7c8955024f3d1!

**Comment by Meorge** [comment]
I think it's set up correctly (actually the same as my code in the first post) but it gives one of the two errors when I try to run it:
Segmentation fault: 11
or 
Floating point exception: 8

Do you have any ideas as to what are causing these?

**Comment by Uberi** [comment]
Hi @Meorge,

That looks like a Qt or PyAudio error. Is it possible to get a core dump, or figure out exactly when it occurs? An easy way to do the latter is to insert print calls between each logical line.

**Comment by Meorge** [comment]
I tried inserting print statements, and it opened fine (printing the statements), but didn't seem to recognize the audio. I closed it, and tried to reopen it, and it printed the print statements, then crashed. From the Console I managed to get this: http://pastebin.com/7wuF3dsv

My print statements were inserted before the 'with' part, during it and after it. All three print, then it crashes

**Comment by Uberi** [comment]
First, the `listen_in_background` function is not called using an AudioSource context. Your callback `hearCool` also takes the wrong number of parameters, and uses an AudioData instance as if it was a string. Please see the third code example in the README, and check out the documentation for the relevant functionality.

Second, does the issue occur if you don't call `listen_in_background` at all?

**Comment by Meorge** [comment]
Just tried running with the `listen_in_background` stuff, it works fine.
Looking at the example again, I think I understand it better, but could you explain to me what the `m` argument is? I tried setting it to `pyaudio.PyAudio()`, but it gave another crash :\

**Comment by Uberi** [comment]
The example has been updated to clarify things a bit more, and make it work out of the box. I'll also be adding more helpful error messages in the next version.

**Comment by Meorge** [comment]
Ok, thanks - Running the updated example code directly worked, but trying to integrate it into my code raised this error: `TypeError: callback() takes 2 positional arguments but 3 were given` 
Here's the code, for reference: http://pastebin.com/g810h1uy
I'm thinking it may have something to do with the `self` stuff, but I'm not sure :\

**Comment by Uberi** [comment]
I recommend reading up on using [bound methods in Python](http://stackoverflow.com/questions/114214/class-method-differences-in-python-bound-unbound-and-static).

In short, use static method decorators for callbacks in order to avoid binding issues.
