### ISSUE TITLE
IOError: [Errno -9999] Unanticipated host error

### ISSUE THREAD

**Issue by Dinesh2903** [Uberi/speech_recognition#292]
#!/usr/bin/env python3
# Requires PyAudio and PySpeech.

import speech_recognition as sr

# Record Audio
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

# Speech recognition using Google Speech Recognition
try:
    # for testing purposes, we're just using the default API key
    # to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
    # instead of `r.recognize_google(audio)`
    print("You said: " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))

**Comment by Uberi** [comment]
Hi @Dinesh2903,

Please fully fill out the issue template - it contains important fields for diagnostic information. Feel free to re-open the issue once that's done!
