### ISSUE TITLE
Cutting up an audiofile for partial recognition

### ISSUE THREAD

**Issue by sujitvasanth** [Uberi/speech_recognition#295]
### I am using pocketsphinx to detect a wakeword ("computer") on windows 10 and then sending the same audio to google to decode. Thus saving the wasted bandwidth and payment to google! My simplified code is below

```
import speech_recognition as sr; import time

def callback(recognizer, audio):
    try: recognised=recognizer.recognize_sphinx(audio, keyword_entries=[("computer", 0.6)])
    except: return
    if "computer" in recognised: print(recognizer.recognize_google(audio))

m = sr.Microphone() ; r = sr.Recognizer()
stop_listening = r.listen_in_background(m, callback)
while True: time.sleep(1)
```

Works fine. If you say "computer, what time is it" that will send speech to google, but saying "howdy neighbor" would have no effect.

To improve processing time: Sphinx only actually needs access to the first half second of of audio and ideally the last half second to take account of the possibility "what time is it, computer!".
Please tell me how i can chop the audio to include the beginning x millisenonds or end y milliseconds or if there is a better solution to do this. (there's no snowboy for windows yet)

also I have set 2 separate recognition tasks - can the functions be combined to save more processing time? i.e. by doing sample rate conversion just once.

also what sample rate and chunk size is native to sphinx/google for performance opimization?

thanks

Sujit Vasanth

**Comment by Uberi** [comment]
Hi @sujitvasanth,

I'll be adding an `audio.get_segment` function in the next release, but for now you can do the following:

```python
def get_segment(audio, start_ms = None, end_ms = None):
    assert start_ms is None or start_ms > 0, "``start_ms`` must be a positive number"
    assert end_ms is None or end_ms > 0, "``end_ms`` must be a positive number"
    if start_ms is None:
        start_byte = 0
    else:
        start_byte = int((start_ms * audio.sample_rate * audio.sample_width) // 1000)
    if end_ms is None:
        end_byte = len(audio.frame_data)
    else:
        end_byte = int((end_ms * audio.sample_rate * audio.sample_width) // 1000)
    return sr.AudioData(audio.frame_data[start_byte:end_byte], audio.sample_rate, audio.sample_width)

import speech_recognition as sr; import time

def callback(recognizer, audio):
    trimmed_audio = get_segment(audio, end_ms=1000)  # get the first second of audio
    try: recognised=recognizer.recognize_sphinx(trimmed_audio, keyword_entries=[("computer", 0.6)])
    except: return
    if "computer" in recognised: print(recognizer.recognize_google(audio))

m = sr.Microphone() ; r = sr.Recognizer()
stop_listening = r.listen_in_background(m, callback)
while True: time.sleep(1)
```

Eventually we hope to have streaming support, which would make wake words a lot more feasible.

For Sphinx, we use 16kHz, 16-bit PCM audio. Google's API uses at least 8kHz and 16-bit FLAC audio. Rate conversion is essentially free, so you generally won't be incurring any noticeable latency from leaving the sample rates/widths as-is.
