### ISSUE TITLE
Basic Example not working

### ISSUE THREAD

**Issue by faxe1008** [Uberi/speech_recognition#298]
Steps to reproduce
------------------

I ran the basic example using Google API Recognition but I don't get any form of reaction.

My System is Win10 Enterprise x64 bit

My **Python version** is 3.6. (You can check this by running `python -V`.)

My **SpeechRecognition library version** is 3.7.1 (You can check this by running `python -c "import speech_recognition as sr;print(sr.__version__)"`.)

My **PyAudio library version** is 0.2.11 / I don't have PyAudio installed. (You can check this by running `python -c "import pyaudio as p;print(p.__version__)"`.)

I ran pyAudio to get all devices and tested 0 and 1:
```
{'index': 0, 'structVersion': 2, 'name': 'Microsoft Soundmapper - Input', 'hostApi': 0, 'maxInputChannels': 2, 'maxOutputChannels': 0, 'defaultLowInputLatency': 0.09, 'defaultLowOutputLatency': 0.09, 'defaultHighInputLatency': 0.18, 'defaultHighOutputLatency': 0.18, 'defaultSampleRate': 44100.0}
{'index': 1, 'structVersion': 2, 'name': 'Microphone Array (Realtek Audio', 'hostApi': 0, 'maxInputChannels': 2, 'maxOutputChannels': 0, 'defaultLowInputLatency': 0.09, 'defaultLowOutputLatency': 0.09, 'defaultHighInputLatency': 0.18, 'defaultHighOutputLatency': 0.18, 'defaultSampleRate': 44100.0}
{'index': 2, 'structVersion': 2, 'name': 'Microsoft Soundmapper - Output', 'hostApi': 0, 'maxInputChannels': 0, 'maxOutputChannels': 2, 'defaultLowInputLatency': 0.09, 'defaultLowOutputLatency': 0.09, 'defaultHighInputLatency': 0.18, 'defaultHighOutputLatency': 0.18, 'defaultSampleRate': 44100.0}
{'index': 3, 'structVersion': 2, 'name': 'Lautsprecher / Kopfhörer (Realt', 'hostApi': 0, 'maxInputChannels': 0, 'maxOutputChannels': 2, 'defaultLowInputLatency': 0.09, 'defaultLowOutputLatency': 0.09, 'defaultHighInputLatency': 0.18, 'defaultHighOutputLatency': 0.18, 'defaultSampleRate': 44100.0}

```

**Comment by Uberi** [comment]
Hi @faxe1008,

By no reaction, do you mean the script gets stuck on `Say something!`?

If so, that means the issue is likely choosing the correct microphone input. One thing you can try is running [this example](https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py) but with `sr.Microphone()` replaced with `sr.Microphone(device_index=1)`, since index 1 seems to be your primary microphone.

**Comment by bindhushree** [comment]
Hello @Uberi 

Im also facing the same issue while running basic example using Google API Recognition.
Im getting below console error:
**A moment of silence, please...
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\speech_recognition\__main__.py", line 8, in
<module>
    with m as source: r.adjust_for_ambient_noise(source)
  File "D:\Python\lib\site-packages\speech_recognition\__init__.py", line 532, i
n adjust_for_ambient_noise
    buffer = source.stream.read(source.CHUNK)
  File "D:\Python\lib\site-packages\speech_recognition\__init__.py", line 190, i
n read
    return self.pyaudio_stream.read(size, exception_on_overflow=False)
  File "D:\Python\lib\site-packages\pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9988] Stream closed**

My System is Win 7 Professional.
My Python version is 3.6.3.
My SpeechRecognition library version is 3.8.1.
My PyAudio library version is 3.8.1.
My Audio devices are(I tested with default audio device):
Microphone with name "Microsoft Sound Mapper - Input" found for `Microphone(devi
ce_index=0)`
Microphone with name "Microphone (High Definition Aud" found for `Microphone(dev
ice_index=1)`
Microphone with name "Microsoft Sound Mapper - Output" found for `Microphone(dev
ice_index=2)`
Microphone with name "Speakers (High Definition Audio" found for `Microphone(dev
ice_index=3)`

**Comment by Uberi** [comment]
Hi @bindhushree,

Try running your code with `sr.Microphone(device_index=1)`.

**Comment by desliem** [comment]
Thank you very much for this,  the only working example I have found of multilingual use of Pocket Sphinx.

I have run into a problem when using the current version from GitHub whenever `r.listen(source)` is invoked.

```
Say something!
Traceback (most recent call last):
  File "write_audio.py", line 19, in <module>
    audio = r.listen(source)
  File "/home/michel/Development/python/speech_recognition/lib/python3.6/site-packages/speech_recognition/__init__.py", line 657, in listen
    buffer = source.stream.read(source.CHUNK)
  File "/home/michel/Development/python/speech_recognition/lib/python3.6/site-packages/speech_recognition/__init__.py", line 198, in read
    return self.pyaudio_stream.read(size, exception_on_overflow=False)
  File "/home/michel/Development/python/speech_recognition/lib/python3.6/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9988] Stream closed
```
I tried all valid indices in `sr.Microphone(device_index=xx)` (xx = 2, 10 and 12
as explained below) without success.

When I replaced
   lib/python3.6/site-packages/speech_recognition/__init__.py
with the script found in the PyPi version of Speech Recognition, uploaded 2017-12-05 (also identified as version 3.8.1), everything works. 

I am sorry, I cannot help any further, I know next to nothing about Python. 

Again, thank you Mr. Zhang for this great library.

**System information**
My system is Ubuntu 17.10
My Python version is 3.6.3
My SpeechRecognition library version is 3.8.1. 
My PyAudio library version is 0.2.11
My microphones are: 
```
	Microphone with name "HDA Intel PCH: 92HD66C3/65 Analog (hw:0,0)" found for `Microphone(device_index=0)`
	Microphone with name "HDA Intel PCH: 92HD66C3/65 Alt Analog (hw:0,2)" found for `Microphone(device_index=1)`
(x)	Microphone with name "Logitech USB Headset: Audio (hw:1,0)" found for `Microphone(device_index=2)`     
	Microphone with name "HDA NVidia: HDMI 0 (hw:2,3)" found for `Microphone(device_index=3)`
	Microphone with name "HDA NVidia: HDMI 1 (hw:2,7)" found for `Microphone(device_index=4)`
	Microphone with name "sysdefault" found for `Microphone(device_index=5)`
	Microphone with name "front" found for `Microphone(device_index=6)`
	Microphone with name "surround40" found for `Microphone(device_index=7)`
	Microphone with name "surround51" found for `Microphone(device_index=8)`
	Microphone with name "surround71" found for `Microphone(device_index=9)`
(x)	Microphone with name "pulse" found for `Microphone(device_index=10)`   
	Microphone with name "dmix" found for `Microphone(device_index=11)`
(x)	Microphone with name "default" found for `Microphone(device_index=12)` 

(x) = working microphones with 2015-12-05 version from PyPi 

```

**Comment by desliem** [comment]
Hi, again

Looks like the problem was introduced on Monday (so it would not be the same as @faxe1008  which is 9 days old.)

```
commit c932096e3bcd9759ab7f9a9634d513f9a1173cfb (HEAD -> master)
Merge: 376153b b5b6197
Author: Anthony Zhang <me@anthonyz.ca>
Date:   Mon Dec 11 14:07:07 2017 -0500

    Merge pull request #304 from dcam0050/patch-1
    
    Update to speechContext formatting for recognize_google_cloud
```
Everything seems to work up to and including the Dec 10th commit. 

Hope that helps. Cheers.
