### ISSUE TITLE
Latest code is failing for me

### ISSUE THREAD

**Issue by kevinismith** [Uberi/speech_recognition#30]
When I back out the latest changes it works fine. but with the latest change it fails with the following error:

  File "/usr/local/lib/python2.7/dist-packages/SpeechRecognition-1.2.3-py2.7.egg/speech_recognition/__init__.py", line 137, in samples_to_flac
    with wave.open(wav_file, "wb") as wav_writer:
AttributeError: Wave_write instance has no attribute '__exit__'

**Comment by kmkroski** [comment]
Same here. OSX

**Comment by Uberi** [comment]
Looks like the latest version broke Python 2 compatibility somehow, I'll look into it.

**Comment by Uberi** [comment]
Fixed in ac9cd56c0b167bc36614872f8ef6ebbc07e0a804!
