### ISSUE TITLE
difference between Google speech recognition and Google cloud speech API?

### ISSUE THREAD

**Issue by HareIam** [Uberi/speech_recognition#302]
Ask a simple question here.

what is the difference between these two recognition methods from google?
 
1. Google Speech Recognition
2. Google Cloud Speech API

Thanks

**Comment by jhoelzl** [comment]
The first one is free, but nobody knows when Google turns the service off...
The second one is not free and requires a Google cloud console account with an active subscription of Speech API.

**Comment by HareIam** [comment]
Firstly, Thanks for your reply @jhoelzl .

Here is some of my finding. Can someone tell me it is correct or not?

The Google Speech Recognition is using Chrome Speech API, which is the first version of google speech api (version beta1?). The second Google Cloud Speech API is the newest version of Google (version 1?).

Thanks!
XU SHIHAO

**Comment by jhoelzl** [comment]
Yes, your findings are correct.

I also made a few tests comparing the two services, the cloud speech API provides fewer latency, but i could not find significant differences in the speech recognition performance (in regards to wprd error rate).

**Comment by HareIam** [comment]
Haha, yeah. It is true, the word error rates are almost same. 

It is said that a new version of speech engine embedded to Google pixel 2. Do you have idea what it is? Is it same as Google Cloud Speech API we used?

Thanks
