### ISSUE TITLE
[Errno -9998] Invalid number of channels or Sampling rate

### ISSUE THREAD

**Issue by ash-lat** [Uberi/speech_recognition#307]
**Hi 

I tried using the library to detect and help me record a .wav file from a USB soundcard mic
First I treid running the below code:**

`import speech_recognition as sr

# obtain audio from the microphone
r = sr.Recognizer()
with sr.Microphone(2,1,44100) as source:
    print("Say something!")
    audio = r.listen(source)

# write audio to a WAV file
with open("/home/jay/Desktop/deepspeech_v0.3/mi.wav", "wb") as f:
    f.write(audio.get_wav_data())
`

**And its giving error "invalid sample rate":**

Traceback (most recent call last):
  File "m1.py", line 6, in <module>
    with sr.Microphone(2,1,44100) as source:
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 141, in __enter__
    input=True,  # stream is an input stream
  File "build/bdist.linux-x86_64/egg/pyaudio.py", line 750, in open
    
  File "build/bdist.linux-x86_64/egg/pyaudio.py", line 441, in __init__
    # calling pa.open returns a stream object
IOError: [Errno -9997] Invalid sample rate

**When I define 
Microphone(device_index=2, sample_rate=44100)
It giving error saying "invalid number of channels":**

Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
Traceback (most recent call last):
  File "m1.py", line 6, in <module>
    with sr.Microphone(2,44100) as source:
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 141, in __enter__
    input=True,  # stream is an input stream
  File "build/bdist.linux-x86_64/egg/pyaudio.py", line 750, in open
    
  File "build/bdist.linux-x86_64/egg/pyaudio.py", line 441, in __init__
    # calling pa.open returns a stream object
IOError: [Errno -9998] Invalid number of channels

**when I try to define channels=1
Microphone(device_index=2, channels=1, sample_rate=44100)
it says argument "channels" is invalid**

**Below is the mic discovery code for debugging:**

[{'defaultSampleRate': 44100.0, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultLowInputLatency': -1.0, 'maxInputChannels': 0L, 'structVersion': 2L, 'hostApi': 0L, 'index': 0, 'defaultHighOutputLatency': 0.034829931972789115, 'maxOutputChannels': 8L, 'name': u'HDA Intel HDMI: 0 (hw:0,3)', 'defaultHighInputLatency': -1.0}, {'defaultSampleRate': 44100.0, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultLowInputLatency': -1.0, 'maxInputChannels': 0L, 'structVersion': 2L, 'hostApi': 0L, 'index': 1, 'defaultHighOutputLatency': 0.034829931972789115, 'maxOutputChannels': 8L, 'name': u'HDA Intel HDMI: 1 (hw:0,7)', 'defaultHighInputLatency': -1.0}, {'defaultSampleRate': 44100.0, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultLowInputLatency': -1.0, 'maxInputChannels': 0L, 'structVersion': 2L, 'hostApi': 0L, 'index': 2, 'defaultHighOutputLatency': 0.034829931972789115, 'maxOutputChannels': 8L, 'name': u'HDA Intel HDMI: 2 (hw:0,8)', 'defaultHighInputLatency': -1.0}, {'defaultSampleRate': 44100.0, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultLowInputLatency': 0.008707482993197279, 'maxInputChannels': 2L, 'structVersion': 2L, 'hostApi': 0L, 'index': 3, 'defaultHighOutputLatency': 0.034829931972789115, 'maxOutputChannels': 2L, 'name': u'HDA Intel PCH: CX20757 Analog (hw:1,0)', 'defaultHighInputLatency': 0.034829931972789115}, **{'defaultSampleRate': 44100.0, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultLowInputLatency': -1.0, 'maxInputChannels': 0L, 'structVersion': 2L, 'hostApi': 0L, 'index': 4, 'defaultHighOutputLatency': 0.034829931972789115, 'maxOutputChannels': 2L, 'name': u'USB Audio Device: - (hw:2,0)', 'defaultHighInputLatency': -1.0}**, {'defaultSampleRate': 44100.0, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultLowInputLatency': -1.0, 'maxInputChannels': 0L, 'structVersion': 2L, 'hostApi': 0L, 'index': 5, 'defaultHighOutputLatency': 0.034829931972789115, 'maxOutputChannels': 8L, 'name': u'hdmi', 'defaultHighInputLatency': -1.0}, {'defaultSampleRate': 44100.0, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultLowInputLatency': 0.008707482993197279, 'maxInputChannels': 32L, 'structVersion': 2L, 'hostApi': 0L, 'index': 6, 'defaultHighOutputLatency': 0.034829931972789115, 'maxOutputChannels': 32L, 'name': u'pulse', 'defaultHighInputLatency': 0.034829931972789115}, {'defaultSampleRate': 44100.0, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultLowInputLatency': 0.008707482993197279, 'maxInputChannels': 32L, 'structVersion': 2L, 'hostApi': 0L, 'index': 7, 'defaultHighOutputLatency': 0.034829931972789115, 'maxOutputChannels': 32L, 'name': u'default', 'defaultHighInputLatency': 0.034829931972789115}]

System information:

System <MINT 18.3>. 
Python<tried with 2.7 & 3.5>.
SpeechRecognition library  is <3.8.1>.
PyAudio library version is <0.2.11> 
working microphones: 
[u'HDA Intel HDMI: 0 (hw:0,3)', u'HDA Intel HDMI: 1 (hw:0,7)', u'HDA Intel HDMI: 2 (hw:0,8)', u'HDA Intel PCH: CX20757 Analog (hw:1,0)', u'USB Audio Device: - (hw:2,0)', u'hdmi', u'pulse', u'default']

**Comment by ash-lat** [comment]
Solved it using Sox 
thanks

**Comment by HimanshuMahto** [comment]
> Solved it using Sox thanks

how to do that can you please tell me. I'm still not able to solve this issue
