### ISSUE TITLE
Dynamic energy_threshold

### ISSUE THREAD

**Issue by kevinismith** [Uberi/speech_recognition#31]
I found that a static energy_threshold wasn't working well for me. I changed it to dynamically adjust to the ambient noise level. 
self.energy_threshold = self.energy_threshold * .9 + (energy * 1.05) * .1

This slowly trends toward an energy threshold of 1.05 the ambient noise. It works pretty well for me. I'm happy to provide my code if you think it would be useful / accepted.

**Comment by Uberi** [comment]
That's an excellent idea. If you don't mind, please submit a [pull request](https://github.com/Uberi/speech_recognition/pulls) to kick off the process.

**Comment by Uberi** [comment]
Implemented in #32, documentation required. Milestone for 1.3.
