### ISSUE TITLE
Can this script be installed on AWS EC2-instance?

### ISSUE THREAD

**Issue by inglesuniversal** [Uberi/speech_recognition#316]
Also, can it be accessed through google chrome PC/MAC and within a react-native app (iOS and Android) ?

Thanks

Hugo Barbosa

**Comment by palikar** [comment]
Hi @inglesuniversal ,

the library can be ran on any system that has python (preferably python3+) and Internet connection (for the most of the APIs). How you call the python scripts implementing some speech recognition functionality is up to you. 

Closing the issue for now as the question really not library related.
