### ISSUE TITLE
Unable to convert speech to text

### ISSUE THREAD

**Issue by PhoduCoder** [Uberi/speech_recognition#320]
Steps to reproduce
------------------
Run this command and then utter "Hello World" in the microphone.
This happens everytime.

I had modified the code to actually print the statement that was spoken.
--------------------
import speech_recognition as sr
#Obtain audio from microphone
r = sr.Recognizer()

with sr.Microphone() as source:
    print ("Say something!")
    audio = r.listen(source)

try:
    print("You said " + r.recognize(audio))    # recognize speech using Google Speech Recognition
except LookupError:                            # speech is unintelligible
    print("Could not understand audio")
------------------

Expected behaviour : Should print the text back
------------------

Actual behaviour: Throwing an exception. Below is the stacktrace.
Say something!
Traceback (most recent call last):
  File "microphone.py", line 11, in <module>
    print("You said " + r.recognize(audio))    # recognize speech using Google Speech Recognition
AttributeError: 'Recognizer' object has no attribute 'recognize'

System information
------------------
My **system** is macOS Sierra. 

My **Python version** is 2.7. 
My **Pip version** is pip 9.0.1. 
My **SpeechRecognition library version** is 3.8.1. 

My **PyAudio library version** is 0.2.11 
My **microphones** are: [u'Built-in Microphone', u'Built-in Output']
---------------------

**Comment by jhoelzl** [comment]
Use `r.recognize_google(audio))` instead of `r.recognize(audio))`.
