### ISSUE TITLE
while running command-git push heroku master i am getting this error    src/_portaudiomodule.c:29:23: fatal error: portaudio.h: No such file or directory error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by rahul6612** [Uberi/speech_recognition#322]
Running setup.py install for PyAudio: started
remote:            Running setup.py install for PyAudio: finished with status 'error'
remote:            Complete output from command /app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r6mmbar0/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-y7x3fzd1-record/install-record.txt --single-version-externally-managed --compile:
remote:            running install
remote:            running build
remote:            running build_py
remote:            creating build
remote:            creating build/lib.linux-x86_64-3.6
remote:            copying src/pyaudio.py -> build/lib.linux-x86_64-3.6
remote:            running build_ext
remote:            building '_portaudio' extension
remote:            creating build/temp.linux-x86_64-3.6
remote:            creating build/temp.linux-x86_64-3.6/src
remote:            gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/app/.heroku/python/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
remote:            src/_portaudiomodule.c:29:23: fatal error: portaudio.h: No such file or directory
remote:            compilation terminated.
remote:            error: command 'gcc' failed with exit status 1
remote:
remote:            ----------------------------------------
remote:        Command "/app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r6mmbar0/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-y7x3fzd1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-r6mmbar0/PyAudio/
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to shoppingwave.
remote:
To https://git.heroku.com/shoppingwave.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shoppingwave.git'

**Comment by adrianlievano** [comment]
Hi Raul - did you ever solve this problem?

**Comment by rahul6612** [comment]
yes i wasted lots of time to install different different versions of  portaudiomodule but did't work.
In last i remove all the pyaudio related folders from the Script folder(where you installed python).
then it works.
**removed files--**
_PyAudio-0.2.9.dist-info
PyAudio-0.2.11.dist-info
pypiwin32_system32
pypiwin32-220.dist-info
pypiwin32-223.dist-info
pywin32_system32
pywin32-223.dist-info
pywin32-223-py3.6.egg-info
pyaudio.py
pypiwin32.pth
pypiwin32.version.txt
PyWin32.chm
pywin32.pth
pywin32.version.txt_
