### ISSUE TITLE
while running command-git push heroku master i am getting this error    src/_portaudiomodule.c:29:23: fatal error: portaudio.h: No such file or directory error: command 'gcc' failed with exit status 1 my os is windows 10 please help me

### ISSUE THREAD

**Issue by rahul6612** [Uberi/speech_recognition#323]
Running setup.py install for PyAudio: started
remote:            Running setup.py install for PyAudio: finished with status 'error'
remote:            Complete output from command /app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r6mmbar0/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-y7x3fzd1-record/install-record.txt --single-version-externally-managed --compile:
remote:            running install
remote:            running build
remote:            running build_py
remote:            creating build
remote:            creating build/lib.linux-x86_64-3.6
remote:            copying src/pyaudio.py -> build/lib.linux-x86_64-3.6
remote:            running build_ext
remote:            building '_portaudio' extension
remote:            creating build/temp.linux-x86_64-3.6
remote:            creating build/temp.linux-x86_64-3.6/src
remote:            gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/app/.heroku/python/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
remote:            src/_portaudiomodule.c:29:23: fatal error: portaudio.h: No such file or directory
remote:            compilation terminated.
remote:            error: command 'gcc' failed with exit status 1
remote:
remote:            ----------------------------------------
remote:        Command "/app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r6mmbar0/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-y7x3fzd1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-r6mmbar0/PyAudio/
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to shoppingwave.
remote:
To https://git.heroku.com/shoppingwave.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shoppingwave.git'

**Comment by palikar** [comment]
It seems that you don't have pulseaudio on your remote server. Please follow the installation guide and the requirements (you can find both in the README) in order to install and run everything.

**Comment by maheshk76** [comment]
> It seems that you don't have pulseaudio on your remote server. Please follow the installation guide and the requirements (you can find both in the README) in order to install and run everything.

from where i have to read README file

**Comment by rlarin** [comment]
Hi, try running this command in your console `heroku run pip install PyAudio`
