### ISSUE TITLE
Pronunciation Evaluation

### ISSUE THREAD

**Issue by easyash** [Uberi/speech_recognition#328]
Hi,

Is there a function in this library to compare pronunciation of a given word and check how close it is to the ground truth.  
This will be immense help to have if it is there.

Regards,
Ash

**Comment by palikar** [comment]
@easyash ,

not really. The library focuses on bringing different speech_recognition APIs together. It is not meant to some kind of "research" in speech recognition. For this purpose you'll need something heavier.
