### ISSUE TITLE
snowboy does not work

### ISSUE THREAD

**Issue by zhujisheng** [Uberi/speech_recognition#329]
I run the snowboy, "python3 demo.py resources/models/snowboy.umdlresources/models/snowboy.umdl", it works fine.
I run a simple stt program using Microsoft Bing, It works fine also.

But, when I changed the listen func, from:
audio = r.listen(source)
to:
audio = r.listen(source,snowboy_configuration=("/home/pi/mywork/snowboy-master/examples/Python3",["/home/pi/mywork/snowboy-master/examples/Python3/resources/models/snowboy.umdl"]))
It halt on the listen func, not go on even I said the right hot word.
 
When I press the Ctrl+C, it shows:
Say something!
^CTraceback (most recent call last):
  File "simple.py", line 12, in <module>
    audio = r.listen(source,snowboy_configuration=("/home/pi/mywork/snowboy-master/examples/Python3",["/home/pi/mywork/snowboy-master/examples/Python3/resources/models/snowboy.umdl"]))
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 638, in listen
    buffer, delta_time = self.snowboy_wait_for_hot_word(snowboy_location, snowboy_hot_word_files, source, timeout)
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 573, in snowboy_wait_for_hot_word
    snowboy_result = detector.RunDetection(b"".join(resampled_frames))
  File "/home/pi/mywork/snowboy-master/examples/Python3/snowboydetect.py", line 116, in RunDetection
    return _snowboydetect.SnowboyDetect_RunDetection(self, *args)
KeyboardInterrupt

The code I try:
```python
import speech_recognition as sr

# obtain audio from the microphone
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    #audio = r.listen(source)
    audio = r.listen(source,snowboy_configuration=("/home/pi/mywork/snowboy-master/examples/Python3",["/home/pi/mywork/snowboy-master/examples/Python3/resources/models/snowboy.umdl"]))

print("recognize begin")

# recognize speech using Microsoft Bing Voice Recognition
BING_KEY = "xxxxxxxxxxxxxxxxxxxxxxx"  # Microsoft Bing Voice Recognition API keys 32-character lowercase hexadecimal strings
try:
    print("Microsoft Bing Voice Recognition thinks you said " + r.recognize_bing(audio, key=BING_KEY, language="zh-CN"))
except sr.UnknownValueError:
    print("Microsoft Bing Voice Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Microsoft Bing Voice Recognition service; {0}".format(e))

```

**Comment by ppirrip** [comment]
After a few try and your note (I forgot the "snowboy_configuration") it seems working for me now (Ubuntu 16.04) A bit unstable but is response.

---------------
import speech_recognition as sr

r = sr.Recognizer()
m = sr.Microphone()

try:
    print("A moment of silence, please...")
    with m as source: r.adjust_for_ambient_noise(source)
    print("Set minimum energy threshold to {}".format(r.energy_threshold))
    pmdl = ['../kws_models/Stop.pmdl']
    sbLoc = '../local/lib/python2.7/site-packages/snowboy-1.3.0-py2.7.egg/snowboy/'
    sbCfg = (sbLoc,pmdl)

    while True:
        print("Say something!")
        with m as source: audio = r.listen(source,snowboy_configuration=sbCfg)
        print("Got it! Now to recognize it...")
        try:
            # recognize speech using Google Speech Recognition
            value = r.recognize_google(audio)

            # we need some special handling here to correctly print unicode characters to standard output
            if str is bytes:  # this version of Python uses bytes for strings (Python 2)
                print(u"You said {}".format(value).encode("utf-8"))
            else:  # this version of Python uses unicode for strings (Python 3+)
                print("You said {}".format(value))
        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except sr.RequestError as e:
            print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
except KeyboardInterrupt:
    pass

**Comment by palikar** [comment]
Hi @zhujisheng,

do you still have the problem or have you managed to get it to work? Your code looks OK. Maybe you can try adjusting your microphone's gain or downloading some other snowboy model. I've found that the Alexa one works pretty good.

**Comment by furqanahmedmtbc** [comment]
I'm still facing this issue. I did some digging around. Looks like the scrip is stuck on 
`snowboy_result = detector.RunDetection(b"".join(resampled_frames))` 
in the speech recognition init file. The "snowboy_result" value remains 0 even after speaking into the mic multiple times.

**Comment by zhujisheng** [comment]
I solved the problem.
Just change
`snowboy_result = detector.RunDetection(b"".join(resampled_frames))`
to:
`snowboy_result = detector.RunDetection(resampled_buffer)`
It's the misusing of the snowboy: you should input the new voice data into detector each time, instead of the whole 5s voice.

If you are on Pi, because of the misusing, there will be much loss when reading the microphone.
If you are on a powerful PC, it may succeed even in the situation of misusing.

You can also delete the code about `resampled_frames`, because it has no more using.
@palikar @furqanahmedmtbc

**Comment by achen88** [comment]
@zhujisheng thank you for this fix, was running on a Pi and found it strange that the snowboy speech recognition worked on my computer but not the Pi. If the above line is correct in your last comment, should we make a pull request?

**Comment by zhujisheng** [comment]
sorry, it's so long ago...

The snowboy is deprecated,  and I have not trace the status of the speech_recognition for long time...

You can try the this on your pi yourself, or you can make a PR.
