### ISSUE TITLE
Google Speech API v2 access control

### ISSUE THREAD

**Issue by legend0011** [Uberi/speech_recognition#34]
I would like to use Google Speech API v2 to generate asr(auto speech recognition) result for .wav files for experiment use.

I make some changes to your project, And I apply for my own API key, and I can only access the API for about 500 times a day.

Do you know how to make 5000 or more request(access to the API)? Or how google block us??

Thanks very much !!!

**Comment by Uberi** [comment]
Hi @legend0011,

You can try requesting more via the Google Developers API console. The form is not available to everyone, though - I think you have to be a Chromium developer.

Alternatively, the default key that ships with the library does not have any limits on it that I am aware of. However, this is only intended for personal/development use.
