### ISSUE TITLE
How can I set a duration for the listen_in_background method

### ISSUE THREAD

**Issue by chefboyrc9** [Uberi/speech_recognition#35]
It would be nice to set a duration for the listen_in_background method. If it listens to a long winded speaker who doesn't stop talking for minutes, it waits until there is no audio before recognizing the audio. It would be nice to process this in smaller chunks. For example,start a new record process for 10 seconds, then send that to recognize while another record process starts, and so on...

**Comment by Uberi** [comment]
Hi @chefboyrc9,

The issue with chunking the input audio is that you get cut off audio near the boundaries of the chunks. For example, if the audio is cut off in the middle of a word, then that word will not be properly recognized.

**Comment by Uberi** [comment]
This is now possible by using the listener thread functionality. Simply manage the multiple background listeners in the main thread, and stop or start them as necessary.
