### ISSUE TITLE
Google speech recognition issue 

### ISSUE THREAD

**Issue by gagana-hg** [Uberi/speech_recognition#360]
Hi ,
@Uberi 
I had two query to ask.
1.How can I use this Speech to Text API without external microphone. I want to use laptop built-in microphone.
2.When I start speaking the listen() only listen for 2 sec instead of 10 sec.
Can you help me with these two issues ASAP

**Comment by zenogantner** [comment]
I think you should put those into 2 separate issues.

(1) should just work. Can you tell us more about your setup?

**Comment by Uberi** [comment]
1. Check out the [documentation for the `Microphone` class](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#microphonedevice_index-unionint-none--none-sample_rate-int--16000-chunk_size-int--1024---microphone).
2. You likely need to adjust the threshold settings. See [`adjust_for_ambient_noise` documentation](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instanceadjust_for_ambient_noisesource-audiosource-duration-float--1---none).

Please feel free to re-open this if you are still having these issues! I highly recommend filling in the issue template as well.
