### ISSUE TITLE
Accuracy in Google Cloud Speech API

### ISSUE THREAD

**Issue by Tritrita** [Uberi/speech_recognition#364]
Hi

I am trying to transcribe an audio file to Text,but I am not getting accurate results using Google Cloud Speech API.

The audio is about 26 seconds.

Is it like the trial version of GoogleCloud Speech API provides only less accuracy than the subscribed version of GoogleCloud Speech API

How may I get the audio converted text to be more accurate using Google Cloud Speech API.

Thanks in advance,

**Comment by Zeeshan75** [comment]
You may use google docs then select the tools option then select voice typing u can get it there.

**Comment by palikar** [comment]
Hi @Tritrita,

I cannot really help you with this one. The library offers just easy way of interacting with different APIs. Speech recognition can be tricky at times and there is no perfect API. As you said, GoogleCloud Speech API is a free (kinda) one so I would assume that the quality of the service isn't "state of  the art". Also, the API is pretty limited so there is nothing that one can do to increase the accuracy. I guess you can try using another API.
