### ISSUE TITLE
Proper Documentation

### ISSUE THREAD

**Issue by akhilkathi97** [Uberi/speech_recognition#373]
Is there any proper documentation for useage  of the Speech Recognition API in python or any other language.

**Comment by rotsix** [comment]
Hi, you can see [here](https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst).

@Uberi links are broken in the bash script, may you fix them? Thanks :)

**Comment by Uberi** [comment]
Thanks @rotsix, fixed in https://github.com/Uberi/speech_recognition/commit/8740a7a82113bce0061f2cec695964d4d353e235#diff-63393b57b9443fc6a633707573fd22bb.
