### ISSUE TITLE
Does not stop recording in speech recognition python

### ISSUE THREAD

**Issue by darkcoderrises** [Uberi/speech_recognition#38]
I was trying the example code for the first time

import speech_recognition as sr
r = sr.Recognizer(language = "en-US"  )
r.pause_threshold = 0.6 
with sr.Microphone() as source:    
    audio = r.adjust_for_ambient_noise(source)
    print "Speak Now"
    audio = r.listen(source, timeout=1)                   # listen for the first phrase and extract it into audio data

try:
    print("You said " + r.recognize(audio))    # recognize speech using Google Speech Recognition
except LookupError:                            # speech is unintelligible
    print("Could not understand audio")
except IndexError:
    print("No internet")
except KeyError:
    print("quota maxed out")
But i am getting this

ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib dlmisc.c:252:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_equal.so
ALSA lib dlmisc.c:252:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_equal.so
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Speak now
and it is then struck there only

What should i do?

**Comment by Uberi** [comment]
Try the instructions mentioned [here](http://askubuntu.com/questions/557906/problem-starting-jack-server-jack-server-is-not-running-or-cannot-be-started) - it seems like it might be necessary to restart the services.

**Comment by darkcoderrises** [comment]
No effect

**Comment by Uberi** [comment]
Do any other PyAudio examples work? Are you able to capture audio using programs like `arecord`?

**Comment by darkcoderrises** [comment]
yes, transcribing a WAV audio file was working. I am also able to capture audio using arecord

**Comment by Uberi** [comment]
Try out the new [troubleshooting guide](https://github.com/Uberi/speech_recognition#user-content-on-ubuntudebian-i-get-errors-like-jack-server-is-not-running-or-cannot-be-started-or-cannot-lock-down--byte-memory-area-cannot-allocate-memory). Feel free to re-open if this doesn't work.

**Comment by darkcoderrises** [comment]
It worked twice after that. But stopped again.
This time i tried putting a print statement like this:-
with sr.Microphone() as source:                
    print "Start"
    audio = r.listen(source)
    print "Done"
But even Start was not printed

**Comment by Uberi** [comment]
What is the new error? Does it work again if you repeat the process?

**Comment by darkcoderrises** [comment]
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib dlmisc.c:252:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_equal.so
ALSA lib dlmisc.c:252:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_equal.so
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave

**Comment by darkcoderrises** [comment]
It worked, thanks a lot

**Comment by Mantej-Singh** [comment]
add,
phrase_time_limit=10// 10 seconds
eg:

    with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source,timeout=1,phrase_time_limit=10)
