### ISSUE TITLE
flac-linux-i386 doesn't seem working on OSX

### ISSUE THREAD

**Issue by chaoming** [Uberi/speech_recognition#40]
It is supposed to work on OSX or just Linux?

**Comment by chaoming** [comment]
Ok, it is not supposed to work on OSX.

Someone managed to make it work on OSX. Here are the details:
http://l34rn-p14y.blogspot.com.au/2014/11/python-speech-recognition-for-mac-os-x.html

**Comment by DelightRun** [comment]
You should use flac's mac version:

`brew install flac`

And You can have a look at my [PyBaiduYuyin](https://github.com/DelightRun/PyBaiduYuyin) project, it contains a `flac-mac` which you can download and use.

**Comment by Uberi** [comment]
Thanks to DelightRun, we now have built in OS X support! That means you should be able to use the library on OS X out of the box.
