### ISSUE TITLE
You need to install sth else before installing sphinx

### ISSUE THREAD

**Issue by sniperwrb** [Uberi/speech_recognition#402]
You need: "apt-get install libasound2-dev" before "pip install pocketsphinx".
Other wise you will get "fatal error: alsa/asoundlib.h: No such file or directory".

Steps to reproduce
------------------
Follow the instruction to install Sphinx (apt-get install a lot of things, and then pip install posketsphinx), but do not install libasound2-dev.

Expected behaviour
------------------
Installation complete.

Actual behaviour
----------------
After a ton of outputs, the last lines says:
 deps/sphinxbase/src/libsphinxad/ad_alsa.c:76:28: fatal error: alsa/asoundlib.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

System information
------------------
My **system** is Ubuntu 16.04 LTS x64
My **Python version** is 3.5.2
My **Pip version** is 19.0.1
My **SpeechRecognition library version** is 3.8.1
I don't have PyAudio installed.
I **installed PocketSphinx from** pip.

**Comment by fygul** [comment]
[Building PocketSphinx-Python from source](https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst#building-pocketsphinx-python-from-source) was updated to include 'libasound2-dev'

**Comment by ftnext** [comment]
Thanks a lot @fygul #396
