### ISSUE TITLE
PyInstaller --noconsole/windowed mode cannot recognize

### ISSUE THREAD

**Issue by muhammeteminturgut** [Uberi/speech_recognition#405]
My System: Windows 10 64-Bit, Python 3.5.4, pip 9.0.1
SpeechRecognition library version: 3.8.1
PyAudio library version: 0.2.11

My Code:
```python
#. Tkinter codes
#.........................
#.........................
def main():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        status.set("Listening...") #Tkinter Label
        sound = r.listen(source)
    try:
        status.set("Processing...") #Tkinter Label
        word=r.recognize_google(sound, language="tr-tr")
        print(word)
    except:
        pass

while True:
    keyboard.add_hotkey('ctrl+alt', main) #Keyboard Library
```

I freezed my code with PyInstaller ( pyinstaller.exe --onefile ) everything is ok. But when i hide console (pyinstaller.exe --onefile --noconsole or --windowed) my code enter the except block. So ```word=r.recognize_google(sound, language="tr-tr") ``` not working.

**Comment by butchpaolom** [comment]
Hello, have you solved this? I'm having the same problem.

**Comment by muhammeteminturgut** [comment]
> Hello, have you solved this? I'm having the same problem.

Unfortunately no. I also reported the failure to the pyinstaller team, but the problem was not solved.

**Comment by butchpaolom** [comment]
> > Hello, have you solved this? I'm having the same problem.
> 
> Edit// Yes i solved problem. Just use Pyinstaller on Windows 7.

I'll try. Thank you so much

**Comment by butchpaolom** [comment]
Did you literally switched os? Switching compatibility in properties wont help

> > Hello, have you solved this? I'm having the same problem.
> 
> Edit// Yes i solved problem. Just use Pyinstaller on Windows 7.

**Comment by muhammeteminturgut** [comment]
I solved the problem for about a year. So I can't remember exactly how I solved it. But if I remember correctly, I started using Python 3.5. and I'm using pyinstaller on Windows 7 (Virtual Machine).
