### ISSUE TITLE
can not import speech_recogination

### ISSUE THREAD

**Issue by ArjunAbhijith** [Uberi/speech_recognition#424]
Expected behaviour
------------------

should have imported

Actual behaviour
----------------
C:\Users\Arjun\Desktop\Python\Python 18-20 -3.7\text to speech>py
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import speech_recognition as r
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'speech_recognition'

threw an error

System information
------------------

My **system** is windows 7 x64. (For example, "Ubuntu 16.04 LTS x64", "Windows 10 x64", or "macOS Sierra".)

My **Python version** is 3.7.3.

My **Pip version** is 19.1.1. 

My **SpeechRecognition library version** is 3.8.1. 

My **PyAudio library version** is 0.2.11.

I **installed PocketSphinx from** https://www.lfd.uci.edu/~gohlke/pythonlibs/#pocketsphinx.

**Comment by Grepolian** [comment]
you need to install the speech_recognition first. open your cmd and type 
`python pip install speech_recognition`
or
`py -m pip install speech_recognition`

**Comment by shafaypro** [comment]
You are using multiple versions of pip, before installing do check
`where python`
also, check how many versions you have installed whether you have anaconda 3 and python3, these might be conflicting.

To correct this, if you have pycharm, go to settings- > Project interpreter --> Select the version and install there.
OR remove all the packages and use python3 only.

**Comment by ArjunAbhijith** [comment]
it didnt worked for me

**Comment by ArjunAbhijith** [comment]
nvm
