### ISSUE TITLE
Speech Recognition not giving correct transcriptions using wav files 

### ISSUE THREAD

**Issue by Sadam1195** [Uberi/speech_recognition#429]
Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)
Loading wave files using librosa load and Yes.

2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)

```
import speech_recognition as sr
# use the audio file as the audio source
files = glob.glob('new_file_write.wav')
for AUDIO_FILE in files:
    r = sr.Recognizer()
    with sr.AudioFile(AUDIO_FILE) as source:
        audio = r.record(source)  # read the entire audio file
    # recognize speech using Google Speech Recognition
    try:
        print("Google Cloud Speech Recognition thinks you said " + r.recognize_google_cloud(audio, credentials_json=GOOGLE_CLOUD_SPEECH_CREDENTIALS))
    except sr.UnknownValueError:
        print("Google Cloud Speech Recognition could not understand audio")
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))
```

3. (If there are any files, like audio recordings, don't forget to include them.)
[https://drive.google.com/open?id=1D4Uiw5IWfDQ_lNIfH4gzEjYTkyEy4Pup](url)

Expected behaviour
------------------
It should show print the correct transcriptions.
(What did you expect to happen?)
The chicken and duck are doing the same trick again. A race down to the villa seemed little fun. There is a dark forest near the foot of a mountain. The boy of course cried out even louder than before. The cousins stayed for a short while. Not long after, a woe just struck. The person was looking for a change from his usual diet.

Actual behaviour
----------------
Code made the wrong transcription 
"boy Ghost Rider 3 in love doesn't decrease based on the villas in Jagat Farm dark forest is near foot of a mountain present state for chat via not long after about district the person was looking for change change"

(What happened instead? How is it different from what you expected?)
Results are way off than they should be.
```
(If the library threw an exception, paste the full stack trace here)
```
It didn't. No errors in running the code.

System information
------------------
My **system** is <Ubuntu 18.04.2 LTS x64>.
My **Python version** is <Python 3.7.3>.
My **Pip version** is <pip 19.1.1 >. 
My **SpeechRecognition library version** is <3.8.1>.
My **PyAudio library version** is <0.2.11>.
My **wave library version** is <0.0.2>.

Audio is mono with sample rate of 16000. Anything I need to make the transcriptions right? @Uberi

**Comment by chrisspen** [comment]
Your code looks fine. The problem looks to be your wav file. I just listened to it myself, and I can't tell what's being spoken. It sounds like there's a ton of noise and echo, and the speaker itself seems to have a thick non-English accent. If a human can't make sense of it, a computer certainly won't be able to.

**Comment by Sadam1195** [comment]
@chrisspen Hey, thanks for the response. There was issue with the file, the spoken speech was very fast. Sentences were quite difficult. I was testing that for something but I made it working then using different encoding.
