### ISSUE TITLE
Error when trying initializing 

### ISSUE THREAD

**Issue by richardbeattie** [Uberi/speech_recognition#43]
I am using speech_recognition on a raspberry pi running a version of linux, and I get this error when I try and run my program

ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1438
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2742
Traceback (most recent call last):
File "AI.py", line 62, in 
with sr.Microphone(0) as source:
File "/usr/local/lib/python2.7/dist-packages/SpeechRecognition-1.4.0-py2.7.egg/speech_recognition/init.py", line 61, in enter
input = True, # stream is an input stream
File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
stream = Stream(self, args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 442, in init
self._stream = pa.open(**arguments)
IOError: [Errno Invalid number of channels] -9998

This error appears at this line of code
with sr.Microphone(0) as source:
print("Got passed")
audio = r.listen(source)

The same program works fine when I am running it on OS X. I belive it is caused by the pyaudio channel it is using, as I got the same error 'IOError: [Errno Invalid number of channels] -9998' using record.py(a test file from the pyaudio folder), but when I changed its channel to 0 it worked.

Any help would be greatly appreciated, thanks.

**Comment by Uberi** [comment]
Please post the full error message. A traceback is useful, but the line after it is the most important one - the one that tells us what actually went wrong.

**Comment by richardbeattie** [comment]
Here is the full error message

ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1438
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2742
Traceback (most recent call last):
  File "AI.py", line 62, in <module>
    with sr.Microphone(0) as source:
  File "/usr/local/lib/python2.7/dist-packages/SpeechRecognition-1.4.0-py2.7.egg/speech_recognition/__init__.py", line 61, in __enter__
    input = True, # stream is an input stream
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid number of channels] -9998

This error appears at this line of code
with sr.Microphone(0) as source:
            print("Got passed")
            audio = r.listen(source)

**Comment by richardbeattie** [comment]
@Uberi I added the whole error

**Comment by Uberi** [comment]
Check out [this StackOverflow thread](http://stackoverflow.com/questions/31073667/getting-ioerror-errno-invalid-number-of-channels-9998-when-using-mic-with-py)! You may need to get a sound card for your RPi that supports audio capture.

**Comment by richardbeattie** [comment]
@Uberi I tested the sound card with pyaudio recording and it recorded fine, I am currently just recording what is said and saving that to a .wav file, and then recognizing that.
