### ISSUE TITLE
speechrecognition errro

### ISSUE THREAD

**Issue by GaneshJondhalekar** [Uberi/speech_recognition#431]
This is my code please help me.

import speech_recognition as sr
import pyaudio
r = sr.Recognizer()

with sr.Microphone() as source:
    print("Speak")
    audio = r.listen(source)
    try:
        text = r.recognize_google(audio)
        print(format(text))

    except:
        print("sorry")

please solve folloving error

/usr/bin/python3.5 /home/ganesh/pycharm/PycharmProjects/SpeechRecognization.py
Traceback (most recent call last):
  File "/home/ganesh/pycharm/PycharmProjects/SpeechRecognization.py", line 5, in <module>
    with sr.Microphone() as source:
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 113, in get_pyaudio
    raise AttributeError("PyAudio 0.2.11 or later is required (found version {})".format(pyaudio.__version__))
AttributeError: PyAudio 0.2.11 or later is required (found version 0.2.8)

Process finished with exit code 1

**Comment by Sadam1195** [comment]
hey, It seems that PyAudio package is missing. Install it first then re-run the code. 
try this `pip install PyAudio-0.2.11-cp37-cp37m-win_amd64.whl`  if you have python 3 and 64-bit system.

**Comment by Grepolian** [comment]
`py -m pip install pyaudio ` worked for me
