### ISSUE TITLE
Recognized Words

### ISSUE THREAD

**Issue by TheAtomicNord** [Uberi/speech_recognition#44]
First of all, I love this module you've created. It really makes speech recognition under python incredibly simple and I thank you for all your hard work. 
However, I am having a hard time getting this library to understand words that it doesn't want to. For instance "Codsworth" is not a word but a name. This is not recognized by the speech API and is causing me a great deal of trouble. Any help? Thanks

**Comment by Uberi** [comment]
Hi @TheAtomicNord,

The speech API cannot transcribe words that it doesn't recognize - there is no concept of "transcribing sounds". Instead, you can try another library such as SPHINX that supports phoneme recognition and transcription.

**Comment by Uberi** [comment]
Here is an example of phoneme recognition: http://cmusphinx.sourceforge.net/wiki/phonemerecognition

To recognize words that aren't really "words", you would need to set up SPHINX such that unrecognized words are gone over with the phoneme recognizer. The resulting phonemes (like F or AO, R, W, ER, D) should then be concatenated to get FAORWERD (forward).

Note that this isn't very accurate - it doesn't take into account any linguistic rules, so you might not get very high quality results from it.

**Comment by AndreMiras** [comment]
@Uberi , have you considered integrating Sphinx to your library? Would that be relevant?
I used your library as well as Sphinx and I feel like it would be great if we could easily switch from Wit.ai, IBM, AT&T or even Sphinx. What do you think? I could eventually do the porting myself, but I'm not a STT expert at all and I would like to have your advice to know if that would make sense.

**Comment by Uberi** [comment]
@AndreMiras actually, I've been working on that previously! Sphinx integration will be a part of the next point release 3.2, which, fingers crossed, will be out in a few days.

**Comment by AndreMiras** [comment]
Wonderful! Please let me know when it's ready so I can test it.
