### ISSUE TITLE
Invalid Sample Rate

### ISSUE THREAD

**Issue by JoeGearyIII** [Uberi/speech_recognition#45]
Is there any way to specify the sample rate that should be used, for recording via the microphone.

I'm using a bluetooth headset and I have no problem recording via arecord at 8000; however, when I attempt to utilitze SpeechRecognition-1.4.0, an exception is generated in speech_recognition.__init__.py (line 61) / pyaduio.py (line 396) stating "IOError: [errno Invalid sample rate] -9997".  I believe that you are defaulting to a rate of 16000 and I would like to change it to 8000.

Edit:  I'll need to hone in on more of the root cause.  For grins, I directly edited the __init__.py source, changing the sample rate, and while it no longer throws an error, it also does not record audio from the Bluetooth headset (even though arecord records audio just fine).

**Comment by Uberi** [comment]
Hmm, that's rather weird. Is the output simply silence, or can you obtain the audio, but the speech is not being recognized?

By the way, you can change the sampling rate by setting `m = Microphone(); m.RATE = 8000`, and then using `with m: ...`

**Comment by XayOn** [comment]
I opened a pull request for rate sampling via parameters, having to force it like that seems a bit un-pythonic =/

**Comment by Uberi** [comment]
Thanks @XayOn, I've merged your changes and documented them in the README and docstrings.  These are now live in version 2.2!
