### ISSUE TITLE
Is it work in offline? It's not work in offline for me.

### ISSUE THREAD

**Issue by almasud** [Uberi/speech_recognition#460]

**Comment by AlpixTM** [comment]
No, it requires online access, as stated in the readme.

Only CMU Sphinx and Snowboy Hotword Detection do not require online access.

**Comment by almasud** [comment]
But according to https://pypi.org/project/SpeechRecognition/ it's "Library for performing speech recognition, with support for several engines and APIs, online and offline." AlpixTM

**Comment by AlpixTM** [comment]
Yes the library itself works offline.
But it needs to use a Speech recognition engine/API.
And most of them are online.
![image](https://user-images.githubusercontent.com/17622853/73199221-b6d8fc80-4134-11ea-826d-d47768758227.png)
If an engine has offline support it is stated in the brackets behind the name.

So if you want to support offline speech recognition, you need to use CMU Sphinx.
For the recognition of your keyword, you can also use Snowboy Hotword Detection.

Online speech recognition is more accurate but also subject to privacy concerns.
Maybe you could check if the user has an internet connection and then decide based on that what speech engine you want to use.
