### ISSUE TITLE
how to stop listen_in_background

### ISSUE THREAD

**Issue by marchtom** [Uberi/speech_recognition#47]
Once I start listen_in_background I can't stop it. Is there any way to turn it off?

Thank you,
marchtom

**Comment by Uberi** [comment]
Hi @marchtom,

This feature has been added in version 2.0, which I just release. Please update your library and check out the "Listening to a microphone in the background" example in the README!

Basically, now when you call `listen_in_background`, it will return a function. Call that function to stop the listener thread.

**Comment by marchtom** [comment]
@Uberi thank you for fast response.

Unfortunately after update I get this error as soon as I start listen_in_background

Exception in thread Thread-3:
Traceback (most recent call last):
  File "E:\Users\Tomek\Anaconda32\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "E:\Users\Tomek\Anaconda32\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "E:\Users\Tomek\Anaconda32\lib\site-packages\speech_recognition\__init__.py", line 373, in threaded_listen
    except TimeoutError:
NameError: global name 'TimeoutError' is not defined

**Comment by Uberi** [comment]
This has been fixed in version 2.0.1 - we should really test on Python 2 more often!
