### ISSUE TITLE
Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC

### ISSUE THREAD

**Issue by Paritoshyadav** [Uberi/speech_recognition#470]
I am recording voice using javascript in .wav format:

```
navigator.mediaDevices.getUserMedia({audio:true})
      .then(stream => {handlerFunction(stream)})

      function handlerFunction(stream) {
            rec = new MediaRecorder(stream);
            rec.ondataavailable = e => {
              audioChunks.push(e.data);
              if (rec.state == "inactive"){


                let blob = new Blob(audioChunks,{type:'audio/wav;codecs=0'});

                sendData(blob)
              }
            }
          }
```

sending the file to convert it to text using speech_recognition:
```
    filename = "name.wav"
    print(filename)
    data = request.body
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    uploadedFile = open(filename, "wb")
    uploadedFile.write(request.body)
    uploadedFile.close()
    #os.path.join(BASE_DIR,filename)
    r = sr.Recognizer()
    file = sr.AudioFile(filename)
    with file as source:
        audio = r.record(source)
    msg = r.recognize_google(audio)
    print(msg)
    return redirect('/')
```
getting Error:
```
ValueError: Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format
```

audio is saving and sound is clear 

audio file:https://drive.google.com/open?id=17ucX9xRG0x5-JEtZDFaotSNLlcRs0jZc

**Comment by Asalle** [comment]
@Paritoshyadav did you get to the bottom of this? I got the same error and would be great to learn about your fix if any.

**Comment by arnavgupta829** [comment]
Try converting it using ffmpeg from the terminal (or use the os commands in python for doing it while the code is running)

**Comment by cuongnguyengit** [comment]
> Try converting it using ffmpeg from the terminal (or use the os commands in python for doing it while the code is running)

can you expain detail??

**Comment by Paritoshyadav** [comment]
> > Try converting it using ffmpeg from the terminal (or use the os commands in python for doing it while the code is running)
> 
> can you expain detail??

@Asalle @cuongnguyengit  u need to install FFmpeg like:= https://github.com/kkroening/ffmpeg-python or from any other repo or lib that use FFmpeg and use it to convert the current file format to 
PCM WAV, AIFF/AIFF-C, or Native FLAC format before processing it

**Comment by cuongnguyengit** [comment]
> > > Try converting it using ffmpeg from the terminal (or use the os commands in python for doing it while the code is running)
> > 
> > 
> > can you expain detail??
> 
> @Asalle @cuongnguyengit u need to install FFmpeg like:= https://github.com/kkroening/ffmpeg-python or from any other repo or lib that use FFmpeg and use it to convert the current file format to
> PCM WAV, AIFF/AIFF-C, or Native FLAC format before processing it

https://github.com/kkroening/ffmpeg-python/blob/master/examples/README.md#convert-sound-to-raw-pcm-audio.
I found the following url, i see the url. can u indicate for me how to read the wav file?

**Comment by Paritoshyadav** [comment]
@cuongnguyengit example:
stream = ffmeg.input(filename)
stream = ffmeg.output(stream,covert_filename)
ffmeg.run(stream)

// here filename = audio.mp4 file and convert_filename = audio.wav or any format you want to save it

**Comment by cuongnguyengit** [comment]
> @cuongnguyengit example:
> stream = ffmeg.input(filename)
> stream = ffmeg.output(stream,covert_filename)
> ffmeg.run(stream)
> 
> // here filename = audio.mp4 file and convert_filename = audio.wav or any format you want to save it

i dont understand a problem. your recording is formatted into "audio.mp4" but not "audio.wav"?
u sent a blod data with mp4 format, then processing the format. Do i understand correctly??

**Comment by Paritoshyadav** [comment]
@cuongnguyengit 

since its been a while I solve this problem I don't remember correctly but I think recording the data from javascript don't give u wav or some other format that u need to play the file..... there is the problem in format when u record through frontend/javascript i don't remember the exact problem now but it was something like that

**Comment by PRG14112000** [comment]
Can you please tell how you record the audio from microphone and convert it to text

**Comment by Yash-Gajewar** [comment]
> tend/javascript i don't remember the exact problem now but it w

So how did you generated text from audio I was working on a project and had similar frontend code like you and it is giving me same issue that frontend is giving corrputed/unplayable file and wanted to extract text so how did you made it work please answer it would be very helpful!!
