### ISSUE TITLE
Listen function doesn't detect the stop of the phrase

### ISSUE THREAD

**Issue by chaoming** [Uberi/speech_recognition#48]
I am using the 4th example code. It works sometimes, but sometimes it doesn't seem to be able to detect the stop of the phrase and keep listening even I am no longer speaking. After a long while, maybe 30 seconds or more of silence, if finally stops and sends the audio to Google. And sometimes it doesn't come back with anything and there is no error message.

**Comment by Uberi** [comment]
Can you try the example again with the latest version? Please post the exact code used.

**Comment by chaoming** [comment]
I am just using your __main__.py code.

Sometimes it takes a while after I stop speaking, then it prints out "Got it! now to recognize it...". I am guess somehow the threshold doesn't work very well so the script doesn't realize I have stopped speaking.

**Comment by Uberi** [comment]
Hmm, have you tried increasing the threshold? Also make sure to try the dynamic threshold so it will adapt to your speaking volume as you speak.

**Comment by chaoming** [comment]
Yes, I have increased threshold to 3000. The thing is no matter what's the threshold value, it sometimes works and sometimes doesn't. Even just few seconds apart from one test to another.

I start to suspect it is my Raspberry Pi B+ CPU capacity issue. I am not sure how the threshold works. But my guess is that there is a loop to check the CHUNK to see what's the energy level and decide whether it is below the threshold low enough to stop recording?

I am going to give a shot on my Raspberry Pi 2 which has faster CPU and more RAM.

**Comment by chaoming** [comment]
I can confirm this issue is related to the device. I moved the script to Raspberry Pi 2 and it works very well. Raspberry Pi B+ possibly can not process the audio input fast enough.
