### ISSUE TITLE
Confidence always "1"

### ISSUE THREAD

**Issue by davidfer1991** [Uberi/speech_recognition#49]
Hello all,

I've been using this function for a while having good results but since last tuesday I'm always getting "1" in the confidence score, no matter if the text is well recognized or not.

Do you guys know why this could be happening?

Any help would be appreciated!!

Regards

**Comment by Uberi** [comment]
Hi @davidfer1991,

Google no longer gives back proper confidence values, unfortunately. That means that we can't really get this information. This happened a while back, actually - we've been returning 1 for a long time now (mainly for backwards compatibility reasons).

However, we do know that the resulting transcriptions are sorted from most confident to least confident. Check out the confidence example for a demo!
