### ISSUE TITLE
Compatiblity

### ISSUE THREAD

**Issue by caue-alves** [Uberi/speech_recognition#497]
Please uptade the module to Python 3.8 versions

**Comment by caue-alves** [comment]
Hello @mytja, for me, the execution of the Recognition in 3.8 throw sow many errors and don't work. When I tried 3.6 all worked fine

**Comment by mytja** [comment]
@caue-alves You can do following
`python -m pip install pipwin && python -m pipwin install SpeechRecognition`
Let me know if that helped!

**Comment by caue-alves** [comment]
ok @mytja, now I can't, but in the afternoon I will try and say you if works

**Comment by caue-alves** [comment]
I already have `pipwin`, so all gonna be easier

**Comment by mytja** [comment]
Sorry, just realized that pipwin cant install SpeechRecognition, but if you send me an output, i can help

**Comment by caue-alves** [comment]
Ok, I will close. I can run in 3.6, thanks @mytja.
