### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by BlkChockr** [Uberi/speech_recognition#52]
Hey there,

I get this exception

```UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 56: ordinal not in  range(128)```

when using your example code (in python 2.7.10) and setting the language to german. The character should be 'ö'.

I did some research and using

```UTF8Writer = codecs.getwriter('utf8')```
```sys.stdout = UTF8Writer(sys.stdout)```

at the very beginning of the example code solved the problem.

Maybe you could/should add this to the speech recognition code itself, if you're giving people the choice to use any language they like :)

**Comment by Uberi** [comment]
Hi @BlkChockr,

Thanks for reporting! This has been fixed in 2.1.3.

I used the encode method instead of a UTF8Writer, since that doesn't break Python 3 code or other parts of programs that depend on bytes output.
