### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by rudrathegreat** [Uberi/speech_recognition#525]
Steps to reproduce
------------------

```Python

import speech_recognition as sr
import pyaudio

def recordAudio():
    # Record Audio
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Say something!")
        audio = r.listen(source, timeout=1, phrase_time_limit=10)

    # Speech recognition using Google Speech Recognition
    data = ""
    try:
        # Uses the default API key
        # To use another API key: `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
        data = r.recognize_google(audio)
        print("You said: " + data)
    except sr.UnknownValueError:
        print("Google Speech Recognition could not understand audio")
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))

    return data

recordAudio()

```

Expected behaviour
------------------

I expected it to record my voice, use Google's API to convert speech to text and then print the text in the Python Shell

Actual behaviour
----------------

```
Traceback (most recent call last):
  File "D:/Rudra/Python/J.A.R.V.I.S/test.py", line 9, in recordAudio
    audio = r.listen(source, timeout=1, phrase_time_limit=10)
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\speech_recognition\__init__.py", line 639, in listen
    assert source.stream is not None, "Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Rudra/Python/J.A.R.V.I.S/test.py", line 25, in <module>
    recordAudio()
  File "D:/Rudra/Python/J.A.R.V.I.S/test.py", line 9, in recordAudio
    audio = r.listen(source, timeout=1, phrase_time_limit=10)
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\speech_recognition\__init__.py", line 188, in __exit__
    self.stream.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

System information
------------------

My **system** is Windows 7 x64.

My **Python version** is 3.7.0.

My **Pip version** is 20.2.3.

My **SpeechRecognition library version** is 3.8.1.

My **PyAudio library version** is 0.2.11.

**Comment by rudrathegreat** [comment]
Fixed

**Comment by Cardreaper** [comment]
I Have kind of the same problem.

Exception has occurred: AttributeError
'NoneType' object has no attribute 'close'
  File "C:\SARA\Testy.py", line 32, in record_audio
    audio = self.r.listen(source,5,5)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

  File "C:\SARA\Testy.py", line 27, in record_audio
    with sr.Microphone() as source:
  File "C:\SARA\Testy.py", line 88, in <module>
    voice_data = assistente.record_audio('A ouvir...')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'

How did you fixed this?
thank you

**Comment by FishinecraftNew** [comment]
> I Have kind of the same problem.
> 
> Exception has occurred: AttributeError 'NoneType' object has no attribute 'close' File "C:\SARA\Testy.py", line 32, in record_audio audio = self.r.listen(source,5,5) ^^^^^^^^^^^^^^^^^^^^^^^^^ AssertionError: Audio source must be entered before listening, see documentation for `AudioSource`; are you using `source` outside of a `with` statement?
> 
> During handling of the above exception, another exception occurred:
> 
> File "C:\SARA\Testy.py", line 27, in record_audio with sr.Microphone() as source: File "C:\SARA\Testy.py", line 88, in voice_data = assistente.record_audio('A ouvir...') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'close'
> 
> How did you fixed this? thank you

Please check your microphone.
