### ISSUE TITLE
Every code which includes PyAudio Responses with "Python" word

### ISSUE THREAD

**Issue by LFCrushTeam** [Uberi/speech_recognition#532]
Windows 10
Python 3.7
Pip 20.2.4
```
C:\Users\User\Desktop\Folder>python main.py
Python
```

**Comment by navaem** [comment]
How are you calling PyAudio? We probably need to see what is written in main.py

**Comment by LFCrushTeam** [comment]
> How are you calling PyAudio? We probably need to see what is written in main.py

All is ok, that was Windows update in Microsoft Store, which worked incorrect.
