### ISSUE TITLE
🚨 Potential Improper Access Control

### ISSUE THREAD

**Issue by huntr-helper** [Uberi/speech_recognition#567]
👋 Hello, @Uberi - a potential high severity Improper Access Control vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-Uberi/speech_recognition** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by Uberi** [comment]
I have checked with the bug reporter and confirmed that this issue will not impact users (i.e., I've marked it invalid).
