### ISSUE TITLE
example wav_transcribe.py doesn't work 

### ISSUE THREAD

**Issue by adrianzhang** [Uberi/speech_recognition#57]
When I am trying to run `python wav_transcribe.py` with my abc.wav(of cause this file is defined in script), it says:

`Google Speech Recognition thinks you said what are Dinobots`

I have a Google Cloud account and a valid API key(type: host) (however I could not find Speech Recognition API in it's cloud platform), then I use this key in the script, what I get is:

`Could not request results from Google Speech Recognition service`

So there are 2 questions:
- How to make example work?
- where to get API key? no matter free or pay.

**Comment by adrianzhang** [comment]
Well, I think it works and guessing it just support English voice.~~~

**Comment by Uberi** [comment]
Hi @adrianzhang,

Please read the documentation for the `recognize_google` function:

* You will need to get a Speech API key, not a Google Cloud key.
* The documentation has a link to the [page with instructions for obtaining an API key](http://www.chromium.org/developers/how-tos/api-keys).

**Comment by adrianzhang** [comment]
@Uberi sorry for late reply, I just saw the comment.
And thank you for help. I got the speech API key, and unfortunately it is 50req/day limitation. 
Anyway, thank you so much to develop so charming API.

**Comment by adrianzhang** [comment]
@Uberi BTW, Nuance has better API support, however I am looking to find a right way to use it since the doc and support give conflict information about request URL. If you have interesting, suggest to have a look at Nuance API here: http://nuancemobiledeveloper.com/public/index.php?task=home
If I find a way to use it. Maybe I can try to combine it  into your API.

**Comment by Uberi** [comment]
Hi @adrianzhang,

I'll definitely look into that! The current APIs I am looking at are now Amazon Alexa and the Nuance API.

As for your Google API key, unfortunately there's no easy way to get a key that allows more than 50 requests per day. I recommend checking out the other APIs already supported, such as the AT&T one (check out `recognize_att` for more information).

**Comment by adrianzhang** [comment]
@Uberi 
My requirement is that, support multiple languages, large quota as much as possible. Guessing lots of people have the same. The problem of AT&T and wit.ai is less languages support. I do not yet try how IBM service is. For app dev on Android or iPhone, there is also another service which is ispeech.org can be used for free. I will have a look at IBM and Amazon Alexa to see if they fulfill my needs. And I noticed that your API is created in binary, that will cause me stop integrate Nuance API into it.

**Comment by adrianzhang** [comment]
Hello, here is api of Nuance. don't know how to combine to your code because it is python api.


<pre><code>
import os
import requests

class Nuance_api():
	"""Nuance ASR Service API"""
	def __init__(self, appid, appkey, n_id):
		self.appid = appid
		self.appkey = appkey
		self.id = n_id

	def recogenize(self, language, voicefile):
		nuance_url = 'https://dictation.nuancemobility.net/NMDPAsrCmdServlet/dictation'
		n_params = {'appId':self.appid, 'appKey':self.appkey, 'id':self.id}
		voice_file = {'file': open(voicefile, 'rb')}
		n_headers = {'Accept-Language':language, 'Content-Type':'audio/amr;codec=amr;bit=4.75;rate=8000', 'Accept':'text/plain', 'Accept-Topic':'Dictation'}
		r = requests.post(url=nuance_url, params=n_params, headers=n_headers, files=voice_file, verify=False)
		if r.status_code == 200 :
			return r.text
</code></pre>

**Comment by adrianzhang** [comment]
@Uberi  see above
