### ISSUE TITLE
What is the difference between Google Cloud Speech API and the one that recognizer.recognize_google is using? 

### ISSUE THREAD

**Issue by j-j-kam** [Uberi/speech_recognition#570]
I know that the Google Cloud Speech API is not free. What about the one that that recognizer.recognize_google is using? Is it the Google Web Speech API? Is it free for commercial use?

**Comment by amcareem** [comment]
The Google Cloud Speech API are based on the newer versions  and also it has minimum latency compared to the recognizer in python. The recognizer.recognize_google limits you when you are doing for longer audio files.
Thats all I know. If you know anything more than this feel free to mention.
Good luck!

**Comment by pulkit21aug** [comment]
I am not sure if the module works correctly . Keeps getting the error  AssertionError: ``credentials_json`` must be ``None`` or a valid JSON string . Though the json credential file is downloaded from  google

**Comment by amcareem** [comment]
Did you import as
import os
["GOOGLE_APPLICATION_CREDENTIALS"]="/path/to/file.json"

or

import os
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file("your-json-path-with-filename.json")
client = language.LanguageServiceClient(credentials=credentials)

**Comment by UtkuDenizAltiok** [comment]
How to pay for the google cloud api and use it ?

**Comment by j-j-kam** [comment]
> The Google Cloud Speech API are based on the newer versions and also it has minimum latency compared to the recognizer in python. The recognizer.recognize_google limits you when you are doing for longer audio files.
> Thats all I know. If you know anything more than this feel free to mention.
> Good luck!
