### ISSUE TITLE
Please upload source packages to PyPI

### ISSUE THREAD

**Issue by strugee** [Uberi/speech_recognition#580]
Steps to reproduce
------------------

1. Visit https://pypi.org/project/SpeechRecognition/#files

Expected behaviour
------------------

There should be a source package published along with the binary wheel.

Actual behaviour
----------------

There's no source package.

System information
------------------

N/A

**Comment by avryhof** [comment]
https://pypi.org/project/speech-recognition-fork/#files

**Comment by ftnext** [comment]
This library has been uploading source distributions to PyPI from version 3.9.0.

https://pypi.org/project/SpeechRecognition/3.9.0/#files

**Comment by ftnext** [comment]
@chenrui333 FYI

Thanks for your reminder

**Comment by strugee** [comment]
Thank you! 🎉
