### ISSUE TITLE
Not working in my android phone

### ISSUE THREAD

**Issue by Iamafnan** [Uberi/speech_recognition#582]
**Speech Recognition Module** is not working on my Android phone 

When I type 
```py
python -m speech_recognition
```
in my termux app it gets stuck at 
```
A moment of silence, please...
```

**My Phone** 
Xiaomi Redmi 8a Dual

**Comment by robmsmt** [comment]
I don't think that running in termux is a good idea for this package. If you want to use the microphone just save the audio files from inside a proper android app to /sdcard then adb pull them to your laptop to evaluate. It's unlikely that this pip package will work directly with mic through termux. I am not even sure that termux requests proper mic access in it's app manifest.

**Comment by Iamafnan** [comment]
Okey
