### ISSUE TITLE
Add a recognizer for whisper

### ISSUE THREAD

**Issue by benthomasson** [Uberi/speech_recognition#624]
Feature request:

Add a recognizer for Whisper from here: https://github.com/openai/whisper

I'll start a PR.

**Comment by joy-void-joy** [comment]
Hey @benthomasson , can I ask where you are with this PR? I also intended to finish a PR to integrate whisper, but if you are already on it then I don't want to interupt!
Thanks a lot in any case :D

**Comment by ftnext** [comment]
Closed by #625.

Try Whisper by `pip install git+https://github.com/Uberi/speech_recognition`.
We'd be happy to send your feedback.
