### ISSUE TITLE
WAV Results are way off

### ISSUE THREAD

**Issue by WillStealthMonitoring** [Uberi/speech_recognition#64]
I'm trying to use speech_recognition 3.1.2 using Python 3.4 but I've been having troubles the entire time. 

Initially when trying to use just the example WAV recognizer I was getting TypeError: 'str' does not support the buffer interface so I combed through the source and made the following change:

        def read(self, size = -1):
            buffer = self.wav_reader.readframes(self.wav_reader.getnframes() if size == -1 else size)
            if type(buffer) is str:
                buffer = buffer.encode(encoding="utf-8", errors="strict")
                print(buffer)
            if self.wav_reader.getnchannels() != 1: # stereo audio
                try:
                    buffer = audioop.tomono(buffer, self.wav_reader.getsampwidth(), 1, 1) # convert stereo audio data to mono
                except Exception as e:
                    print(e)
            return buffer

from:

        def read(self, size = -1):
            buffer = self.wav_reader.readframes(self.wav_reader.getnframes() if size == -1 else size)
            if self.wav_reader.getnchannels() != 1: # stereo audio
                buffer = audioop.tomono(buffer, self.wav_reader.getsampwidth(), 1, 1) # convert stereo audio data to mono
            return buffer

While it doesn't throw an error now the transcription quality is terrible. I can run python -m speech_recognition with great accuracy so I'm not sure what is happening. I upped the energy_threshold to 4000 to make sure it wasn't an ambient noise issue. I even used 2 different recognition services (IBM and Google Speech Recognition). Also, for some reason the last 2 buffers are empty Strings which I then have to convert to byte objects

    b''
    b''

Any advice would be awesome!

**Comment by Uberi** [comment]
Hi Will,

I replied to your email, but forgot to ask: could you also post the full stack trace? Simply use this following snippet:

    def read(self, size = -1):
        buffer = self.wav_reader.readframes(self.wav_reader.getnframes() if size == -1 else size)
        if type(buffer) is str:
            buffer = buffer.encode(encoding="utf-8", errors="strict")
            print(buffer)
        if self.wav_reader.getnchannels() != 1: # stereo audio
            try:
                buffer = audioop.tomono(buffer, self.wav_reader.getsampwidth(), 1, 1)
            except Exception as e:
                import traceback
                traceback.print_exc()
        return buffer

**Comment by WillStealthMonitoring** [comment]
Thanks for reaching out! The result of your query is:

0.2.8 3.1.2
3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]

and after editing the read method I get:

Recognizing  .\assets\test.wav
b''
IBM Speech to Text thinks you said nnj 

Google Speech Recognition could not understand audio
127.0.0.1 - - [04/Nov/2015 14:57:19] "POST /upload HTTP/1.1" 200 -

If I remove the check for a string I get:

Recognizing  .\assets\test.wav
Traceback (most recent call last):
  File "C:\Users\William\AppData\Roaming\Python\Python34\site-packages\speech_recognition\__init__.py", line 137, in read
    buffer = audioop.tomono(buffer, self.wav_reader.getsampwidth(), 1, 1)
TypeError: 'str' does not support the buffer interface
IBM Speech to Text thinks you said okay 
Google Speech Recognition thinks you said Google
127.0.0.1 - - [04/Nov/2015 14:58:48] "POST /upload HTTP/1.1" 200 -
Traceback (most recent call last):
Recognizing  .\assets\test.wav
  File "C:\Users\William\AppData\Roaming\Python\Python34\site-packages\speech_recognition\__init__.py", line 137, in read
    buffer = audioop.tomono(buffer, self.wav_reader.getsampwidth(), 1, 1)
TypeError: 'str' does not support the buffer interface
IBM Speech to Text thinks you said okay 
127.0.0.1 - - [04/Nov/2015 14:58:57] "POST /upload HTTP/1.1" 200 -
Google Speech Recognition thinks you said Google

As for the WAV, I attached that in the E-Mail since it isn't supported by GitHub

**Comment by Uberi** [comment]
Hi @WillStealthMonitoring,

After some debugging, it turns out it's [an issue in the Python standard library](https://bugs.python.org/issue24608).

I have added a workaround for this in 3.1.3 - just `pip install --upgrade SpeechRecognition` to get the fix!

Also, I made stereo audio work correctly for your sample. From running it, I get "hello there" as a result from the Google Speech API and Wit.ai.

**Comment by WillStealthMonitoring** [comment]
Just tested it and the transcription accuracy for a WAV with Python 3.4 is excellent now!
