### ISSUE TITLE
Flac linux permission denied ubuntu

### ISSUE THREAD

**Issue by whereismushfiq** [Uberi/speech_recognition#65]
Tonight my code was just hanging up when it's supposed to record. Then i tried python -m speech_recognition. I was running. But instead of decoding it's showing
Suddenly getting this error today . /usr/local/lib/python2.7/dist-packages/speech_recognition/flac-linux-i386:

**Comment by Uberi** [comment]
Hi @whereismushfiq,

Do you have the rest of the error?

**Comment by whereismushfiq** [comment]
Thank you. I fixed it. It tried to install that package with pip3 once. I think that was causing the problem.
