### ISSUE TITLE
recognize_google() stays "waiting" until i disable the mic

### ISSUE THREAD

**Issue by 0ut0flin3** [Uberi/speech_recognition#656]
Hello, I'm working on this project: https://github.com/0ut0flin3/openai-davinci003-python-speech
Till today it worked fine, but from today (to me) a strange thing happens on Ubuntu 20.04, i.e. the detection from the microphone remains "stuck" i.e. in "waiting" until I disable the microphone...precisely it remains stuck here : https://github.com/0ut0flin3/openai-davinci003-python-speech/blob/main/app.py#L68 (without giving any error).once i disable the mic then proceed the text is returned.. .how come? It's only been happening since today, it's happening every time, and the code is the same one I've always used. Thank you.

**Comment by 0ut0flin3** [comment]
`alsa force-reload` fix the problem

**Comment by GuiNovaisPy** [comment]
estou tendo o mesmo problema, como corrijo? o codigo estava funcionando normalmente.
        with sr.Microphone() as source:
            print('ouvindo')
           >>>>>>>>> voz = audio.listen(source) <<<<<<<<
            comando = audio.recognize_google(voz,language='pt-BR')
            comando = comando.lower()


>>>>>>>>> voz = audio.listen(source) <<<<<<<< agora fico preso nesta funcao com o mic aberto... e nao tenho retorno nenhum, ela simplesmente fica esperando
