### ISSUE TITLE
How to pause recording ?

### ISSUE THREAD

**Issue by whereismushfiq** [Uberi/speech_recognition#66]
Hello, is there any way to pause recording for a certain amount of time? 
update :  i might have found a way by setting the audio input zero and using time.sleep but a built in feature would be great

**Comment by whereismushfiq** [comment]
I think I have to use r.pause_threshold = few sec , right?

**Comment by Uberi** [comment]
Assuming you're using `recognizer_instance.listen_in_background`, you can stop recording using the stop function returned by that function:

```python
import time
import speech_recognition as sr

# this is called from the background thread
def callback(recognizer, audio):
    # received audio data, now we'll recognize it using Google Speech Recognition
    try:
        print("Google Speech Recognition thinks you said " + recognizer.recognize_google(audio))
    except sr.UnknownValueError:
        print("Google Speech Recognition could not understand audio")
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))

r = sr.Recognizer()
m = sr.Microphone()

stop_listening = r.listen_in_background(m, callback)

# stop listening, wait for 5 seconds, then restart listening
stop_listening()
time.sleep(5)
stop_listening = r.listen_in_background(m, callback)

# do other things on the main thread
while True: time.sleep(0.1)
```

**Comment by whereismushfiq** [comment]
Thanks a lot! I'll try that and update.

**Comment by whereismushfiq** [comment]
Actually the project i'm working on for that one, it's easier to use it like your simple __main__.py . The method below seems to work for me. Because for my project, I need to calculate the length of  recognized characters (value). Creating a global variable to hold that length is not working as i'm not calling callback() directly. Your method is better but let me know if you have any suggestion to expose the length outside of callback. I'm kinda new to python. Don't know the advanced features. Thank you.
```
value = r.recognize_google(audio) 
audio =0 
#do stuff... and wait using time.sleep
audio = r.listen(source) #start listening again
```

**Comment by Uberi** [comment]
Assuming you want the length of the recognized characters:

```python
import speech_recognition as sr
r = sr.Recognizer()
with sr.Microphone() as source:
    audio = r.listen(source)
result = r.recognize_google(audio)
print("Your phrase contains {} characters".format(result))
```

**Comment by whereismushfiq** [comment]
I see. So I have to call the recognizer again, although it was called inside callback. Thank you. I really appreciate your help.

**Comment by whereismushfiq** [comment]
Nope. Didn't work. I'm sticking to my method. Actually what I am doing is getting audio input and as a response reading out something. I could be a long article too. So it started listening to itself and responding. It was funny. So I decided to pause recording for sometime which is related to the length of the response. Anyway thanks for the help. As my trick is working at the moment .. i'll continue with it.
