### ISSUE TITLE
Support OpenAI Whisper API

### ISSUE THREAD

**Issue by ftnext** [Uberi/speech_recognition#668]
- https://openai.com/blog/introducing-chatgpt-and-whisper-apis
- https://platform.openai.com/docs/guides/speech-to-text/quickstart

**Comment by ventz** [comment]
@ftnext Would it be possible to add the 4-5 lines needed to make this Azure compatible too?

```
openai.api_version = OPENAI_API_VERSION
openai.api_type = OPENAI_API_TYPE
openai.api_key = OPENAI_API_KEY
openai.api_base = OPENAI_API_BASE
deployment_name = OPENAI_DEPLOYMENT_NAME
```

see: https://learn.microsoft.com/en-us/azure/ai-services/openai/whisper-quickstart?tabs=command-line#rest-api

it really just requires a custom `openai.api_base`, the key (`openai.api_key` -- already available) as is, a `openai.api_type`, `openaiapi_version`, and `deployment_name` (could be named anything).

You could keep everything the same, and just provide them as override parameters.
