### ISSUE TITLE
Can't record audio on rpi

### ISSUE THREAD

**Issue by XayOn** [Uberi/speech_recognition#67]
Hi there Uberi.
I'm currently investigating an issue with sr on the PI, and I'm quite lost.

Problem:

It seems like I can't get it to get sound, it gets stuck on Recogniser 's listen method (It seems like pyaudio's read_stream is not returning anything).
And... well. I'm kinda lost on where to follow. Any idea?

Right now I've:
- Tried to update to pyaudio 0.2.9 and latest speech_recognition.
- Checked that I CAN record sound with pyaudio
- Checked that my usb card is index 0
- Tried with older pyaudio and speech_recognition (lightly patched)
- Debugged to see where it gets stuck (read_stream, and, acording to strace, it's getting EAGAIN from the driver, not getting any audio data maybe? but recording works.)

I would normally not open this as a bug, but as I've encountered #62 and may be related (but may be not)... 

Anything I can do, here I'm.

**Comment by XayOn** [comment]
write(2, "return pa.is_stream_stopped(self"..., 42return pa.is_stream_stopped(self._stream)
) = 42
close(3)                                = 0
munmap(0x76f11000, 4096)                = 0
write(2, "IOError", 7IOError)                  = 7
write(2, ": ", 2: )                       = 2
write(2, "[Errno -9988] Stream closed", 27[Errno -9988] Stream closed) = 27
write(2, "\n", 1
)                       = 1

(Pyaudio 0.2.9 speech_recognition 3.1.3)

**Comment by Uberi** [comment]
Hmm, how are you doing recording? Is this using `arecord` (ALSA) or using PyAudio/Python? Which Raspberry Pi are you using?

**Comment by clusterfudge** [comment]
I can confirm this same issue, both on rpi and ubuntu desktop. after recording a few times, listen will block on portaudio.read_stream (underneath pyaudio.Stream.read) will block for arbitrary amounts of time; sometimes a second, sometimes it does not return for several minutes.

You asked if the original reporter was using arecord or pyaudio; It's likely that arecord would provide better consistent recordings, but I feel like it would be a real hassle to reimplement on top of arecord. Impossible? No. Hassle? So much so.

thanks!

**Comment by XayOn** [comment]
I'm sorry, I forgot to reply to this ticket and I've been quite busy,_ but as stated in the main comment:
"Checked that I CAN record sound with pyaudio"

I'll try with latest versions as soon as I can and report back here.
Thanks

**Comment by hassanmian** [comment]
Hi guys,

Ran into the same issue. After some debugging I found that the following worked on my Rpi:

```

import speech_recognition as sr

# Settings
mic_name = "Blue Snowball: USB Audio (hw:1,0)"
sample_rate = 48000
chunk_size = 2048

# obtain audio from the microphone
r = sr.Recognizer()
r.energy_threshold = 50

mic_list = sr.Microphone.list_microphone_names()

for i, microphone_name in enumerate(mic_list):
    if microphone_name == mic_name:
        device_id = i
        print('Your Mic has Device id: {}'.format(device_id))
    else:
        print('Your Mic name is incorrect. It should be one of these: {}'.format(mic_list))

with sr.Microphone(device_index=device_id, sample_rate = sample_rate, chunk_size=chunk_size) as source:
    print("Say something!")
    audio = r.listen(source)

```

**Comment by Uberi** [comment]
Thanks @hassanmian, I've added this information in 271f7e9394c7bf7199d3948e055ded2b1bffa314.

@XayOn, I'm guessing it should probably work if you try [the new instructions](https://github.com/Uberi/speech_recognition#the-recognizer-hangs-on-recognizer_instancelisten-specifically-when-its-calling-microphonemicrophonestreamread). I'm going to close this for now, but if it still happens please feel free to re-open.

**Comment by XayOn** [comment]
Ir works perfectly, Thanatermesis!
