### ISSUE TITLE
STDOUT blowing up with messages

### ISSUE THREAD

**Issue by Anuluxer** [Uberi/speech_recognition#677]
When I use listen() on a recognizer it blows up my terminal, it doesn't do this on Windows, but it does on my RPI 4.

![Screenshot_88](https://user-images.githubusercontent.com/95879548/228710357-e243965f-b4f7-41ff-9696-78882d111b73.png)

**Comment by kpeabody** [comment]
I have this same exact problem!!!!  I would love to know how to fix this!!!

**Comment by Anuluxer** [comment]
> I have this same exact problem!!!! I would love to know how to fix this!!!

I figured out a fix, put this before the line containing the microphone class:
```python
devnull = os.open(os.devnull, os.O_WRONLY)
old_stderr = os.dup(2)
sys.stderr.flush()
os.dup2(devnull, 2)
os.close(devnull)
```
Then put this after the line:
```python
os.dup2(old_stderr, 2)
os.close(old_stderr)
```
So it should look something like this (example from my code):
```python
devnull = os.open(os.devnull, os.O_WRONLY)
old_stderr = os.dup(2)
sys.stderr.flush()
os.dup2(devnull, 2)
os.close(devnull)
with sr.Microphone(device_index=1) as source:
    os.dup2(old_stderr, 2)
    os.close(old_stderr)
```
