### ISSUE TITLE
recognize_whisper_api automatically translates to Italian

### ISSUE THREAD

**Issue by danielenapo** [Uberi/speech_recognition#681]
Expected behaviour
------------------

When speaking in english, recognize_whisper_api should transcribe text in english

Actual behaviour
----------------

When speaking long enough phrases, the api automatically translates to Italian (I'm in Italy), even though I spoke in English. 
in the [api documentation](https://platform.openai.com/docs/api-reference/audio/create) there is an optional "language" option. It would be nice if language could be selected when calling recognize_whisper_api as an optional argument.

**Comment by ftnext** [comment]
@danielenapo Try SpeechRecognition 3.12.0

`python -m pip install 'SpeechRecognition[openai]==3.12.0'`

```python
>>> import speech_recognition as sr
>>> r = sr.Recognizer()
>>> with sr.AudioFile("english.wav") as source:
...   audio = r.record(source)
>>> r.recognize_openai(audio, language="en")
```
