### ISSUE TITLE
ConnectionResetError when translating with Google Speech

### ISSUE THREAD

**Issue by italomaia** [Uberi/speech_recognition#69]
I have my little good looking script right here:

```
import speech_recognition as sr
r = sr.Recognizer()
def translate(file_path):
    with sr.WavFile(file_path) as source:
        audio = r.record(source)

    return r.recognize_google(audio, key=key, language=language)
```

Which reads from a wav file and translates the audio with speech recognition. I'm getting a **ConnectionResetError: [Errno 104] Connection reset by peer** all the time. I made sure the audio 
is wav 16k mono.

**Comment by italomaia** [comment]
I have read somewhere google speech has a 60s limit, so, I changed my encoder to match that:

```
call(['ffmpeg',
          '-i', mp3_path,
          '-acodec', 'pcm_s16le',
          '-ac', '1',
          '-ar', '16000',
          '-t', '50',  # 50s
          wav_path])
```

File format seems correct. Still get error:

``` 
 if "alternative" not in actual_result: raise UnknownValueError()
speech_recognition.UnknownValueError
```

**Comment by Uberi** [comment]
Hi @italomaia,

Please upload the WAV file and the script that is causing the error.

Does the WAV file example work for you (see `examples/wav_transcribe.py`)? If not, then the issue may be your connection.

**Comment by italomaia** [comment]
This is the sample: https://drive.google.com/file/d/0B9UaciTdg4eHbmk1OFR2XzhrZWc/view?usp=sharing

**Comment by italomaia** [comment]
Here is the thing, sample-10s, which is 48khz mono wav, pt-BR language, with 10s duration, works: https://drive.google.com/file/d/0B9UaciTdg4eHOXRGZkY5Wk1DTGc/view?usp=sharing

Same song, same settings, 20s duration, does not: https://drive.google.com/file/d/0B9UaciTdg4eHbFlzdG15SHI2dnM/view?usp=sharing

What do you guys think?

**Comment by italomaia** [comment]
wav_transcribe.py works with the 10s sample only.

**Comment by Uberi** [comment]
Hi @italomaia,

Your samples seem to contain music, which is confusing the speech recognizer. You may get better results by trimming those out.

It might be worth trying out the Wit.ai recognizer to see if it works a bit better - see the documentation for `recognize_wit`.
