### ISSUE TITLE
Google Speech API fail

### ISSUE THREAD

**Issue by Vincechen611** [Uberi/speech_recognition#72]
The response from google is like "addinfourl at 139816755007928 whose fp = <socket._fileobject object at 0x7f29a0c90450"

**Comment by Uberi** [comment]
Please post the entire response, or the entire traceback if there is one.

**Comment by Vincechen611** [comment]
The response.read() retrun a empty string 

line 409 of __init__.py 
in recognize_google function 
response_text = response.read().decode("utf-8")

**Comment by Uberi** [comment]
Hi @Vincechen611 ,

* What OS/OS version are you running?
* Are you able to use any of the PyAudio sample scripts? For example, [this one](https://gist.github.com/mabdrabo/8678538).
* What is the full terminal output, including the exception message and traceback? Please copy and paste this, or post a screenshot, as all of the information is necessary.

**Comment by Vincechen611** [comment]
1. I have run on ununtu 14.04 with Python 2.7.6 and windows 7 with python 2.7.10
 ps: i also try to use C# and Java to call google Speech API , C# version is also get the empty response, but java version can get the text result of the audio.
2. Yes i use the PyAudio to record the audio , i am sure that the voice is recorded into wav file and can be converted to flac file.
3. here is the response header of python 2.7.6  on ununtu 14.04 
Content-Type: application/json; charset=utf-8
Content-Disposition: attachment
Cache-Control: no-transform
X-Content-Type-Options: nosniff
Pragma: no-cache
Date: Mon, 14 Dec 2015 09:25:52 GMT
Server: S3 v1.0
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close

this is the screenshot : http://1drv.ms/1SWHnqA

**Comment by Vincechen611** [comment]
I find that google speech api not support Stero Flac now !!!!

this is the mono Flac audio file
https://drive.google.com/file/d/0B3K2J-Bb0QjEM1ZvOVZqMHE2Snc/view?usp=sharing

this is the stereo Flac audio file
https://drive.google.com/file/d/0B3K2J-Bb0QjEUjVTTXhtUEctNmM/view?usp=sharing

**Comment by Uberi** [comment]
Hi @Vincechen611,

Yeah, it's got to be a mono FLAC file at at least a 16kHz sample rate. Unfortunately there's no way around this limit.

Is this related to this issue by any chance? Are you uploading FLAC files directly instead of generating them using this library?

**Comment by Vincechen611** [comment]
In order to recognize the sound location, I have to record the stereo wav audio.
I uploading the flac data generated from "get_flac_data" function of this library to convert audio to text.
it works well until 12/11...

now i'am trying to convert stereo wav audio to  mono flac audio , but the flac converter from this library seems cant do it.

**Comment by Uberi** [comment]
Hmm, please upload a sample audio file that reproduces this issue.

The currently released version does in fact support stereo WAV. However, note that only integer formats are supported - extensible WAV is not available.

Also, it would be helpful if you post the code that you're running. I had previously assumed you were using the library itself for recording.

**Comment by Vincechen611** [comment]
This link is the stero wav audio reproduces this issue.
https://drive.google.com/file/d/0B3K2J-Bb0QjEWXhwMGlEXzRFSmM/view?usp=sharing

I add two function in "AudioData" class to save the audio data recorded from this library.
https://gist.github.com/Vincechen611/23494b38b0c70e107af7

**Comment by Uberi** [comment]
This is now confirmed working in the latest version.
