### ISSUE TITLE
Ilegal use of this repository agains Google

### ISSUE THREAD

**Issue by codreporter** [Uberi/speech_recognition#727]
Hello guys,
I have identified that this repository is exposing an illegal API Key for Google services. This issue has been reported to Google, and they have acknowledged that the use of that API Key violates Google's terms of service. They have assured that appropriate measures will be taken.

If you are using this API Key commercially for yourself or one of your clients, it is advisable to discontinue its use due to potential actions by Google.

In my opinion, the owners and collaborators of this repository have engaged in irresponsible behavior by publicly exposing an API Key obtained illicitly from Google Chrome.

Best,

**Comment by Uberi** [comment]
Hi @codreporter, thanks for sharing your opinion! Please feel free to re-open if you have an issue you'd like to see addressed.

We've also got an [issue template here](https://github.com/Uberi/speech_recognition/blob/master/.github/ISSUE_TEMPLATE.md) if you have something that can be reproduced consistently, which will make it a lot easier to address for the library maintainers!
