### ISSUE TITLE
Trying to make it run for the first time...

### ISSUE THREAD

**Issue by levanolis** [Uberi/speech_recognition#74]
Hi, 

Thank you for your code. I have just installed it and try to run an example 
"microphone_recognition.py". I typed this in examples directory.
"python microphone_recognition.py". Following are the error I got.
Can you direct to me where to start?

==========================

Traceback (most recent call last):
  File "microphone_recognition.py", line 9, in <module>
    with sr.Microphone() as source:
AttributeError: 'module' object has no attribute 'Microphone'

==========================

**Comment by LovelyHorse** [comment]
Do you have pyaudio installed?

**Comment by levanolis** [comment]
You are right. After posting, I figured I didn't install PyAudio properly. Currently working on that right now...

**Comment by levanolis** [comment]
Yes. It is working. Having other errors but at least sr.Microphone() is recognized. Thanks.

**Comment by LovelyHorse** [comment]
Great! Any issues I'd default to the demo code, it's pretty broad in usage covered.

**Comment by Uberi** [comment]
Hi @levanolis,

Feel free to post any other errors you're having. Also check out the [troubleshooting guide](https://github.com/Uberi/speech_recognition#troubleshooting) for more solutions to common problems!

**Comment by levanolis** [comment]
Thank you again. It is up and running. :-)
