### ISSUE TITLE
Error when running simple speech recognition code

### ISSUE THREAD

**Issue by General-Hex** [Uberi/speech_recognition#749]
Steps to reproduce
------------------
Running this code:
```from datetime import datetime
import speech_recognition as sr
import pyttsx3
import webbrowser
import wikipedia
import wolframalpha
import os
from termcolor import colored, cprint


ENGINE = pyttsx3.init('dummy')
VOICES = ENGINE.getProperty('voices')
ENGINE.setProperty('voice', VOICES[0].id)
ACTIVATION_WORD = "echo"

def Command_recognition():
    listener = sr.Recognizer()
    os.system('clear')
    activated_text = colored('ACTIVATED','light_green', attrs=['blink', 'bold'])
    print(activated_text)
    
    with sr.Microphone(device_index=1) as source:
        listener.pause_threshold = 2
        command = listener.listen(source)
    
    try:
        listening_text = colored('LISTENING...','light_green', attrs=['blink'])
        print(listening_text)
        query = listener.recognize_google_cloud(command, language='en_gb')
    except Exception as exception:
        error_text = colored('ERROR','red', attrs=['blink', 'bold'])
        print('\n'+error_text)
        print(exception)
        quit()
    return query


query1 = Command_recognition()
print(query1)
```

Expected behaviour
------------------
Run normally without issues and print speech input

Actual behaviour
----------------
crashed with this error code:
||PaMacCore (AUHAL)|| AUHAL component not found.Traceback (most recent call last):
  File "/Users/ryan/Desktop/stuff/code/Project Echo/__main__.py", line 29, in Command_recognition
    command = listener.listen(source)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/anaconda3/lib/python3.11/site-packages/speech_recognition/__init__.py", line 466, in listen
    assert source.stream is not None, "Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryan/Desktop/stuff/code/Project Echo/__main__.py", line 43, in <module>
    query1 = Command_recognition()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/Desktop/stuff/code/Project Echo/__main__.py", line 27, in Command_recognition
    with sr.Microphone(device_index=1) as source:
  File "/Users/ryan/anaconda3/lib/python3.11/site-packages/speech_recognition/__init__.py", line 189, in __exit__
    self.stream.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'

System information
------------------

(Delete all the statements that don't apply.)

My MacOS Sonoma 14.4.1

My **Python version** is 3.11.0

My **Pip version** is 23.1.2

My **SpeechRecognition library version** is 3.10.3

My **PyAudio library version** is 0.2.14

My **microphones** are: ['Ryan’s iPhone 15 Pro Microphone', 'MacBook Pro Microphone', 'MacBook Pro Speakers']

My **working microphones** are:  the code outputs this: ||PaMacCore (AUHAL)|| AUHAL component not found.||PaMacCore (AUHAL)|| AUHAL component not found.{}

Also to note I am using a Anaconda environment

**Comment by thedarknight01** [comment]
Hey @General-Hex,
This error typically indicates issues in accessing the audio hardware. 
To resolve this, please ensure that your audio hardware is properly connected and configured. Also, make sure that your device isn't blocking the access request.

**Comment by General-Hex** [comment]
> Hey @General-Hex, This error typically indicates issues in accessing the audio hardware. To resolve this, please ensure that your audio hardware is properly connected and configured. Also, make sure that your device isn't blocking the access request.

I’ve tried everything, I’m only using the inbuilt microphone of the MacBook and I have given both terminal and VScode all possible permissions including full disk access and microphone access still to no avail

**Comment by thedarknight01** [comment]
Please check this out 
[Link to the issue](https://github.com/spatialaudio/python-sounddevice/issues/299).

**Comment by General-Hex** [comment]
None of those solutions have worked for me, do you have any specific solutions for me to try?

**Comment by General-Hex** [comment]
@thedarknight01 I also tried disabling all firewalls/filters, giving all permissions to vscode and terminal and also connecting a seperate microphone and using that device index to no avail. I tried uninstalling and reinstalling speech recognition, pyaudio and portaudio again to no avail. Apparently many people on macbooks (Mainly on M-chip series) are having this issue, is there any specific solution that has worked for them?

**Comment by thedarknight01** [comment]
Please attempt these commands as the standard installation seems to be encountering issues. This alternative method often resolves many problems.
```
brew uninstall portaudio
brew install portaudio --HEAD
```

**Comment by General-Hex** [comment]
@thedarknight01 I’ve tried that multiple times sadly to no success. This is very frustrating because I had a plan for a super cool project but it isn’t possible without speech recognition. What else can I try?

**Comment by thedarknight01** [comment]
I apologize for the inconvenience; I was having the same problem, which I resolved with the step. I'm unsure why, this is not working but don't worry—I'll figure something out.

**Comment by General-Hex** [comment]
@thedarknight01 thank you. Also I fully understand that this is not your fault and out of your control because apple probably did some sort of silly update that messed with things. let me know if there is any tests/anything else you would like me to try 😊

**Comment by General-Hex** [comment]
can't install pyaudio with the first command, gives this error:
```conda install -c conda-forge pyaudio
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pyaudio

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.```

**Comment by thedarknight01** [comment]
try after updating conda 
```
conda update conda
```

**Comment by General-Hex** [comment]
IT WORKED, I don't know what did it but it finally worked, this is what i did:

1. fully uninstalled portaudio, pyaudio and speech recognition. 
2. ran brew update && brew install portaudio --HEAD
3. ran python -m pip install pyaudio --no-cache
4. ran python -m pip install speechrecognition 

and IT WORKED

only problem is that now for some reason this line is giving an error but not saying what the error is:
```query = listener.recognize_google_cloud(command, language='en_gb')```

**Comment by General-Hex** [comment]
oh because I need an account and its paid, i'll probably use openai whisper for that then but thank you very much 😊 (hopefully other people with this issue can solve it too)

**Comment by General-Hex** [comment]
OMG as soon as I closed the issue and tried to run the code again IN THE EXACT SAME WAY it starting throwing the attribute error again

**Comment by thedarknight01** [comment]
@General-Hex I was about to suggest that authenticity may be the problem. 
Now if your issue is solved please close the issue.
Happy Coding 😊.

**Comment by General-Hex** [comment]
the error started again, I changed NOTHING, it just stopped working all of a sudden

**Comment by General-Hex** [comment]
the attribute error that is with not being able to use my microphone, not the account error

**Comment by General-Hex** [comment]
I just updated my conda, could you give me a simple code to copy and paste to try because i'm currently using my original code (in my original issue post) which is only 47 lines long

**Comment by General-Hex** [comment]
its strange because it began working for 3 times i ran the code, then as soon as I closed this issue and tired one last time it failed

**Comment by General-Hex** [comment]
@thedarknight01 I SOLVED IT

the problem is that your iphone keeps connecting/disconnecting from your macbook meaning it keeps going into index 0 of the list of devices.

**Comment by General-Hex** [comment]
@thedarknight01 adding these lines of code should stop the issue for others too (but changing the name with the name of their own phone ofc):

```python 
devices = sr.Microphone.list_microphone_names()
    if devices[0] == 'Ryan’s iPhone 15 Pro Microphone': index = 1
    else: index = 0
    with sr.Microphone(device_index=index) as source:```

**Comment by thedarknight01** [comment]
devices = sr.Microphone.list_microphone_names() 
print(devices)
run this check the name of your microphone and replace it from there

**Comment by General-Hex** [comment]
I have before that is how I found the error, it gives the following:
['MacBook Pro Microphone', 'MacBook Pro Speakers'] or ['Ryan’s iPhone 15 Pro Microphone', 'MacBook Pro Microphone', 'MacBook Pro Speakers'] depending if my phone is connected or not which randomly changes
