### ISSUE TITLE
The python 'aifc' library is removed in python 3.13.0

### ISSUE THREAD

**Issue by aaronmader** [Uberi/speech_recognition#775]
The speech_recognition library is unable to run on python 3.13.0, because of the removal of standard libraries like aifc (and possibly others)

We probably just need to specify a new dependency, possibly https://pypi.org/project/standard-aifc/ ?
Note: I haven't done my due-diligence evaluating this library or its maintainer.

**Comment by ftnext** [comment]
As written in the metadata, the current SpeechRecognition (3.11.0) supports Python 3.9 through 3.12.
We welcome information of migration where aifc is moving to add support for 3.13 in the future.
`standard-aifc` might be one of the candidates (verification needed), thanks!

---

links
* https://docs.python.org/3/whatsnew/3.13.html#whatsnew313-pep594
* https://peps.python.org/pep-0594/#aifc

**Comment by ftnext** [comment]
pytest mentions **'audioop' removal** as well as 'aifc'.
https://github.com/Uberi/speech_recognition/actions/runs/11643697199/job/32424738545

```
=============================== warnings summary ===============================
speech_recognition/__init__.py:7
  /home/runner/work/speech_recognition/speech_recognition/speech_recognition/__init__.py:7: DeprecationWarning: 'aifc' is deprecated and slated for removal in Python 3.13
    import aifc

speech_recognition/__init__.py:8
  /home/runner/work/speech_recognition/speech_recognition/speech_recognition/__init__.py:8: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
    import audioop
```

**Comment by ftnext** [comment]
Added in setup.py
https://github.com/Uberi/speech_recognition/blob/46bb4705775c6b5af3432c104ce3450dfa2669d4/setup.py#L73-L77

TODO: Run tests on Python 3.13 (but PyTorch (openai-whisper depends) doesn't support 3.13 yet, so we need to skip some tests)

**Comment by ftnext** [comment]
```
% python -V
Python 3.13.0

% python -m pip install standard-aifc setuptools
% python -m pip install --no-build-isolation git+https://github.com/Uberi/speech_recognition
```
