### ISSUE TITLE
How do I stop it listening to itself?

### ISSUE THREAD

**Issue by s4chin** [Uberi/speech_recognition#78]
This is the code:
```py
import speech_recognition as sr
import subprocess

r = sr.Recognizer()
m = sr.Microphone()

def say(text):
    return subprocess.call("espeak -s 155 -a 200 '"+text+"'", shell=True)

try:
    print("A moment of silence, please...")
    with m as source:
        r.adjust_for_ambient_noise(source)
        print("Set minimum energy threshold to {}".format(r.energy_threshold))
        while True:
            print("Say something!")
            audio = r.listen(source)
            print("Got it! Now to recognize it...")
            try:
                # recognize speech using Google Speech Recognition
                value = r.recognize_google(audio)

                # we need some special handling here to correctly print unicode characters to standard output
                if str is bytes: # this version of Python uses bytes for strings (Python 2)
                    say(u"You said {}".format(value).encode("utf-8"))
                else: # this version of Python uses unicode for strings (Python 3+)
                    say("You said {}".format(value))
            except sr.UnknownValueError:
                print("Oops! Didn't catch that")
            except sr.RequestError as e:
                print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
except KeyboardInterrupt:
    pass
```
Thus, I want it to say what I say. But with the above code, it keeps listening to itself and thus keeps saying what it listens. Is there anyway I could stop the listener when I want it to speak?

**Comment by LovelyHorse** [comment]
I'd say there are a couple of ways you could achieve this and it really depends on your contraints; do you need it to be listening for new inputs while it reads the result aloud? 

The easiest option I see is to manipulate the recogniser's energy threshold to some incredibly high arbitrary value while you execute your say(text) method. you'll need to pass (r) into say() to achieve this; something like the following may work.
    try:
        say(u"You said {}".format(value).encode("utf-8"), r)

and in say respectively:

    def say (text, r):
        store = r.energy_threshold
        r.energy_threshold = 9001 # note I'm not sure what the maximum value is
        subprocess.call("espeak -s 155 -a 200 '"+text+"'", shell=True)
        r.energy_threshhold = store;
        return true

Hopefully that helps.

**Comment by Uberi** [comment]
@LovelyHorse has the right idea! However, that way in particular won't have any effect, since this threshold is only read in `r.listen`, so by the time we call it again it won't be modified!

I recommend you simply not keep the microphone on when you don't want to be listening. I have tested and confirmed that the following code works:

```python
import speech_recognition as sr
import subprocess, time

r = sr.Recognizer()
m = sr.Microphone()

def say(text):
    return subprocess.call("espeak -s 155 -a 200 '" + text + "'", shell=True)

try:
    print("A moment of silence, please...")
    with m as source: r.adjust_for_ambient_noise(source)
    print("Set minimum energy threshold to {}".format(r.energy_threshold))
    while True:
        print("Say something!")
        with m as source: audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            # recognize speech using Google Speech Recognition
            value = r.recognize_google(audio)

            # we need some special handling here to correctly print unicode characters to standard output
            if str is bytes: # this version of Python uses bytes for strings (Python 2)
                say(u"You said {}".format(value).encode("utf-8"))
            else: # this version of Python uses unicode for strings (Python 3+)
                say("You said {}".format(value))
        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except sr.RequestError as e:
            print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
        time.sleep(0.5) # sleep for a little bit
except KeyboardInterrupt:
    pass
```

One more thing. Using `subprocess.call` with `shell=True` is **VERY VERY DANGEROUS**. If I were to somehow say `' && rm -rf --no-preserve-root '/`, the script would delete all the files on your computer.

You can solve this by not using the `shell=True` option (so you'll need to fully qualify the path to `espeak`), and do the necessary escaping. I recommend using the Python espeak library instead.

**Comment by s4chin** [comment]
Thanks guys! :smile: :+1:
I think I'll close this.

**Comment by m7mdcc** [comment]
Hello @Uberi , i'm in the same boat with @s4chin  , how i cant stop mic when i need to say ? 

i have 2 classes 
Recognizer : 

`import speech_recognition as sr
from SpeechToText import SpeechToText
import time

class Recognizer:
    def __init__(self, lang='en-US', ttslang='en', provider='bing'):
        self.language = lang
        self.ttslanguage = ttslang
        self.provider = provider
        self.r = sr.Recognizer()
        self.m = sr.Microphone()
        self.startListening()

    def startListening(self):
        # received audio data, now we'll recognize it using Google Speech Recognition
        with self.m as self.source:
            self.r.adjust_for_ambient_noise(self.source)
            self.r.pause_threshold = 0.5
            self.r.non_speaking_duration = self.r.pause_threshold - 0.1
            self.audio = self.r.listen(self.source)
            print("listening...")


            while True:
                stop_listening = self.r.listen_in_background(self.m, self.callback())
                print("listening...")
    def callback(self):
        print("callback called")
        txty = None
        try:
            if self.provider == "bing":
                txty = self.r.recognize_bing(self.audio, key="5a5a284df38445b3961ecd49c01142f7",
                                             language=self.language)
            elif self.provider == "google":
                txty = self.r.recognize_google(self.audio, key="5a5a284df38445b3961ecd49c01142f7",
                                               language=self.language)
            elif self.provider == "sphinx":
                txty = self.r.recognize_sphinx(self.audio)
        except sr.UnknownValueError:
            print("Frank could not understand audio")

        except sr.RequestError as e:
            print("Could not request results from Speech Recognition service Provider; {0}".format(e))
        if txty is not None :
         txtyto = "Hello I'm Frank How I can help you ? "
         print("Frank thinks you said " + txty)
         if "hello" in txty.lower():
            print("OK SAY SAY OK SAY SAY OK SAY SAY ")
            self.speechtotxt = SpeechToText(language=self.ttslanguage)
            self.speechtotxt.say(txtyto)
`


Speechtotext : 
# -*- coding: UTF-8 -*-
import os
from gtts import gTTS
import tempfile
import pygame


class SpeechToText:
    def __init__(self, language='en'):
        self.language = language

    def say(self, phrase):
        tts = gTTS(text=phrase, lang=self.language)
        with tempfile.NamedTemporaryFile(suffix='.mp3', delete=True) as f:
            tmpfile = f.name
            print(tmpfile)
        tts.save(tmpfile)
        self.play_mp3(tmpfile)
        os.remove(tmpfile)

    def play_mp3(self, filename):
        pygame.mixer.init()
        pygame.mixer.music.load(filename)
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
        pygame.mixer.quit()

**Comment by m7mdcc** [comment]
UPDATE : i'm trying to use 
 stop_listening = r.listen_in_background(m, say(txt))
           time.sleep(5)
           stop_listening()

its work , but always show error 
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 596, in threaded_listen
    with source as s:
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 130, in __enter__
    assert self.stream is None, "This audio source is already inside a context manager"
AssertionError: This audio source is already inside a context manager

When its called .

**Comment by m7mdcc** [comment]
Hi again , 
I try your example , Its listen to itself .. Also i try listen in background with call back function but its return error about " cant join thread . " i guess it's threading issue ?

**Comment by MaMallu** [comment]
Traceback (most recent call last):
  File "/home/pi/Desktop/mallutry/noisecanceltry1.py", line 40, in <module>
    m = sr.Microphone()
  File "/usr/local/lib/python3.4/dist-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/usr/local/lib/python3.4/dist-packages/speech_recognition/__init__.py", line 108, in get_pyaudio
    import pyaudio
  File "/home/pi/Desktop/mallutry/pyaudio.py", line 4, in <module>
    FORMAT = pyaudio.paInt16
AttributeError: 'module' object has no attribute 'paInt16'
 please3 can u help me i am getting error like this.i am running it on raspberry pi jessie .i want to remove the background noise as well as.my microphone taking lot time to capture my voice i am using google speech recognition for speech to text.please can help me how to overcome it...

**Comment by Uberi** [comment]
@MaMallu Please open a new issue by filling in the issue template - this issue is closed.
