### ISSUE TITLE
Sphix support?

### ISSUE THREAD

**Issue by blacksector** [Uberi/speech_recognition#79]
I see that there is a method that is in the works for Sphix. Any idea if you might get this done? I haven't been able to get it to work by myself. Pretty complex and i get too lost in the CMU pocketsphinx documentation as well, Any ideas? :)

**Comment by blacksector** [comment]
I just noticed the offline speech recognition branch. Sorry about that!

**Comment by LovelyHorse** [comment]
No worries; just further to that (I'm unfamiliar with the branch), there's a minimal sphinx method in recognizers available via: 

    recognizer_instance.recognize_sphinx(audio_data, language , show_all = False)

code as seen in __init__.py:

    def recognize_sphinx(self, audio_data, language = "en-US", show_all = False):
        """
        ;wip
        """
        assert isinstance(audio_data, AudioData), "`audio_data` must be audio data"
        assert isinstance(language, str), "`language` must be a string"

        flac_data, sample_rate = audio_data.get_flac_data(), audio_data.sample_rate
        
        # no transcriptions available
        raise UnknownValueError()

**Comment by blacksector** [comment]
@LovelyHorse In the main branch correct? I have found that but wasn't sure exactly how it was functioning or more important how to get it to work. I think I might switch over to my Linux box today and test it out there.

**Comment by Uberi** [comment]
Hi @blacksector,

The Sphinx functionality in the offline-recognition branch is basically complete. If you install it from there, you will have a working Sphinx setup.

However, I haven't released yet since I'm still writing docs and instructions. If you have any troubles with it before it's released, feel free to comment on this issue about them.

**Comment by blacksector** [comment]
@Uberi great thanks Anthony. I am going to be trying it out in a bit. On the other hand quick question you stated that the Google API Key is a public key. When do you think it might run out? Or Google might just discontinue it?

**Comment by Uberi** [comment]
I make no guarantees on it being usable in the future. However, it is the same one used by Chrome, which means it is likely to be valid for a while yet.

**Comment by blacksector** [comment]
@Uberi Didn't know it was part of the Chrome API Key :) So it is likely it will be around for a while, but we shall see. Thank you by the way!
