### ISSUE TITLE
Adding a base_url parameter to the recognize_whisper_api function.

### ISSUE THREAD

**Issue by amosdevstudio** [Uberi/speech_recognition#794]
Just that. I would like to use the Groq API (https://groq.com/), but to do that I had to change the library's code. It's a simple fix, actually.

**Comment by ftnext** [comment]
Groq provides whisper models. I see...
https://console.groq.com/docs/speech-text

**Comment by amosdevstudio** [comment]
Yes, exactly. That's why i need the base_url parameter. To use groq i need to put their url there and their api key.

**Comment by amosdevstudio** [comment]
Hey, could you merge the PR?

**Comment by ftnext** [comment]
Thanks the PR, but I want to use [groq](https://pypi.org/project/groq/) library.
Draft: https://github.com/Uberi/speech_recognition/pull/797/commits/a0999389c38f986abd6bd29bd4c73e16a55a3b47

In Groq documentation, groq library is used.
From my viewpoint, openai library with base_url seems kind of hack for workaround.

**Comment by ftnext** [comment]
@amosdevstudio Try SpeechRecognition 3.12.0, which supports Groq.

`python -m pip install SpeechRecognition==3.12.0`

```python
>>> # NOTICE: export GROQ_API_KEY before launching Python interpreter
>>> import speech_recognition as sr
>>> r = sr.Recognizer()
>>> with sr.AudioFile("english.wav") as source:
...   audio = r.record(source)
>>>
>>> r.recognize_groq(audio)
' One, two, three.'
```

**Comment by amosdevstudio** [comment]
Great! I love to see this.
