### ISSUE TITLE
Speech Recognition without punctuation

### ISSUE THREAD

**Issue by jhoelzl** [Uberi/speech_recognition#80]
Hello,

i am trying Google Speech Recognition with German and English, however, the text output does not contain any punctuation marks. Is there a way to get these additional info (if available) or is this standard behaviour?

Example: I say `Hello, my Name is John. How are you today? Where are your parents?`
and i get: `hello my name is john how are you today where are your parents`

I know it is very difficult to predict these punctuations, but does Google provide this? 
Or do you know any other Speech Recognition service that offers such feature?

Thanks for help!
Regards,
Josef

**Comment by Uberi** [comment]
I am not aware of any recognizer that can do this reliably (this is still an active area of research).

Punctuation is generally inferred from context and less from the sounds themselves, so your best bet is to process the text itself.

The Sphinx recognizer [can do it a bit](http://cmusphinx.sourceforge.net/wiki/postpframework), but it doesn't have very usable accuracy. Also, it takes a lot more effort to set up.

Of course, you could always set a short `recognizer_instance.pause_threshold`, repeatedly call `recognizer_instance.listen`, and then add a period after each result and append all of them together. Very hacky though.

**Comment by jhoelzl** [comment]
Thanks, i will try both of your ideas!

**Comment by Shane-Neeley** [comment]
This is available now!

https://github.com/Uberi/speech_recognition/pull/432
