### ISSUE TITLE
Missing Microphone object in virtualenv

### ISSUE THREAD

**Issue by jhoelzl** [Uberi/speech_recognition#81]
Hello,

when using `virtualenv` with Python 2.7.6 and latest speech_recognition package, the Microphone object can not be used.

```
import speech_recognition as sr
r = sr.Recognizer()
m = sr.Microphone() 
```
Console output:

> m = sr.Microphone()  
> AttributeError: 'module' object has no attribute 'Microphone'

Of course, the package is installed in virtualenv using pip.
However, when virtualenv is deactivated, the code works with the same Python and speech_recognition package version without error.

Do you have an idea how to solve this?

Thanks,
Josef

**Comment by LovelyHorse** [comment]
The first thing that comes to mind is that PyAudio may not be loading properly with virtualenv. I'm not too familiar with virtualenv however; though I'd make sure it's properly bundled.

**Comment by jhoelzl** [comment]
Yes, you are right, after installing PyAudio it worked. Thanks!
