### ISSUE TITLE
Exception  occurs while recording larger .wav files

### ISSUE THREAD

**Issue by rakhi27** [Uberi/speech_recognition#83]
My requirement is to get the speech from .mp3 file. so I am converting the .mp3 file to .wav file with **pydub** (https://github.com/jiaaro/pydub). Here if my mp3 file is larger than 6:00 min length the code stuck suddenly and the terminal becomes unresponsive. 

so I have given duration for record() as 10sec based on the total duration of the file.
then it works fine but gives inaccurate results. And I am not able to get the frequency of the wav audio file at specific time.

```
r = sr.Recognizer()
with sr.WavFile(WAV_FILE) as source:
    for off in range(int(source.DURATION/10)):
        audio = r.record(source, duration=10)
        try:
            print("Audio says:::::::: \n" + r.recognize_sphinx(audio))
        except sr.UnknownValueError:
            print("Could not understand audio")
```

could you please replay me how to fix this issue

**Comment by Uberi** [comment]
Hi @rakhi27,

Please give the following information:

* Your system information (including versions for PyAudio, SpeechRecognition, and PocketSphinx)
* Steps to reproduce, as well as any files needed to do so.
* Whether it works with `recognize_google` instead of `recognize_sphinx`

**Comment by rakhi27** [comment]
Hi @Uberi,

I am not using PyAudio as I am not dealing with microphone.
Requirements:
--> pocketsphinx==0.0.9
--> pydub==0.16.3
--> SpeechRecognition==3.2.1

if I use `recognize_google`, it gives entirely irrelevant results
please once check it with this file.
([http://hwcdn.libsyn.com/p/a/3/b/a3b7a1d949f9b444/English_Mastery_Formula.mp3?c_id=1940943&expiration=1456122325&hwt=cf4c62aa43c3acf3a39528dce6038103])

I am providing my entire code here.

```
import speech_recognition as sr
from os import path
import pydub

sound = pydub.AudioSegment.from_mp3("English_Mastery_Formula.mp3")
sound.export("export.wav", format="wav")
print "export done"
WAV_FILE = path.join(path.dirname(path.realpath(__file__)), "export.wav")

r = sr.Recognizer()
with sr.WavFile(WAV_FILE) as source:
    for off in range(int(source.DURATION/10)):
        audio = r.record(source, duration=10)
        try:
            print("Audio says:::::::: \n" + r.recognize_sphinx(audio))
        except sr.UnknownValueError:
            print("Could not understand audio")
```

**Comment by Uberi** [comment]
@rakhi27,

I tried the code you posted as-is, but it did not give an exception.

Can you try converting the MP3 to a WAV manually, then seeing if it loads correctly? Also, please upload `segment.wav` after running the following:

```python
import speech_recognition as sr
from os import path
import pydub

sound = pydub.AudioSegment.from_mp3("English_Mastery_Formula.mp3")
sound.export("export.wav", format="wav")
print "export done"
WAV_FILE = path.join(path.dirname(path.realpath(__file__)), "export.wav")

r = sr.Recognizer()
with sr.WavFile(WAV_FILE) as source:
    for offset in range(int(source.DURATION / 10)):
        audio = r.record(source, duration=10)
        try:
            print(offset, ":", r.recognize_sphinx(audio))
        except sr.UnknownValueError:
            print("Could not understand audio")
            wav_data = audio.get_wav_data(convert_rate = 16000, convert_width = 2)
            print(offset)
            with open("segment.wav", "wb") as f: f.write(wav_data)
            break
```

**Comment by Uberi** [comment]
Seems like this issue is resolved - please re-open if this is not the case!
