### ISSUE TITLE
Method to start listening

### ISSUE THREAD

**Issue by gunthercox** [Uberi/speech_recognition#88]
Hi, I am looking at the [background_listening.py](https://github.com/Uberi/speech_recognition/blob/master/examples/background_listening.py) example you have. To stop listening, the `stop_listening` function is called.

```python
stop_listening = r.listen_in_background(m, callback)
```

I was wondering if there was a way to pause the listening process? For example, I am looking at using this library along with a speech synthesis library. My goal is to have the program stop listening before it speaks so that it doesn't hear itself.

Currently, I am stopping the listening process and then re-instantiating the microphone and recognizer every time the program speaks. This works fine, but it takes a bit of time for the microphone to adjust for ambient noise.

Do you know if there is a way that I can pause the listening process so that it can then be resumed at a later point?

**Comment by Uberi** [comment]
Hi @gunthercox,

The recommended way to do this is to stop the listening thread and restart it, as you stated.

Note that you don't have to adjust for ambient noise every time you start listening. Adjusting it once will retain those adjustments even when you start/stop listening multiple times.

For example:

```python
import time
import speech_recognition as sr
def callback(recognizer, audio):
        print("YOU SAID: " + recognizer.recognize_google(audio))
r = sr.Recognizer()
m = sr.Microphone()
with m as source:
    r.adjust_for_ambient_noise(source) # we only need to calibrate once, before we start listening
stop_listening = r.listen_in_background(m, callback)
time.sleep(5)
stop_listening()
# do other stuff like talking here
stop_listening = r.listen_in_background(m, callback) # we're going to start listening here again, and we didn't have to adjust again
time.sleep(5)
stop_listening()
```

**Comment by gunthercox** [comment]
Thank you! That is exactly what I was looking for.
