### ISSUE TITLE
Integrate Nuance CloudService

### ISSUE THREAD

**Issue by jhoelzl** [Uberi/speech_recognition#92]
Hello,

it would be nice if you can integrate the Nuance ASR Cloud Service in this framework:
http://nuancedev.github.io/samples/http/python/

Regards,
Josef

**Comment by Uberi** [comment]
Hi @jhoelzl,

Unfortunately, this API doesn't seem to have a free tier or trial.

**Comment by jhoelzl** [comment]
hi @Uberi, sure there is a trial. After free registration you get a sandbox account with 5000 transactions per day.

**Comment by Uberi** [comment]
Ah, I didn't see that earlier from the pricing page. Since there seems to be a fair bit of demand for this, we'll try to have it in within the next few releases.

**Comment by jhoelzl** [comment]
Added pull request #117 , but audio data stream has to be adjusted otherwise API returns timeout.
