### ISSUE TITLE
install will not work

### ISSUE THREAD

**Issue by eragon898** [Uberi/speech_recognition#93]
when installing speech recognition I use  pip install SpeechRecognition to install on my raspberry pi 2. it down loads the file this start running the build. a few seconds later I get an error saying "could not create '/usr/lecal/lib/python2.7/dist-packages/speech_recognition': permission denied ".

**Comment by Uberi** [comment]
Hi @eragon898,

You need elevated privileges to install globally on Raspbian. Run `sudo pip install SpeechRecognition` instead.
