### ISSUE TITLE
RuntimeError: new_Decoder returned -1

### ISSUE THREAD

**Issue by Suresh-Subedi** [Uberi/speech_recognition#95]
Steps to reproduce
------------------

1. When running example file extended_results.py I get this error.

Expected behaviour
------------------

get text output of example english.wav file

Actual behaviour
----------------
I got following stack trace:

INFO: cmd_ln.c(697): Parsing command line:

Current configuration:
[NAME]                  [DEFLT]         [VALUE]
-agc                    none            none
-agcthresh              2.0             2.000000e+000
-allphone
-allphone_ci            no              no
-alpha                  0.97            9.700000e-001
-ascale                 20.0            2.000000e+001
......
-vad_prespeech          20              20
-vad_startspeech        10              10
-vad_threshold          2.0             2.000000e+000
-var
-varfloor               0.0001          1.000000e-004
-varnorm                no              no
-verbose                no              no
-warp_params
-warp_type              inverse_linear  inverse_linear
-wbeam                  7e-29           7.000000e-029
-wip                    0.65            6.500000e-001
-wlen                   0.025625        2.562500e-002

Traceback (most recent call last):
  File "C:\Users\Suresh SUBEDI\Desktop\python\speech_recognition\extended_result
s.py", line 16, in <module>
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
  File "C:\Python34\lib\site-packages\speech_recognition\__init__.py", line 503,
 in recognize_sphinx
    decoder = pocketsphinx.Decoder(config)
  File "C:\Python34\lib\site-packages\pocketsphinx\pocketsphinx.py", line 227, i
n __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

System information
------------------
My **SpeechRecognition library version** is 3.3.3

My **PyAudio library version** is 0.2.9

I **installed PocketSphinx from** https://pypi.python.org/packages/3.4/p/pocketsphinx/pocketsphinx-0.0.5-cp34-none-win32.whl#md5=91f8aa702d895473475a7c22edb0f4e9.

**Comment by Uberi** [comment]
Hi @Suresh-Subedi,

You have a very old version of PocketSphinx, 0.0.5, while we're currently distributing 0.0.9. The solution is to update it.

Since it seems like you're on Windows, you should be using the prebuilt binaries here: https://github.com/Uberi/speech_recognition/tree/master/third-party.

If you need 32-bit libraries, there are several here as well: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pocketsphinx

Please re-open if issues persist.

**Comment by choudharykrish** [comment]
This solved my problem

https://stackoverflow.com/questions/44339312/new-decoder-returned-1-when-trying-to-run-pocketsphinx-on-raspberry-pi/51346264#51346264
