### ISSUE TITLE
Support for Microsoft Bing/Project Oxford speech recognition?

### ISSUE THREAD

**Issue by wiseman** [Uberi/speech_recognition#97]
Have you considered support for Microsoft's Bing/Project Oxford speech recognition? https://msdn.microsoft.com/library/mt656780.aspx

**Comment by jhoelzl** [comment]
+1

**Comment by Uberi** [comment]
Interesting, is this open access, or is there a link at which we can sign up and test it?

**Comment by wiseman** [comment]
It's available for free for testing. E.g. go to https://www.projectoxford.ai/speech and follow the "Try for free" link, which should prompt you to login/create and Azure account and let you enable the Speech API.

**Comment by LovelyHorse** [comment]
I've methods for this; might create a pull request in the next couple of days. The biggest pain in the ass was it required token validation mechanisms, to be checked and refreshed before making requests. Oxford is a great API, much faster than Watson and a hell of a lot more reliable.

**Comment by Uberi** [comment]
Thanks @LovelyHorse, I'll take a look. From what I can tell, it's pretty fast/accurate, so sounds like a good addition for the next release!

**Comment by Uberi** [comment]
Version 3.4.1 now has `recognize_bing`, which uses the Microsoft Bing Voice Recognition API service. It's indeed quite nice.
