### ISSUE TITLE
sample_width standardization

### ISSUE THREAD

**Issue by zhaoqf123** [Uberi/speech_recognition#98]
Steps to reproduce
------------------

Audio file used: http://www.wavsource.com/snds_2016-03-13_7646817315637486/people/men/about_time.wav

Run following codes:
`import speech_recognition as sr`
`# obtain path to "about_time.wav" in the same folder as this script`
`audio_file = "about_time.wav"`
`from os import path`
`WAV_FILE = path.join(path.dirname(path.realpath('__file__')), audio_file)`
`r = sr.Recognizer()`
`with sr.WavFile(WAV_FILE) as source:`
`    audio = r.record(source) # read the entire WAV file`

Expected behaviour
------------------

No error or warning

Actual behaviour
----------------

`---------------------------------------------------------------------------`
`AssertionError                            Traceback (most recent call last)`
`<ipython-input-38-cd847f64b67d> in <module>()`
`      3 r = sr.Recognizer()`
`      4 with sr.WavFile(WAV_FILE) as source:`
`----> 5     audio = r.record(source) # read the entire WAV file`

`/Library/Python/2.7/site-packages/speech_recognition/__init__.py in record(self, source, duration, offset)`
`    334 #        print source.SAMPLE_RATE`
`    335 #        print source.SAMPLE_WIDTH`
`--> 336         return AudioData(frame_data, source.SAMPLE_RATE, source.SAMPLE_WIDTH)`
`    337 `
`    338     def adjust_for_ambient_noise(self, source, duration = 1):`

`/Library/Python/2.7/site-packages/speech_recognition/__init__.py in __init__(self, frame_data, sample_rate, sample_width)`
`    193     def __init__(self, frame_data, sample_rate, sample_width):`
`    194         assert sample_rate > 0, "Sample rate must be a positive integer"`
`--> 195         assert sample_width % 1 == 0 and 2 <= sample_width <= 4, "Sample width must be 2, 3, or 4"`
`    196         self.frame_data = frame_data`
`    197         self.sample_rate = sample_rate`

`AssertionError: Sample width must be 2, 3, or 4`

How I solve it
------------------
I go into source code, and change the following code:
`assert sample_width % 1 == 0 and 2 <= sample_width <= 4, "Sample width must be 2, 3, or 4"`
into:
`assert sample_width % 1 == 0 and 1 <= sample_width <= 4, "Sample width must be 2, 3, or 4"`

And then Google API output the correct results. The code is:
`# recognize speech using Google Speech Recognition`
`try:`
`    print("Google Speech Recognition thinks you said " + r.recognize_google(audio))`
`except sr.UnknownValueError:`
`    print("Google Speech Recognition could not understand audio")`
`except sr.RequestError as e:`
`    print("Could not request results from Google Speech Recognition service; {0}".format(e))`

My question
------------------
Why should the sample width threshold be set in domain [2,4]? I googled sample width and found that it means volume of the audio, and its value could be larger than 4.

My **SpeechRecognition library version** is 3.3.3

**Comment by Uberi** [comment]
Hi @zhaoqf123,

Full 8-bit WAV support has been added in version 3.4.1. Give it a try!
