### ISSUE TITLE
Standalone offline version

### ISSUE THREAD

**Issue by johnfelipe** [Uberi/speech_recognition#99]
This software can execute offline standalone?

**Comment by jhoelzl** [comment]
Yes, when you use CMUSphinx as a speech recognition service you can handle this.

**Comment by johnfelipe** [comment]
i use Dragon Naturally Speaking professional 13, offline and standalone, my acuracy is 93% for spanish lang, what is acuracy for this?

**Comment by jhoelzl** [comment]
When using CMUSphinx you can and have to use your own language models. Some models for few languages are available on [Sourceforge](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/) but form my point of view very outdated. I do not think hat CMUSphinx performs better than Dragon...

**Comment by johnfelipe** [comment]
what speech recognition service is equal like Dragon?

**Comment by jhoelzl** [comment]
Maybe you can use [Kaldi](https://github.com/kaldi-asr/kaldi), but i have no experience with this tool. There are some papers that are using this framework and i think it is often used in scientific works.

If you now another offline speech recognition system i would also appreciate it to share your knowledge with us :)

**Comment by Uberi** [comment]
Hi @johnfelipe,

This library already supports Sphinx for offline recognition. Note that we actually bundle models to simplify usage; you don't actually have to spend hours wrangling dependencies and putting everything together.

As jhoelzl mentioned, Kaldi is a good option as well. However, it takes a lot more work to set up, has very limited cross-platform support, and doesn't come with any models.

**Comment by johnfelipe** [comment]
no only DNS 13 PRO, is better acuracy i try, then only offline version is CMU but is not better than Dragon
